In [1]:
import pandas as pd
import numpy as np
import tabula

C:\Users\Usuario\AppData\Local\Temp\ipykernel_10512\3008533230.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
pdf = "../Inputs/Doc1/DocEconomica_731956_3_1_1_2020_11_04_19_44_42_860.pdf"

In [3]:
first = tabula.read_pdf(pdf, pages=1, area=(100,19,816,577), lattice=True, output_format="dataframe", encoding="latin-1")
second = tabula.read_pdf(pdf, pages=2, area=(20,19,823,575), lattice=True, output_format="dataframe", encoding="latin-1")
third = tabula.read_pdf(pdf, pages=3, area=(20,19,823,575), lattice=True, output_format="dataframe", encoding="latin-1")
fourth = tabula.read_pdf(pdf, pages=4, area=(20,19,823,575), lattice=True, output_format="dataframe", encoding="latin-1")
fifth = tabula.read_pdf(pdf, pages=5, area=(20,19,823,575), lattice=True, output_format="dataframe", encoding="latin-1")
sixth = tabula.read_pdf(pdf, pages=6, area=(20,19,823,575), lattice=True, output_format="dataframe", encoding="latin-1")
seventh = tabula.read_pdf(pdf, pages=7, area=(20,19,275,576), lattice=True, output_format="dataframe", encoding="latin-1")
Header = tabula.read_pdf(pdf, pages=1, area=(20,20,112,576), lattice=True, output_format="dataframe", encoding="latin-1")

Error importing jpype dependencies. Fallback to subprocess.
No module named 'jpype'

In [4]:
daf1 = first[0]
daf2 = second[0]
daf3 = third[0]
daf4 = fourth[0]
daf5 = fifth[0]
daf6 = sixth[0]
daf7 = seventh[0]
dafHeader = Header[0]

In [5]:
daf1

,Unnamed: 0,FECHA DE LA JUNTA QUE APROBÓ LOS ESTADOS FINANCIEROS (DD/MM/AAA),null,Unnamed: 3
0,NaN,ESTADO DE SITUACIÓN FINANCIERA,NaN,NaN
1,NaN,CUENTA,CÓDIGO,VALOR (En USD$)
2,NaN,ACTIVO,1,100.00
3,NaN,ACTIVO CORRIENTE,101,100.00
4,NaN,EFECTIVO Y EQUIVALENTES DE EFECTIVO,10101,100.00
5,NaN,CAJA,1010101,0.00
6,NaN,INSTITUCIONES FINANCIERAS PÚBLICAS,1010102,0.00
7,NaN,INSTITUCIONES FINANCIERAS PRIVADAS,1010103,100.00
8,NaN,ACTIVOS FINANCIEROS,10102,0.00
9,NaN,ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMB...,1010201,0.00
10,NaN,RENTA VARIABLE,101020101,0.00
11,NaN,ACCIONES Y PARTICIPACIONES,10102010101,0.00
12,NaN,CUOTAS DE FONDOS COLECTIVOS,10102010102,0.00
13,NaN,VALORES DE TITULARIZACIÓN DE PARTICIPACIÓN,10102010103,0.00
14,NaN,UNIDADES DE PARTICIPACIÓN,10102010104,0.00
15,NaN,INVERSIONES EN EL EXTERIOR,10102010105,0.00
16,NaN,OTROS,10102010106,0.00
17,NaN,RENTA FIJA,101020102,0.00
18,NaN,AVALES,10102010201,0.00
19,NaN,BONOS DEL ESTADO,10102010202,0.00
20,NaN,BONOS DE PRENDA,10102010203,0.00
21,NaN,CÉDULAS HIPOTECARIAS,10102010204,0.00
22,NaN,CERTIFICADOS FINANCIEROS,10102010205,0.00
23,NaN,CERTIFICADOS DE INVERSIÓN,10102010206,0.00
24,NaN,CERTIFICADOS DE TESORERÍA,10102010207,0.00
25,NaN,CERTIFICADOS DE DEPÓSITO,10102010208,0.00
26,NaN,CUPONES,10102010209,0.00
27,NaN,DEPÓSITOS A PLAZO,10102010210,0.00
28,NaN,LETRAS DE CAMBIO,10102010211,0.00
29,NaN,NOTAS DE CRÉDITO,10102010212,0.00
30,NaN,OBLIGACIONES,10102010213,0.00
31,NaN,FACTURAS COMERCIALES NEGOCIABLES,10102010214,0.00
32,NaN,OVERNIGHTS,10102010215,0.00
33,NaN,OBLIGACIONES CONVERTIBLES EN ACCIONES,10102010216,0.00
34,NaN,PAPEL COMERCIAL,10102010217,0.00
35,NaN,PAGARÉS,10102010218,0.00
36,NaN,PÓLIZAS DE ACUMULACIÓN,10102010219,0.00
37,NaN,TÍTULOS DEL BANCO CENTRAL,10102010220,0.00
38,NaN,VALORES DE TITULARIZACIÓN,10102010221,0.00
39,NaN,INVERSIONES EN EL EXTERIOR,10102010222,0.00
40,NaN,OTROS,10102010223,0.00
41,NaN,DERIVADOS,101020103,0.00
42,NaN,FORWARD,10102010301,0.00
43,NaN,FUTUROS,10102010302,0.00
44,NaN,OPCIONES,10102010303,0.00
45,NaN,OTROS,10102010304,0.00
46,NaN,ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA,1010202,0.00
47,NaN,RENTA VARIABLE,101020201,0.00
48,NaN,ACCIONES Y PARTICIPACIONES,10102020101,0.00
49,CUOTAS DE FONDOS COLECTIVOS,10102020102,0.00,NaN

In [6]:
print(daf1.index[49]) # o con -1
daf1.fillna("d", inplace=True)
daf1.rename(inplace=True, columns={"null": "CODS"})

daf1.drop(["Unnamed: 0"], axis=1, inplace=True)
daf1.iloc[daf1.index[-1]] = {"FECHA DE LA JUNTA QUE APROBÓ LOS ESTADOS FINANCIEROS (DD/MM/AAA)":"CUOTAS DE FONDOS COLECTIVOS",
                            "CODS":"10102020102", "Unnamed: 3":"0.00"}

daf1.rename(inplace=True, columns={"FECHA DE LA JUNTA QUE APROBÓ LOS ESTADOS FINANCIEROS (DD/MM/AAA)":"CUENTA", 
                                "CODS":"CODS1",  "Unnamed: 3":"VALOR EN USD"})
daf1.drop("CODS1", axis=1, inplace=True)
daf1.drop([0,1], inplace=True)
daf1.head(10)

49

                                               CUENTA VALOR EN USD
2                                              ACTIVO       100.00
3                                    ACTIVO CORRIENTE       100.00
4                 EFECTIVO Y EQUIVALENTES DE EFECTIVO       100.00
5                                                CAJA         0.00
6                  INSTITUCIONES FINANCIERAS PÚBLICAS         0.00
7                  INSTITUCIONES FINANCIERAS PRIVADAS       100.00
8                                 ACTIVOS FINANCIEROS         0.00
9   ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMB...         0.00
10                                     RENTA VARIABLE         0.00
11                         ACCIONES Y PARTICIPACIONES         0.00

In [7]:
daf1

                                               CUENTA VALOR EN USD
2                                              ACTIVO       100.00
3                                    ACTIVO CORRIENTE       100.00
4                 EFECTIVO Y EQUIVALENTES DE EFECTIVO       100.00
5                                                CAJA         0.00
6                  INSTITUCIONES FINANCIERAS PÚBLICAS         0.00
7                  INSTITUCIONES FINANCIERAS PRIVADAS       100.00
8                                 ACTIVOS FINANCIEROS         0.00
9   ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMB...         0.00
10                                     RENTA VARIABLE         0.00
11                         ACCIONES Y PARTICIPACIONES         0.00
12                        CUOTAS DE FONDOS COLECTIVOS         0.00
13        VALORES DE  TITULARIZACIÓN DE PARTICIPACIÓN         0.00
14                          UNIDADES DE PARTICIPACIÓN         0.00
15                         INVERSIONES EN EL EXTERIOR         0.00
16                                              OTROS         0.00
17                                         RENTA FIJA         0.00
18                                             AVALES         0.00
19                                   BONOS DEL ESTADO         0.00
20                                    BONOS DE PRENDA         0.00
21                               CÉDULAS HIPOTECARIAS         0.00
22                           CERTIFICADOS FINANCIEROS         0.00
23                          CERTIFICADOS DE INVERSIÓN         0.00
24                          CERTIFICADOS DE TESORERÍA         0.00
25                           CERTIFICADOS DE DEPÓSITO         0.00
26                                            CUPONES         0.00
27                                  DEPÓSITOS A PLAZO         0.00
28                                   LETRAS DE CAMBIO         0.00
29                                   NOTAS DE CRÉDITO         0.00
30                                       OBLIGACIONES         0.00
31                   FACTURAS COMERCIALES NEGOCIABLES         0.00
32                                         OVERNIGHTS         0.00
33              OBLIGACIONES CONVERTIBLES EN ACCIONES         0.00
34                                    PAPEL COMERCIAL         0.00
35                                            PAGARÉS         0.00
36                             PÓLIZAS DE ACUMULACIÓN         0.00
37                          TÍTULOS DEL BANCO CENTRAL         0.00
38                          VALORES DE TITULARIZACIÓN         0.00
39                         INVERSIONES EN EL EXTERIOR         0.00
40                                              OTROS         0.00
41                                          DERIVADOS         0.00
42                                            FORWARD         0.00
43                                            FUTUROS         0.00
44                                           OPCIONES         0.00
45                                              OTROS         0.00
46      ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA         0.00
47                                     RENTA VARIABLE         0.00
48                         ACCIONES Y PARTICIPACIONES         0.00
49                        CUOTAS DE FONDOS COLECTIVOS         0.00

In [8]:
daf2

,Unnamed: 0,ESTADO DE SITUACIÓN FINANCIERA,Unnamed: 2,Unnamed: 3
0,NaN,CUENTA,CÓDIGO,VALOR (En USD$)
1,NaN,UNIDADES DE PARTICIPACIÓN,10102020103,0.00
2,NaN,VALORES DE TITULARIZACIÓN DE PARTICIPACIÓN,10102020104,0.00
3,NaN,INVERSIONES EN EL EXTERIOR,10102020105,0.00
4,NaN,OTROS,10102020106,0.00
5,NaN,RENTA FIJA,101020202,0.00
6,NaN,AVALES,10102020201,0.00
7,NaN,BONOS DEL ESTADO,10102020202,0.00
8,NaN,BONOS DE PRENDA,10102020203,0.00
9,NaN,CÉDULAS HIPOTECARIAS,10102020204,0.00
10,NaN,CERTIFICADOS FINANCIEROS,10102020205,0.00
11,NaN,CERTIFICADOS DE INVERSIÓN,10102020206,0.00
12,NaN,CERTIFICADOS DE TESORERÍA,10102020207,0.00
13,NaN,CERTIFICADOS DE DEPÓSITO,10102020208,0.00
14,NaN,CUPONES,10102020209,0.00
15,NaN,DEPÓSITOS A PLAZO,10102020210,0.00
16,NaN,LETRAS DE CAMBIO,10102020211,0.00
17,NaN,NOTAS DE CRÉDITO,10102020212,0.00
18,NaN,OBLIGACIONES,10102020213,0.00
19,NaN,FACTURAS COMERCIALES NEGOCIABLES,10102020214,0.00
20,NaN,OVERNIGHTS,10102020215,0.00
21,NaN,OBLIGACIONES CONVERTIBLES EN ACCIONES,10102020216,0.00
22,NaN,PAPEL COMERCIAL,10102020217,0.00
23,NaN,PAGARÉS,10102020218,0.00
24,NaN,PÓLIZAS DE ACUMULACIÓN,10102020219,0.00
25,NaN,TÍTULOS DEL BANCO CENTRAL,10102020220,0.00
26,NaN,VALORES DE TITULARIZACIÓN,10102020221,0.00
27,NaN,INVERSIONES EN EL EXTERIOR,10102020222,0.00
28,NaN,OTROS,10102020223,0.00
29,NaN,ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIM...,1010203,0.00
30,NaN,RENTA VARIABLE,101020301,0.00
31,NaN,ACCIONES Y PARTICIPACIONES,10102030101,0.00
32,NaN,CUOTAS DE FONDOS COLECTIVOS,10102030102,0.00
33,NaN,UNIDADES DE PARTICIPACIÓN,10102030103,0.00
34,NaN,VALORES DE TITULARIZACIÓN DE PARTICIPACIÓN,10102030104,0.00
35,NaN,INVERSIONES EN EL EXTERIOR,10102030105,0.00
36,NaN,OTROS,10102030106,0.00
37,NaN,RENTA FIJA,101020302,0.00
38,NaN,AVALES,10102030201,0.00
39,NaN,BONOS DEL ESTADO,10102030202,0.00
40,NaN,BONOS DE PRENDA,10102030203,0.00
41,NaN,CÉDULAS HIPOTECARIAS,10102030204,0.00
42,NaN,CERTIFICADOS FINANCIEROS,10102030205,0.00
43,NaN,CERTIFICADOS DE INVERSIÓN,10102030206,0.00
44,NaN,CERTIFICADOS DE TESORERÍA,10102030207,0.00
45,NaN,CERTIFICADOS DE DEPÓSITO,10102030208,0.00
46,NaN,CUPONES,10102030209,0.00
47,NaN,DEPÓSITOS A PLAZO,10102030210,0.00
48,NaN,LETRAS DE CAMBIO,10102030211,0.00
49,NaN,NOTAS DE CRÉDITO,10102030212,0.00
50,NaN,OBLIGACIONES,10102030213,0.00
51,NaN,FACTURAS COMERCIALES NEGOCIABLES,10102030214,0.00
52,NaN,OVERNIGHTS,10102030215,0.00
53,NaN,OBLIGACIONES CONVERTIBLES EN ACCIONES,10102030216,0.00
54,NaN,PAPEL COMERCIAL,10102030217,0.00
55,NaN,PAGARÉS,10102030218,0.00

In [9]:
daf2.drop(["Unnamed: 0","Unnamed: 2"], axis=1, inplace=True)
daf2.drop([0], inplace=True)
daf2.rename(inplace=True, columns={"ESTADO DE SITUACIÓN FINANCIERA":"CUENTA",  "Unnamed: 3":"VALOR EN USD"})
daf2.head(10)

                                         CUENTA VALOR EN USD
1                     UNIDADES DE PARTICIPACIÓN         0.00
2   VALORES DE  TITULARIZACIÓN DE PARTICIPACIÓN         0.00
3                    INVERSIONES EN EL EXTERIOR         0.00
4                                         OTROS         0.00
5                                    RENTA FIJA         0.00
6                                        AVALES         0.00
7                              BONOS DEL ESTADO         0.00
8                               BONOS DE PRENDA         0.00
9                          CÉDULAS HIPOTECARIAS         0.00
10                     CERTIFICADOS FINANCIEROS         0.00

In [10]:
daf3

,Unnamed: 0,ESTADO DE SITUACIÓN FINANCIERA,Unnamed: 2,Unnamed: 3
0,NaN,CUENTA,CÓDIGO,VALOR (En USD$)
1,NaN,PÓLIZAS DE ACUMULACIÓN,10102030219,0.00
2,NaN,TÍTULOS DEL BANCO CENTRAL,10102030220,0.00
3,NaN,VALORES DE TITULARIZACIÓN,10102030221,0.00
4,NaN,INVERSIONES EN EL EXTERIOR,10102030222,0.00
5,NaN,OTROS,10102030223,0.00
6,NaN,PROVISIÓN POR DETERIORO DE ACTIVOS FINANCIEROS,1010204,0.00
7,NaN,ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMB...,101020401,0.00
8,NaN,ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA,101020402,0.00
9,NaN,ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIM...,101020403,0.00
10,NaN,DOCUMENTOS Y CUENTAS POR COBRAR NO RELACIONADOS,1010205,0.00
11,NaN,DE ACTIVIDADES ORDINARIAS QUE GENEREN INTERESES,101020501,0.00
12,NaN,CUENTAS Y DOCUMENTOS A COBRAR A CLIENTES,10102050101,0.00
13,NaN,CUENTAS Y DOCUMENTOS A COBRAR A TERCEROS,10102050102,0.00
14,NaN,DE ACTIVIDADES ORDINARIAS QUE NO GENEREN INTER...,101020502,0.00
15,NaN,CUENTAS Y DOCUMENTOS A COBRAR A CLIENTES,10102050201,0.00
16,NaN,CUENTAS Y DOCUMENTOS A COBRAR A TERCEROS,10102050202,0.00
17,NaN,CUENTAS POR COBRAR AL ORIGINADOR,10102050203,0.00
18,NaN,COMISIONES POR OPERACIONES BURSÁTILES,10102050204,0.00
19,NaN,POR SERVICIOS BURSÁTILES - PUESTOS INACTIVOS,10102050205,0.00
20,NaN,OPERACIONES EXTRABURSÁTILES,10102050206,0.00
21,NaN,CONTRATO DE UNDERWRITING,10102050207,0.00
22,NaN,POR ADMINISTRACIÓN Y MANEJO DE PORTAFOLIOS DE...,10102050208,0.00
23,NaN,POR ADMINISTRACIÓN Y MANEJO DE FONDOS ADMINIST...,10102050209,0.00
24,NaN,POR ADMINISTRACIÓN Y MANEJO DE NEGOCIOS FIDUCI...,10102050210,0.00
25,NaN,POR CUSTODIA Y CONSERVACIÓN DE VALORES MATERIA...,10102050211,0.00
26,NaN,POR CUSTODIA Y CONSERVACIÓN DE VALORES DESMATE...,10102050212,0.00
27,NaN,POR MANEJO DE LIBRO DE ACCIONES Y ACCIONISTAS,10102050213,0.00
28,NaN,POR ASESORÍA,10102050214,0.00
29,NaN,RENDIMIENTOS POR COBRAR DIVIDENDOS,10102050215,0.00
30,NaN,RENDIMIENTO POR COBRAR INTERESES,10102050216,0.00
31,NaN,DEUDORES POR INTERMEDIACIÓN DE VALORES,10102050217,0.00
32,NaN,ANTICIPO A COMITENTES,10102050218,0.00
33,NaN,ANTICIPO A CONSTRUCTOR POR AVANCE DE OBRA,10102050219,0.00
34,NaN,DERECHOS POR COMPROMISO DE RECOMPRA,10102050220,0.00
35,NaN,OTRAS CUENTAS POR COBRAR NO RELACIONADAS,10102050221,0.00
36,NaN,DOCUMENTOS Y CUENTAS POR COBRAR RELACIONADOS,1010206,0.00
37,NaN,POR COBRAR A ACCIONISTAS,101020601,0.00
38,NaN,POR COBRAR A COMPAÑÍAS RELACIONADAS,101020602,0.00
39,NaN,POR COBRAR A CLIENTES,101020603,0.00
40,NaN,OTRAS CUENTAS POR COBRAR RELACIONADAS,101020604,0.00
41,NaN,PROVISIÓN POR CUENTAS INCOBRABLES Y DETERIORO,1010207,0.00
42,NaN,INVENTARIOS,10103,0.00
43,NaN,INVENTARIOS DE MATERIA PRIMA,1010301,0.00
44,NaN,INVENTARIOS DE PRODUCTOS EN PROCESO,1010302,0.00
45,NaN,INVENTARIOS DE SUMINISTROS O MATERIALES A SER ...,1010303,0.00
46,NaN,INVENTARIOS DE SUMINISTROS O MATERIALES A SER ...,1010304,0.00
47,NaN,INVENTARIOS DE PROD. TERM. Y MERCAD. EN ALMACÉ...,1010305,0.00
48,NaN,INVENTARIOS DE PROD. TERM. Y MERCAD. EN ALMACÉ...,1010306,0.00
49,NaN,MERCADERÍAS EN TRÁNSITO,1010307,0.00
50,NaN,OBRAS EN CONSTRUCCION,1010308,0.00
51,NaN,OBRAS TERMINADAS,1010309,0.00
52,NaN,MATERIALES O BIENES PARA LA CONSTRUCCION,1010310,0.00
53,NaN,"INVENTARIOS REPUESTOS, HERRAMIENTAS Y ACCESORIOS",1010311,0.00
54,NaN,OTROS INVENTARIOS,1010312,0.00
55,NaN,(-) PROVISIÓN POR VALOR NETO DE REALIZACIÓN Y ...,1010313,0.00

In [11]:
daf3.drop(["Unnamed: 0", "Unnamed: 2"], axis=1, inplace=True)
daf3.drop([0], inplace=True)
daf3.rename(inplace=True, columns={"ESTADO DE SITUACIÓN FINANCIERA":"CUENTA",  "Unnamed: 3":"VALOR EN USD"})
daf3.head(10)

                                               CUENTA VALOR EN USD
1                              PÓLIZAS DE ACUMULACIÓN         0.00
2                           TÍTULOS DEL BANCO CENTRAL         0.00
3                           VALORES DE TITULARIZACIÓN         0.00
4                          INVERSIONES EN EL EXTERIOR         0.00
5                                               OTROS         0.00
6      PROVISIÓN POR DETERIORO DE ACTIVOS FINANCIEROS         0.00
7   ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMB...         0.00
8       ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA         0.00
9   ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIM...         0.00
10    DOCUMENTOS Y CUENTAS POR COBRAR NO RELACIONADOS         0.00

In [12]:
daf4

,Unnamed: 0,ESTADO DE SITUACIÓN FINANCIERA,Unnamed: 2,Unnamed: 3
0,NaN,CUENTA,CÓDIGO,VALOR (En USD$)
1,NaN,SERVICIOS Y OTROS PAGOS ANTICIPADOS,10104,0.00
2,NaN,SEGUROS PAGADOS POR ANTICIPADO,1010401,0.00
3,NaN,ARRIENDOS PAGADOS POR ANTICIPADO,1010402,0.00
4,NaN,ANTICIPOS A PROVEEDORES,1010403,0.00
5,NaN,OTROS ANTICIPOS ENTREGADOS,1010404,0.00
6,NaN,ACTIVOS POR IMPUESTOS CORRIENTES,10105,0.00
7,NaN,CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA (IVA),1010501,0.00
8,NaN,CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA ( I. R.),1010502,0.00
9,NaN,ANTICIPO DE IMPUESTO A LA RENTA,1010503,0.00
10,NaN,ACTIVOS CORRIENTES MANTENIDOS PARA LA VENTA Y ...,10106,0.00
11,NaN,CONSTRUCCIONES EN PROCESO (NIC 11 Y SECC.23 PY...,10107,0.00
12,NaN,OTROS ACTIVOS CORRIENTES,10108,0.00
13,NaN,ACTIVOS NO CORRIENTES,102,0.00
14,NaN,"PROPIEDAD, PLANTA Y EQUIPO",10201,0.00
15,NaN,TERRENOS,1020101,0.00
16,NaN,EDIFICIOS,1020102,0.00
17,NaN,CONSTRUCCIONES EN CURSO,1020103,0.00
18,NaN,INSTALACIONES,1020104,0.00
19,NaN,MUEBLES Y ENSERES,1020105,0.00
20,NaN,MAQUINARIA Y EQUIPO,1020106,0.00
21,NaN,"NAVES, AEREONAVES, BARCAZAS Y SIMILARES",1020107,0.00
22,NaN,EQUIPO DE COMPUTACIÓN,1020108,0.00
23,NaN,"VEHÍCULOS, EQUIPOS DE TRASPORTE Y EQUIPO CAMIN...",1020109,0.00
24,NaN,"OTROS PROPIEDADES, PLANTA Y EQUIPO",1020110,0.00
25,NaN,REPUESTOS Y HERRAMIENTAS,1020111,0.00
26,NaN,"(-) DEPRECIACIÓN ACUMULADA PROPIEDADES, PLANTA...",1020112,0.00
27,NaN,"(-) DETERIORO ACUMULADO DE PROPIEDADES, PLANT...",1020113,0.00
28,NaN,ACTIVOS DE EXPLORACION Y EXPLOTACION,1020114,0.00
29,NaN,ACTIVOS DE EXPLORACION Y EXPLOTACION,102011401,0.00
30,NaN,(-) AMORTIZACION ACUMULADA DE ACTIVOS DE EXPLO...,102011402,0.00
31,NaN,(-) DETERIORO ACUMULADO DE ACTIVOS DE EXPLORA...,102011403,0.00
32,NaN,PROPIEDADES DE INVERSIÓN,10202,0.00
33,NaN,TERRENOS,1020201,0.00
34,NaN,EDIFICIOS,1020202,0.00
35,NaN,(-) DEPRECIACION ACUMULADA DE PROPIEDADES DE I...,1020203,0.00
36,NaN,(-) DETERIORO ACUMULADO DE PROPIEDADES DE INVE...,1020204,0.00
37,NaN,ACTIVOS BIOLOGICOS,10203,0.00
38,NaN,ANIMALES VIVOS EN CRECIMIENTO,1020301,0.00
39,NaN,ANIMALES VIVOS EN PRODUCCION,1020302,0.00
40,NaN,PLANTAS EN CRECIMIENTO,1020303,0.00
41,NaN,PLANTAS EN PRODUCCION,1020304,0.00
42,NaN,(-) DEPRECIACION ACUMULADA DE ACTIVOS BIOLÓGICOS,1020305,0.00
43,NaN,(-) DETERIORO ACUMULADO DE ACTIVOS BIOLOGÍCOS,1020306,0.00
44,NaN,ACTIVO INTANGIBLE,10204,0.00
45,NaN,PLUSVALÍAS,1020401,0.00
46,NaN,"MARCAS, PATENTES, DERECHOS DE LLAVE , CUOTAS P...",1020402,0.00
47,NaN,CONCESIONES Y LICENCIAS,1020403,0.00
48,NaN,ACTIVOS DE EXPLORACION Y EXPLOTACION,1020404,0.00
49,NaN,(-) AMORTIZACIÓN ACUMULADA DE ACTIVOS INTANGIBLE,1020405,0.00
50,NaN,(-) DETERIORO ACUMULADO DE ACTIVO INTANGIBLE,1020406,0.00
51,NaN,OTROS INTANGIBLES,1020407,0.00
52,NaN,ACTIVOS POR IMPUESTOS DIFERIDOS,10205,0.00
53,NaN,ACTIVOS FINANCIEROS NO CORRIENTES,10206,0.00
54,NaN,ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIM...,1020601,0.00
55,NaN,(-) PROVISION POR DETERIORO DE ACTIVOS FINANCI...,1020602,0.00

In [13]:
daf4.drop(["Unnamed: 0", "Unnamed: 2"], axis=1, inplace=True)
daf4.drop([0], inplace=True)
daf4.rename(inplace=True, columns={"ESTADO DE SITUACIÓN FINANCIERA":"CUENTA",  "Unnamed: 3":"VALOR EN USD"})
daf4.head(10)

                                               CUENTA VALOR EN USD
1                 SERVICIOS Y OTROS PAGOS ANTICIPADOS         0.00
2                      SEGUROS PAGADOS POR ANTICIPADO         0.00
3                    ARRIENDOS PAGADOS POR ANTICIPADO         0.00
4                             ANTICIPOS A PROVEEDORES         0.00
5                          OTROS ANTICIPOS ENTREGADOS         0.00
6                    ACTIVOS POR IMPUESTOS CORRIENTES         0.00
7      CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA (IVA)         0.00
8   CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA ( I. R.)         0.00
9                     ANTICIPO DE IMPUESTO A LA RENTA         0.00
10  ACTIVOS CORRIENTES MANTENIDOS PARA LA VENTA Y ...         0.00

In [14]:
daf5

,Unnamed: 0,ESTADO DE SITUACIÓN FINANCIERA,Unnamed: 2,Unnamed: 3
0,NaN,CUENTA,CÓDIGO,VALOR (En USD$)
1,NaN,DOCUMENTOS Y CUENTAS POR COBRAR,1020603,0.00
2,NaN,(-) PROVISIÓN CUENTAS INCOBRABLES DE ACTIVOS F...,1020604,0.00
3,NaN,ACTIVOS ADQUIRIDOS EN ARRENDAMIENTO FINANCIERO,10207,0.00
4,NaN,OTROS ACTIVOS NO CORRIENTES,10208,0.00
5,NaN,DERECHOS FIDUCIARIOS,1020801,0.00
6,NaN,DEPÓSITOS EN GARANTÍA,1020802,0.00
7,NaN,DEPÓSITOS EN GARANTÍA POR OPERACIONES BURSÁTILES,1020803,0.00
8,NaN,CUOTA PATRIMONIAL BOLSA DE VALORES,1020804,0.00
9,NaN,ACCIONES DEPÒSITO CENTRALIZADO DE VALORES,1020805,0.00
10,NaN,INVERSIONES SUBSIDIARIAS,1020806,0.00
11,NaN,INVERSIONES ASOCIADAS,1020807,0.00
12,NaN,INVERSIONES NEGOCIOS CONJUNTOS,1020808,0.00
13,NaN,OTRAS INVERSIONES,1020809,0.00
14,NaN,(-) PROVISIÓN VALUACIÓN DE INVERSIONES,1020810,0.00
15,NaN,OTROS ACTIVOS NO CORRIENTES,1020811,0.00
16,NaN,PASIVO,2,0.00
17,NaN,PASIVO CORRIENTE,201,0.00
18,NaN,PASIVOS FINANCIEROS A VALOR RAZONABLE CON CAMB...,20101,0.00
19,NaN,PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCI...,20102,0.00
20,NaN,CUENTAS Y DOCUMENTOS POR PAGAR,20103,0.00
21,NaN,LOCALES,2010301,0.00
22,NaN,PRÉSTAMOS,201030101,0.00
23,NaN,ANTICIPOS RECIBIDOS,201030102,0.00
24,NaN,OTRAS,201030103,0.00
25,NaN,DEL EXTERIOR,2010302,0.00
26,NaN,OBLIGACIONES CON INSTITUCIONES FINANCIERAS,20104,0.00
27,NaN,LOCALES,2010401,0.00
28,NaN,DEL EXTERIOR,2010402,0.00
29,NaN,PROVISIONES,20105,0.00
30,NaN,LOCALES,2010501,0.00
31,NaN,DEL EXTERIOR,2010502,0.00
32,NaN,PORCIÓN CORRIENTE DE VALORES EMITIDOS,20106,0.00
33,NaN,OBLIGACIONES,2010601,0.00
34,NaN,PAPEL COMERCIAL,2010602,0.00
35,NaN,VALORES DE TITULARIZACIÓN,2010603,0.00
36,NaN,OTROS,2010604,0.00
37,NaN,INTERESES POR PAGAR,2010605,0.00
38,NaN,OTRAS OBLIGACIONES CORRIENTES,20107,0.00
39,NaN,CON LA ADMINISTRACIÓN TRIBUTARIA,2010701,0.00
40,NaN,IMPUESTO A LA RENTA POR PAGAR DEL EJERCICIO,2010702,0.00
41,NaN,CON EL IESS,2010703,0.00
42,NaN,POR BENEFICIOS DE LEY A EMPLEADOS,2010704,0.00
43,NaN,PARTICIPACIÓN TRABAJADORES POR PAGAR DEL EJERC...,2010705,0.00
44,NaN,DIVIDENDOS POR PAGAR,2010706,0.00
45,NaN,OTROS,2010707,0.00
46,NaN,CUENTAS POR PAGAR DIVERSAS/ RELACIONADAS,20108,0.00
47,NaN,OTROS PASIVOS FINANCIEROS,20109,0.00
48,NaN,ANTICIPOS DE CLIENTES,20110,0.00
49,NaN,PASIVOS DIRECTAMENTE ASOCIADOS CON LOS ACTIVOS...,20111,0.00
50,NaN,PORCION CORRIENTE DE PROVISIONES POR BENEFICIO...,20112,0.00
51,NaN,JUBILACION PATRONAL,2011201,0.00
52,NaN,OTROS BENEFICIOS PARA LOS EMPLEADOS,2011202,0.00
53,NaN,OTROS PASIVOS CORRIENTES,20113,0.00
54,NaN,COMISIONES POR PAGAR,2011301,0.00
55,NaN,POR OPERACIONES BURSÁTILES,2011302,0.00

In [15]:
daf5.drop(["Unnamed: 0", "Unnamed: 2"], axis=1, inplace=True)
daf5.drop([0], inplace=True)
daf5.rename(inplace=True, columns={"ESTADO DE SITUACIÓN FINANCIERA":"CUENTA",  "Unnamed: 3":"VALOR EN USD"})
daf5.head(10)

                                               CUENTA VALOR EN USD
1                     DOCUMENTOS Y CUENTAS POR COBRAR         0.00
2   (-) PROVISIÓN CUENTAS INCOBRABLES DE ACTIVOS F...         0.00
3      ACTIVOS ADQUIRIDOS EN ARRENDAMIENTO FINANCIERO         0.00
4                         OTROS ACTIVOS NO CORRIENTES         0.00
5                                DERECHOS FIDUCIARIOS         0.00
6                               DEPÓSITOS EN GARANTÍA         0.00
7    DEPÓSITOS EN GARANTÍA POR OPERACIONES BURSÁTILES         0.00
8                  CUOTA PATRIMONIAL BOLSA DE VALORES         0.00
9           ACCIONES DEPÒSITO CENTRALIZADO DE VALORES         0.00
10                           INVERSIONES SUBSIDIARIAS         0.00

In [16]:
daf6

,Unnamed: 0,ESTADO DE SITUACIÓN FINANCIERA,Unnamed: 2,Unnamed: 3
0,NaN,CUENTA,CÓDIGO,VALOR (En USD$)
1,NaN,POR CUSTODIA,2011303,0.00
2,NaN,POR ADMINISTRACIÓN,2011304,0.00
3,NaN,OTRAS COMISIONES,2011305,0.00
4,NaN,SANCIONES Y MULTAS,2011306,0.00
5,NaN,INDEMNIZACIONES,2011307,0.00
6,NaN,OBLIGACIONES JUDICIALES,2011308,0.00
7,NaN,ACREEDORES POR INTERMEDIACIÓN,2011309,0.00
8,NaN,OBLIGACIÓN POR COMPROMISO DE RECOMPRA,2011310,0.00
9,NaN,POR CONTRATOS DE UNDERWRITING,2011311,0.00
10,NaN,OTROS,2011312,0.00
11,NaN,PASIVO NO CORRIENTE,202,0.00
12,NaN,PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIERO,20201,0.00
13,NaN,CUENTAS Y DOCUMENTOS POR PAGAR,20202,0.00
14,NaN,LOCALES,2020201,0.00
15,NaN,PRÉSTAMOS,202020101,0.00
16,NaN,ANTICIPOS RECIBIDOS,202020102,0.00
17,NaN,OTRAS,202020103,0.00
18,NaN,DEL EXTERIOR,2020202,0.00
19,NaN,OBLIGACIONES CON INSTITUCIONES FINANCIERAS,20203,0.00
20,NaN,LOCALES,2020301,0.00
21,NaN,DEL EXTERIOR,2020302,0.00
22,NaN,CUENTAS POR PAGAR DIVERSAS/RELACIONADAS,20204,0.00
23,NaN,LOCALES,2020401,0.00
24,NaN,DEL EXTERIOR,2020402,0.00
25,NaN,PORCIÓN NO CORRIENTE DE VALORES EMITIDOS,20205,0.00
26,NaN,OBLIGACIONES,2020501,0.00
27,NaN,PAPEL COMERCIAL,2020502,0.00
28,NaN,VALORES DE TITULARIZACIÓN,2020503,0.00
29,NaN,OTROS,2020504,0.00
30,NaN,INTERESES POR PAGAR,2020505,0.00
31,NaN,ANTICIPOS DE CLIENTES,20206,0.00
32,NaN,PROVISIONES POR BENEFICIOS A EMPLEADOS,20207,0.00
33,NaN,JUBILACION PATRONAL,2020701,0.00
34,NaN,OTROS BENEFICIOS NO CORRIENTES PARA LOS EMPLEADOS,2020702,0.00
35,NaN,OTRAS PROVISIONES,20208,0.00
36,NaN,PASIVO DIFERIDO,20209,0.00
37,NaN,INGRESOS DIFERIDOS,2020901,0.00
38,NaN,PASIVOS POR IMPUESTOS DIFERIDOS,2020902,0.00
39,NaN,OTROS PASIVOS NO CORRIENTES,20210,0.00
40,NaN,PATRIMONIO NETO,3,100.00
41,NaN,PATRIMONIO NETO ATRIBUIBLE A LOS PROPIETARIOS ...,30,NaN
42,NaN,CAPITAL,301,100.00
43,NaN,CAPITAL SUSCRITO O ASIGNADO,30101,100.00
44,NaN,"(-) CAPITAL SUSCRITO NO PAGADO, ACCIONES EN TE...",30102,0.00
45,NaN,FONDO PATRIMONIAL,30103,0.00
46,NaN,PATRIMONIO DE LOS NEGOCIOS FIDUCIARIOS,30104,0.00
47,NaN,PATRIMONIO DE LOS FONDOS DE INVERSIÓN,30105,0.00
48,NaN,PATRIMONIO DEL FONDO ADMINISTRADO,3010501,0.00
49,NaN,PATRIMONIO DEL FONDO COLECTIVO,3010502,0.00
50,NaN,APORTES DE SOCIOS O ACCIONISTAS PARA FUTURA CA...,302,0.00
51,NaN,PRIMA POR EMISIÓN PRIMARIA DE ACCIONES,303,0.00
52,NaN,RESERVAS,304,0.00
53,NaN,RESERVA LEGAL,30401,0.00
54,NaN,RESERVAS FACULTATIVA Y ESTATUTARIA,30402,0.00
55,NaN,OTROS RESULTADOS INTEGRALES,305,0.00

In [17]:
daf6.drop(["Unnamed: 0", "Unnamed: 2"], axis=1, inplace=True)
daf6.drop([0], inplace=True)
daf6.rename(inplace=True, columns={"ESTADO DE SITUACIÓN FINANCIERA":"CUENTA",  "Unnamed: 3":"VALOR EN USD"})
daf6.head(10)

                                   CUENTA VALOR EN USD
1                            POR CUSTODIA         0.00
2                      POR ADMINISTRACIÓN         0.00
3                        OTRAS COMISIONES         0.00
4                      SANCIONES Y MULTAS         0.00
5                         INDEMNIZACIONES         0.00
6                 OBLIGACIONES JUDICIALES         0.00
7           ACREEDORES POR INTERMEDIACIÓN         0.00
8   OBLIGACIÓN POR COMPROMISO DE RECOMPRA         0.00
9           POR CONTRATOS DE UNDERWRITING         0.00
10                                  OTROS         0.00

In [18]:
daf7

,Unnamed: 0,ESTADO DE SITUACIÓN FINANCIERA,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,CUENTA,CÓDIGO,VALOR (En USD$),NaN
1,NaN,SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES P...,30501,0.00,NaN
2,NaN,"SUPERAVIT POR REVALUACIÓN DE PROPIEDADES, PLAN...",30502,0.00,NaN
3,NaN,SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES,30503,0.00,NaN
4,NaN,OTROS SUPERAVIT POR REVALUACION,30504,0.00,NaN
5,NaN,RESULTADOS ACUMULADOS,306,0.00,NaN
6,NaN,GANANCIAS ACUMULADAS,30601,0.00,NaN
7,NaN,(-) PÉRDIDAS ACUMULADAS,30602,0.00,NaN
8,NaN,RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPC...,30603,0.00,NaN
9,NaN,RESERVA DE CAPITAL,30604,0.00,NaN
10,NaN,RESERVA POR DONACIONES,30605,0.00,NaN
11,NaN,RESERVA POR VALUACIÓN,30606,0.00,NaN
12,NaN,SUPERÁVIT POR REVALUACIÓN DE INVERSIONES,30607,0.00,NaN
13,NaN,RESULTADOS DEL EJERCICIO,307,0.00,NaN
14,NaN,GANANCIA NETA DEL PERIODO,30701,0.00,NaN
15,NaN,(-) PÉRDIDA NETA DEL PERIODO,30702,0.00,NaN
16,PARTICIPACIÓN CONTROLADORA,31,NaN,NaN,NaN

In [21]:
print(daf7.iloc[-1])

Unnamed: 0                        PARTICIPACIÓN CONTROLADORA
ESTADO DE SITUACIÓN FINANCIERA                            31
Unnamed: 2                                               NaN
Unnamed: 3                                               NaN
Unnamed: 4                                               NaN
Name: 16, dtype: object

In [25]:
daf7.drop(["Unnamed: 0","Unnamed: 2","Unnamed: 4"], axis=1, inplace=True)
daf7.drop([0], inplace=True)
daf7.iloc[daf7.index[-1]] = {"ESTADO DE SITUACIÓN FINANCIERA":"PARTICIPACIÓN CONTROLADORA",
                            "Unnamed: 3":"0.00"}
daf7.rename(inplace=True, columns={"ESTADO DE SITUACIÓN FINANCIERA":"CUENTA",  "Unnamed: 3":"VALOR EN USD"})
daf7

                                               CUENTA VALOR EN USD
1   SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES P...         0.00
2   SUPERAVIT POR REVALUACIÓN DE PROPIEDADES, PLAN...         0.00
3    SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES         0.00
4                     OTROS SUPERAVIT POR REVALUACION         0.00
5                               RESULTADOS ACUMULADOS         0.00
6                                GANANCIAS ACUMULADAS         0.00
7                             (-) PÉRDIDAS ACUMULADAS         0.00
8   RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPC...         0.00
9                                  RESERVA DE CAPITAL         0.00
10                             RESERVA POR DONACIONES         0.00
11                              RESERVA POR VALUACIÓN         0.00
12           SUPERÁVIT POR REVALUACIÓN DE INVERSIONES         0.00
13                           RESULTADOS DEL EJERCICIO         0.00
14                          GANANCIA NETA DEL PERIODO         0.00
15                       (-) PÉRDIDA NETA DEL PERIODO         0.00
16                                                 31          NaN

In [33]:
daf7

                                               CUENTA VALOR EN USD
1   SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES P...         0.00
2   SUPERAVIT POR REVALUACIÓN DE PROPIEDADES, PLAN...         0.00
3    SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES         0.00
4                     OTROS SUPERAVIT POR REVALUACION         0.00
5                               RESULTADOS ACUMULADOS         0.00
6                                GANANCIAS ACUMULADAS         0.00
7                             (-) PÉRDIDAS ACUMULADAS         0.00
8   RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPC...         0.00
9                                  RESERVA DE CAPITAL         0.00
10                             RESERVA POR DONACIONES         0.00
11                              RESERVA POR VALUACIÓN         0.00
12           SUPERÁVIT POR REVALUACIÓN DE INVERSIONES         0.00
13                           RESULTADOS DEL EJERCICIO         0.00
14                          GANANCIA NETA DEL PERIODO         0.00
15                       (-) PÉRDIDA NETA DEL PERIODO         0.00
16                                                 31          NaN

In [35]:
daf7.drop([16], inplace=True)
#daf7.iloc[daf7.index[15]] = {"CUENTA":"PARTICIPACIÓN CONTROLADORA", "VALOR EN USD":"0.00"}
#daf7

In [36]:
daf7

                                               CUENTA VALOR EN USD
1   SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES P...         0.00
2   SUPERAVIT POR REVALUACIÓN DE PROPIEDADES, PLAN...         0.00
3    SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES         0.00
4                     OTROS SUPERAVIT POR REVALUACION         0.00
5                               RESULTADOS ACUMULADOS         0.00
6                                GANANCIAS ACUMULADAS         0.00
7                             (-) PÉRDIDAS ACUMULADAS         0.00
8   RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPC...         0.00
9                                  RESERVA DE CAPITAL         0.00
10                             RESERVA POR DONACIONES         0.00
11                              RESERVA POR VALUACIÓN         0.00
12           SUPERÁVIT POR REVALUACIÓN DE INVERSIONES         0.00
13                           RESULTADOS DEL EJERCICIO         0.00
14                          GANANCIA NETA DEL PERIODO         0.00
15                       (-) PÉRDIDA NETA DEL PERIODO         0.00

In [38]:
nueva_fila = {"CUENTA": "PARTICIPACIÓN CONTROLADORA", "VALOR EN USD": "0.00"}
daf7 = daf7._append(nueva_fila, ignore_index=True)

In [39]:
daf7

                                               CUENTA VALOR EN USD
0   SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES P...         0.00
1   SUPERAVIT POR REVALUACIÓN DE PROPIEDADES, PLAN...         0.00
2    SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES         0.00
3                     OTROS SUPERAVIT POR REVALUACION         0.00
4                               RESULTADOS ACUMULADOS         0.00
5                                GANANCIAS ACUMULADAS         0.00
6                             (-) PÉRDIDAS ACUMULADAS         0.00
7   RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPC...         0.00
8                                  RESERVA DE CAPITAL         0.00
9                              RESERVA POR DONACIONES         0.00
10                              RESERVA POR VALUACIÓN         0.00
11           SUPERÁVIT POR REVALUACIÓN DE INVERSIONES         0.00
12                           RESULTADOS DEL EJERCICIO         0.00
13                          GANANCIA NETA DEL PERIODO         0.00
14                       (-) PÉRDIDA NETA DEL PERIODO         0.00
15                         PARTICIPACIÓN CONTROLADORA         0.00

In [40]:
dafHeader

,Unnamed: 0,RAZÓN SOCIAL,J2R TECH S.A.S.,Unnamed: 3
0,DIRECCIÓN,yanahurco Y rio upano No. s/n BARRIO:,NaN,NaN
1,EXPEDIENTE,731956,NaN,NaN
2,RUC,0190493105001,NaN,NaN
3,AÑO,2020,NaN,NaN
4,FORMULARIO,SCV.NIIF.731956.2020.1,NaN,NaN
5,FECHA DE LA JUNTA QUE APROBÓ LOS ESTADOS FINAN...,NaN,NaN,NaN

In [41]:
dafHeader.drop(["J2R TECH S.A.S.","Unnamed: 3"], axis=1, inplace=True)
dafHeader.rename(inplace=True, columns={"Unnamed: 0":"RAZÓN SOCIAL", "RAZÓN SOCIAL":"J2R TECH S.A.S."})
dafHeader

,RAZÓN SOCIAL,J2R TECH S.A.S.
0,DIRECCIÓN,yanahurco Y rio upano No. s/n BARRIO:
1,EXPEDIENTE,731956
2,RUC,0190493105001
3,AÑO,2020
4,FORMULARIO,SCV.NIIF.731956.2020.1
5,FECHA DE LA JUNTA QUE APROBÓ LOS ESTADOS FINAN...,NaN

In [44]:
columns_names = ["REPRESENTANTE LEGAL","CONTADOR"]
pandas_options = {"names":columns_names}
contador = tabula.read_pdf(pdf, pages=7, area=(608,16,666,376), lattice=False, output_format="dataframe", encoding="latin-1", multiple_tables=True, pandas_options=pandas_options)
dafContador = contador[0]

In [46]:
dafContador.drop([0], inplace=True)
dafContador

            REPRESENTANTE LEGAL CONTADOR
1  SANCHEZ SALAZAR JOSE ANTONIO      NaN
2                    0705952547      NaN
3                           NaN      NaN

In [47]:

dafData = pd.concat([daf1,daf2, daf3, daf4, daf5, daf6, daf7])

In [48]:
dafData

                                      CUENTA VALOR EN USD
2                                     ACTIVO       100.00
3                           ACTIVO CORRIENTE       100.00
4        EFECTIVO Y EQUIVALENTES DE EFECTIVO       100.00
5                                       CAJA         0.00
6         INSTITUCIONES FINANCIERAS PÚBLICAS         0.00
..                                       ...          ...
11  SUPERÁVIT POR REVALUACIÓN DE INVERSIONES         0.00
12                  RESULTADOS DEL EJERCICIO         0.00
13                 GANANCIA NETA DEL PERIODO         0.00
14              (-) PÉRDIDA NETA DEL PERIODO         0.00
15                PARTICIPACIÓN CONTROLADORA         0.00

[339 rows x 2 columns]

In [50]:
texto = dafData["CUENTA"].to_list()
valores_list = dafData["VALOR EN USD"].to_list()

In [52]:
valores = np.array(valores_list).reshape(1,-1)
dfDatos = pd.DataFrame(valores, columns=texto)

In [53]:
dfDatos

,ACTIVO,ACTIVO CORRIENTE,EFECTIVO Y EQUIVALENTES DE EFECTIVO,CAJA,INSTITUCIONES FINANCIERAS PÚBLICAS,INSTITUCIONES FINANCIERAS PRIVADAS,ACTIVOS FINANCIEROS,ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADOS,RENTA VARIABLE,ACCIONES Y PARTICIPACIONES,...,(-) PÉRDIDAS ACUMULADAS,RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPCION POR PRIMERA VEZ DE LAS NIIF,RESERVA DE CAPITAL,RESERVA POR DONACIONES,RESERVA POR VALUACIÓN,SUPERÁVIT POR REVALUACIÓN DE INVERSIONES,RESULTADOS DEL EJERCICIO,GANANCIA NETA DEL PERIODO,(-) PÉRDIDA NETA DEL PERIODO,PARTICIPACIÓN CONTROLADORA
0,100.00,100.00,100.00,0.00,0.00,100.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [54]:
with pd.ExcelWriter("../Outputs/Doc1/InfoEconomica731956.xlsx", engine="xlsxwriter") as writer:
    dafHeader.to_excel(writer, sheet_name="Encabezado", index=False)
    dafContador.to_excel(writer, sheet_name="Encabezado", index=False, startrow=len(dafHeader)+2)
    dfDatos.to_excel(writer, sheet_name="Datos", index=False)