In [1]:
import pandas as pd
import numpy as np
import tabula

C:\Users\Usuario\AppData\Local\Temp\ipykernel_19164\3008533230.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
pdf = "../Inputs/Docs2LaFavorita/resultado_integral.pdf"

In [3]:
header = tabula.read_pdf(pdf, pages=1, area=(20,19,100,575), lattice=True, output_format="dataframe", encoding="latin-1")
first = tabula.read_pdf(pdf, pages=1, area=(99, 20, 815, 572), lattice=True, output_format="dataframe", encoding="latin-1")
second = tabula.read_pdf(pdf, pages=2, area=(20,20, 821,575), lattice=True, output_format="dataframe", encoding="latin-1")
third = tabula.read_pdf(pdf, pages=3, area=(20,20,821,575), lattice=True, output_format="dataframe", encoding="latin-1")
fourth = tabula.read_pdf(pdf, pages=4, area=(20,20,821,575), lattice=True, output_format="dataframe", encoding="latin-1")
fifth = tabula.read_pdf(pdf, pages=5, area=(20,19,499,575), lattice=True, output_format="dataframe", encoding="latin-1")

Error importing jpype dependencies. Fallback to subprocess.
No module named 'jpype'

In [4]:
dafHeader = header[0]
daf1 = first[0]
daf2 = second[0]
daf3 = third[0]
daf4 = fourth[0]
daf5 = fifth[0]

In [5]:
daf1

,ESTADO DE RESULTADO INTEGRAL,Unnamed: 1,Unnamed: 2
0,CUENTA,CÓDIGO,VALOR (En USD$)
1,INGRESOS DE ACTIVIDADES ORDINARIAS,401,3603082756.94
2,VENTA DE BIENES,40101,3590384805.81
3,PRESTACION DE SERVICIOS,40102,140899487.4
4,INGRESOS POR ASESORÍA,4010201,0.00
5,INGRESOS POR ESTRUCTURACIÓN DE OFERTA PÚBLICA ...,4010202,0.00
6,INGRESOS POR ESTRUCTURACIÓN DE NEGOCIOS FIDUCI...,4010203,0.00
7,OTROS,4010204,140899487.4
8,CONTRATOS DE CONSTRUCCION,40103,0.00
9,SUBVENCIONES DEL GOBIERNO,40104,0.00
10,REGALÍAS,40105,0.00
11,INTERESES,40106,3662684.3
12,INTERESES GENERADOS POR VENTAS A CREDITO,4010601,3619682.2
13,INTERESES Y RENDIMIENTOS FINANCIEROS,4010602,38001.88
14,OTROS INTERESES GENERADOS,4010603,5000.2
15,DIVIDENDOS,40107,0.00
16,GANANCIA POR MEDICION A VALOR RAZONABLE DE AC...,40108,0.00
17,"INGRESOS POR COMISIONES, PRESTACIÓN DE SERVICI...",40109,0.00
18,COMISIONES GANADAS POR INTERMEDIACIÓN DE VALORES,4010901,0.00
19,POR OPERACIONES BURSATILES,401090101,0.00
20,POR CONTRATOS DE UNDERWRITING,401090103,0.00
21,POR COMISIÓN EN OPERACIONES,401090104,0.00
22,POR INSCRIPCIONES,401090105,0.00
23,POR MANTENIMIENTO DE INSCRIPCIÓN,401090106,0.00
24,POR PRESTACIÓN DE SERVICIOS DE ADMINISTRACIÓN ...,4010902,0.00
25,PORTAFOLIO DE TERCEROS,401090201,0.00
26,FONDOS ADMINISTRADOS,401090202,0.00
27,FONDOS COLECTIVOS,401090203,0.00
28,TITULARIZACIÓN,401090204,0.00
29,FIDEICOMISOS MERCANTILES,401090205,0.00
30,ENCARGOS FIDUCIARIOS,401090206,0.00
31,POR CALIFICACION DE RIESGO,401090207,0.00
32,POR REPRESENTACION DE OBLIGACIONISTAS,401090208,0.00
33,"CUSTODIA, REGISTRO, COMPENSACIÓN Y LIQUIDACIÓN",4010903,0.00
34,CUSTODIA VALORES MATERIALIZADOS,401090301,0.00
35,CUSTODIA VALORES DESMATERIALIZADOS,401090302,0.00
36,COMPENSACIÓN Y LIQUIDACIÓN DE VALORES,401090303,0.00
37,OTROS,401090304,0.00
38,INGRESOS FINANCIEROS,40110,48318364.64
39,DIVIDENDOS,4011001,1549507.2
40,INTERESES FINANCIEROS,4011002,29005316.45
41,GANANCIA EN INVERSIONES EN ASOCIADAS / SUBSIDI...,4011003,0.00
42,VALUACION DE INSTRUMENTOS FINANCIEROS A VALOR ...,4011004,0.00
43,GANANCIA EN VENTA DE TITULOS VALORES,4011005,0.00
44,OTROS INGRESOS FINANCIEROS,4011006,17763540.96
45,(-) DESCUENTO EN VENTAS,40112,-167714864.3
46,(-) DEVOLUCIONES EN VENTAS,40113,-12467721.02
47,(-) BONIFICACIÓN EN PRODUCTO,40114,0.00
48,(-) OTRAS REBAJAS COMERCIALES,40115,0.00

In [6]:
daf2

,ESTADO DE RESULTADO INTEGRAL,Unnamed: 1,Unnamed: 2
0,CUENTA,CÓDIGO,VALOR (En USD$)
1,GANANCIA BRUTA,402,0.00
2,OTROS INGRESOS,403,0.00
3,"GANANCIA EN VENTA DE PROPIEDAD, PLANTA Y EQUIPO",40301,0.00
4,GANANCIA EN VENTA DE ACTIVOS BIOLÓGICOS,40302,0.00
5,OTROS,40303,0.00
6,COSTO DE VENTAS Y PRODUCCIÓN,501,2557102527.87
7,MATERIALES UTILIZADOS O PRODUCTOS VENDIDOS,50101,2520857356.11
8,(+) INVENTARIO INICIAL DE BIENES NO PRODUCIDOS...,5010101,0.00
9,(+) COMPRAS NETAS LOCALES DE BIENES NO PRODUCI...,5010102,1952911647.00
10,(+) IMPORTACIONES DE BIENES NO PRODUCIDOS POR ...,5010103,10296874.28
11,(-) INVENTARIO FINAL DE BIENES NO PRODUCIDOS P...,5010104,-544676187.84
12,(+) INVENTARIO INICIAL DE MATERIA PRIMA,5010105,0.00
13,(+) COMPRAS NETAS LOCALES DE MATERIA PRIMA,5010106,12972646.99
14,(+) IMPORTACIONES DE MATERIA PRIMA,5010107,0.00
15,(-) INVENTARIO FINAL DE MATERIA PRIMA,5010108,0.00
16,(+) INVENTARIO INICIAL DE PRODUCTOS EN PROCESO,5010109,0.00
17,(-) INVENTARIO FINAL DE PRODUCTOS EN PROCESO,5010110,0.00
18,(+) INVENTARIO INICIAL PRODUCTOS TERMINADOS,5010111,0.00
19,(-) INVENTARIO FINAL DE PRODUCTOS TERMINADOS,5010112,0.00
20,(+) MANO DE OBRA DIRECTA,50102,9242839.04
21,SUELDOS Y BENEFICIOS SOCIALES,5010201,8710241.10
22,GASTOS PLANES DE BENEFICIOS A EMPLEADOS,5010202,532597.94
23,(+) MANO DE OBRA INDIRECTA,50103,0.00
24,SUELDOS Y BENEFICIOS SOCIALES,5010301,0.00
25,GASTO PLANES DE BENEFICIOS A EMPLEADOS,5010302,0.00
26,(+) OTROS COSTOS INDIRECTOS DE FABRICACION,50104,27002332.72
27,"DEPRECIACIÓN PROPIEDADES, PLANTA Y EQUIPO",5010401,0.00
28,DETERIORO O PERDIDAS DE ACTIVOS BIOLOGICOS,5010402,0.00
29,"DETERIORO DE PROPIEDAD, PLANTA Y EQUIPO",5010403,0.00
30,EFECTO VALOR NETO DE REALIZACION DE INVENTARIOS,5010404,0.00
31,GASTO POR GARANTIAS EN VENTA DE PRODUCTOS O SE...,5010405,0.00
32,MANTENIMIENTO Y REPARACIONES,5010406,3270091.67
33,SUMINISTROS MATERIALES Y REPUESTOS,5010407,1474238.60
34,OTROS COSTOS DE PRODUCCIÓN,5010408,22258002.45
35,COSTOS DE CONTRATOS DE CONSTRUCCIONES,50105,0.00
36,COSTOS DE ACUERDO A PORCENTAJES O GRADOS DE TE...,5010501,0.00
37,GASTOS,502,771745691.54
38,GASTOS DE VENTA,50201,125174597.31
39,"SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES",5020101,0.00
40,APORTES A LA SEGURIDAD SOCIAL (INCLUIDO FONDO ...,5020102,0.00
41,BENEFICIOS SOCIALES E INDEMNIZACIONES,5020103,0.00
42,GASTO PLANES DE BENEFICIOS A EMPLEADOS,5020104,0.00
43,"HONORARIOS, COMISIONES Y DIETAS A PERSONAS NAT...",5020105,0.00
44,REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS,5020106,0.00
45,HONORARIOS A EXTRANJEROS POR SERVICIOS OCASION...,5020107,0.00
46,MANTENIMIENTO Y REPARACIONES,5020108,0.00
47,ARRENDAMIENTO,5020109,0.00
48,COMISIONES,5020110,0.00
49,PROMOCIÓN Y PUBLICIDAD,5020111,20556958.56
50,COMBUSTIBLES,5020112,0.00
51,LUBRICANTES,5020113,0.00
52,SEGUROS Y REASEGUROS (PRIMAS Y CESIONES),5020114,0.00
53,TRANSPORTE,5020115,0.00
54,"GASTOS DE GESTIÓN (AGASAJOS A ACCIONISTAS, TRA...",5020116,0.00
55,GASTOS DE VIAJE,5020117,0.00

In [7]:
daf3

,ESTADO DE RESULTADO INTEGRAL,Unnamed: 1,Unnamed: 2
0,CUENTA,CÓDIGO,VALOR (En USD$)
1,"AGUA, ENERGÍA, LUZ, Y TELECOMUNICACIONES",5020118,0.00
2,NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MER...,5020119,0.00
3,DEPRECIACIONES:,5020120,7593811.76
4,"PROPIEDADES, PLANTA Y EQUIPO",502012001,0.00
5,PROPIEDADES DE INVERSIÓN,502012002,0.00
6,ACTIVOS POR DERECHO DE USO,502012003,7593811.76
7,AMORTIZACIONES,5020121,88302260.85
8,INTANGIBLES,502012101,88302260.85
9,OTROS ACTIVOS,502012102,0.00
10,GASTO DETERIORO,5020122,0.00
11,"PROPIEDADES, PLANTA Y EQUIPO",502012201,0.00
12,INVENTARIOS,502012202,0.00
13,INSTRUMENTOS FINANCIEROS,502012203,0.00
14,INTANGIBLES,502012204,0.00
15,CUENTAS POR COBRAR,502012205,0.00
16,OTROS ACTIVOS,502012206,0.00
17,DERECHOS DE USO POR ACTIVOS ARRENDADOS,502012207,0.00
18,GASTOS POR CANTIDADES ANORMALES DE UTILIZACION...,5020123,0.00
19,MANO DE OBRA,502012301,0.00
20,MATERIALES,502012302,0.00
21,COSTOS DE PRODUCCION,502012303,0.00
22,GASTO POR REESTRUCTURACION,5020124,0.00
23,VALOR NETO DE REALIZACION DE INVENTARIOS,5020125,0.00
24,GASTO IMPUESTO A LA RENTA (ACTIVOS Y PASIVOS D...,5020126,0.00
25,SUMINISTROS Y MATERIALES,5020127,0.00
26,OTROS GASTOS,5020128,8721566.14
27,GASTOS ADMINISTRATIVOS,50202,577579170.87
28,"SUELDOS, SALARIOS Y DEMÁS REMUNERACIONES",5020201,234496917.60
29,APORTES A LA SEGURIDAD SOCIAL (INCLUIDO FONDO ...,5020202,23398348.52
30,BENEFICIOS SOCIALES E INDEMNIZACIONES,5020203,36671793.60
31,GASTO PLANES DE BENEFICIOS A EMPLEADOS,5020204,5276858.65
32,"HONORARIOS, COMISIONES Y DIETAS A PERSONAS NAT...",5020205,12898594.09
33,REMUNERACIONES A OTROS TRABAJADORES AUTÓNOMOS,5020206,0.00
34,HONORARIOS A EXTRANJEROS POR SERVICIOS OCASION...,5020207,0.00
35,MANTENIMIENTO Y REPARACIONES,5020208,31948884.34
36,ARRENDAMIENTO,5020209,14674919.33
37,COMISIONES,5020210,24903375.61
38,PROMOCIÓN Y PUBLICIDAD,5020211,0.00
39,COMBUSTIBLES,5020212,1240946.50
40,LUBRICANTES,5020213,0.00
41,SEGUROS Y REASEGUROS (PRIMAS Y CESIONES),5020214,3584349.65
42,TRANSPORTE,5020215,36679652.79
43,"GASTOS DE GESTIÓN (AGASAJOS A ACCIONISTAS, TRA...",5020216,439541.04
44,GASTOS DE VIAJE,5020217,3165855.98
45,"AGUA, ENERGÍA, LUZ, Y TELECOMUNICACIONES",5020218,33613417.04
46,NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MER...,5020219,0.00
47,"IMPUESTOS, CONTRIBUCIONES Y OTROS",5020220,39660850.25
48,DEPRECIACIONES,5020221,0.00
49,"PROPIEDADES, PLANTA Y EQUIPO",502022101,0.00
50,PROPIEDADES DE INVERSIÓN,502022102,0.00
51,ACTIVOS POR DERECHO DE USO,502022103,0.00
52,AMORTIZACIONES,5020222,17107674.61
53,INTANGIBLES,502022201,17107674.61
54,OTROS ACTIVOS,502022202,0.00
55,GASTO DETERIORO:,5020223,0.00

In [8]:
daf4

,ESTADO DE RESULTADO INTEGRAL,Unnamed: 1,Unnamed: 2
0,CUENTA,CÓDIGO,VALOR (En USD$)
1,"PROPIEDADES, PLANTA Y EQUIPO",502022301,0.00
2,INVENTARIOS,502022302,0.00
3,INSTRUMENTOS FINANCIEROS,502022303,0.00
4,INTANGIBLES,502022304,0.00
5,CUENTAS POR COBRAR,502022305,0.00
6,OTROS ACTIVOS,502022306,0.00
7,DERECHOS DE USO POR ACTIVOS ARRENDADOS,502022307,0.00
8,GASTOS POR CANTIDADES ANORMALES DE UTILIZACION...,5020224,0.00
9,MANO DE OBRA,502022401,0.00
10,MATERIALES,502022402,0.00
11,COSTOS DE PRODUCCION,502022403,0.00
12,GASTO POR REESTRUCTURACION,5020225,0.00
13,VALOR NETO DE REALIZACION DE INVENTARIOS,5020226,0.00
14,GASTO IMPUESTO A LA RENTA (ACTIVOS Y PASIVOS D...,5020227,0.00
15,SUMINISTROS Y MATERIALES,5020228,19174064.09
16,OTROS GASTOS,5020229,38643127.18
17,GASTOS FINANCIEROS,50203,46204675.35
18,INTERESES,5020301,46204675.35
19,INTERESES POR PRESTAMOS,502030101,27849227.12
20,INTERESES POR ARRENDAMIENTOS,502030102,6590621.27
21,INTERESES POR VALORES EMITIDOS,502030103,0.00
22,OTROS INTERESES,502030104,11764826.96
23,COMISIONES,5020302,0.00
24,COMISIONES PAGADAS POR INTERMEDIACIÓN DE VALORES:,502030201,0.00
25,POR OPERACIONES BURSATILES,50203020101,0.00
26,POR CONTRATOS DE UNDERWRITING,50203020103,0.00
27,POR COMISIÓN EN OPERACIONES,50203020104,0.00
28,POR INSCRIPCIONES,50203020105,0.00
29,POR MANTENIMIENTO DE INSCRIPCIÓN,50203020106,0.00
30,POR PRESTACIÓN DE SERVICIOS DE ADMINISTRACIÓN ...,5020303,0.00
31,PORTAFOLIO DE TERCEROS,502030301,0.00
32,FONDOS ADMINISTRADOS,502030302,0.00
33,FONDOS COLECTIVOS,502030303,0.00
34,TITULARIZACIÓN,502030304,0.00
35,FIDEICOMISOS MERCANTILES,502030305,0.00
36,ENCARGOS FIDUCIARIOS,502030306,0.00
37,POR CALIFICACION DE RIESGO,502030307,0.00
38,POR REPRESENTACION DE OBLIGACIONISTAS,502030308,0.00
39,"CUSTODIA, REGISTRO, COMPENSACIÓN Y LIQUIDACIÓN",5020304,0.00
40,CUSTODIA VALORES MATERIALIZADOS,502030401,0.00
41,CUSTODIA VALORES DESMATERIALIZADOS,502030402,0.00
42,COMPENSACIÓN Y LIQUIDACIÓN DE VALORES,502030403,0.00
43,OTROS,502030404,0.00
44,GASTOS POR SERVICIOS DE ASESORIA Y ESTRUCTURACION,5020305,0.00
45,POR ASESORÍA,502030501,0.00
46,POR ESTRUCTURACIÓN DE OFERTA PÚBLICA DE VALORES,502030502,0.00
47,POR ESTRUCTURACIÓN DE NEGOCIOS FIDUCIARIOS,502030503,0.00
48,OTROS,502030504,0.00
49,GASTOS DE FINANCIAMIENTO DE ACTIVOS,5020306,0.00
50,DIFERENCIA EN CAMBIO,5020307,0.00
51,VALUACION DE INSTRUMENTOS FINANCIEROS A VALOR ...,5020308,0.00
52,PERDIDA EN VENTA DE TITULOS VALORES,5020309,0.00
53,"PERDIDA EN VENTA DE PROPIEDAD, PLANTA Y EQUIPO",5020310,0.00
54,PERDIDA EN VENTA DE ACTIVOS BIOLOGICOS,5020311,0.00
55,OTROS GASTOS FINANCIEROS,5020312,0.00

In [9]:
daf5

,Unnamed: 0,ESTADO DE RESULTADO INTEGRAL,Unnamed: 2,Unnamed: 3
0,NaN,CUENTA,CÓDIGO,VALOR (En USD$)
1,NaN,OTROS GASTOS,50204,22787248.01
2,NaN,PERDIDA EN INVERSIONES EN ASOCIADAS / SUBSIDIA...,5020401,0.00
3,NaN,OTROS,5020402,22787248.01
4,NaN,GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES...,600,274234537.53
5,NaN,15% PARTICIPACIÓN TRABAJADORES,601,48389557.08
6,NaN,GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS,602,225844980.45
7,NaN,IMPUESTO A LA RENTA CAUSADO,603,74692616.71
8,NaN,GANANCIA (PÉRDIDA) DE OPERACIONES CONTINUADAS ...,604,151152363.74
9,NaN,(-) GASTO POR IMPUESTO DIFERIDO,605,34315.00
10,NaN,(+) INGRESO POR IMPUESTO DIFERIDO,606,4580987.45
11,NaN,GANANCIA (PERDIDA) DE OPERACIONES CONTINUADAS,607,155767666.19
12,NaN,INGRESOS POR OPERACIONES DISCONTINUADAS,700,0.00
13,NaN,GASTOS POR OPERACIONES DISCONTINUADAS,701,0.00
14,NaN,GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES...,702,0.00
15,NaN,15% PARTICIPACIÓN TRABAJADORES,703,0.00
16,NaN,GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS DE OPERA...,704,0.00
17,NaN,IMPUESTO A LA RENTA CAUSADO,705,0.00
18,NaN,GANANCIA (PÉRDIDA) DE OPERACIONES DISCONTINUADAS,706,0.00
19,NaN,GANANCIA (PÉRDIDA) NETA DEL PERIODO,707,155767666.19
20,NaN,OTRO RESULTADO INTEGRAL,800,0.00
21,NaN,COMPONENTES DEL OTRO RESULTADO INTEGRAL,80001,0.00
22,NaN,DIFERENCIA DE CAMBIO POR CONVERSIÓN,80002,0.00
23,NaN,VALUACIÓN DE ACTIVOS FINANCIEROS A VALOR RAZON...,80003,0.00
24,NaN,"GANANCIAS POR REVALUACIÓN DE PROPIEDADES, PLAN...",80004,0.00
25,NaN,GANANCIAS (PÉRDIDAS) ACTUARIALES POR PLANES DE...,80005,0.00
26,NaN,REVERSION DEL DETERIORO (PÉRDIDA POR DETERIORO...,80006,0.00
27,NaN,PARTICIPACION DE OTRO RESULTADO INTEGRAL DE AS...,80007,0.00
28,NaN,IMPUESTO SOBRE LAS GANANCIAS RELATIVO A OTRO R...,80008,0.00
29,NaN,OTROS (DETALLAR EN NOTAS),80009,0.00
30,NaN,RESULTADO INTEGRAL TOTAL DEL AÑO,801,0.00
31,NaN,PROPIETARIOS DE LA CONTROLADORA,80101,0.00
32,PARTICIPACION NO CONTROLADORA (INFORMATIVO),80102,0.00,NaN

In [10]:
dafHeader

,Unnamed: 0,RAZÓN SOCIAL,CORPORACION FAVORITA C.A.
0,DIRECCIÓN,AV.ELOY ALFARO Y AVIGIRAS No. N52-468 BARRIO:,NaN
1,EXPEDIENTE,384,NaN
2,RUC,1790016919001,NaN
3,AÑO,2022,NaN
4,FORMULARIO,SCV.NIIF.384.2022.1,NaN

In [11]:
daf1.rename(inplace=True, columns={"ESTADO DE RESULTADO INTEGRAL":"CUENTA",
                                "Unnamed: 1":"CODS", "Unnamed: 2":"VALOR EN USD"})

daf1.drop(["CODS"], axis=1, inplace=True)
daf1.drop([0], inplace=True)
daf1.head(8)

                                              CUENTA   VALOR EN USD
1                 INGRESOS DE ACTIVIDADES ORDINARIAS  3603082756.94
2                                    VENTA DE BIENES  3590384805.81
3                            PRESTACION DE SERVICIOS    140899487.4
4                              INGRESOS POR ASESORÍA           0.00
5  INGRESOS POR ESTRUCTURACIÓN DE OFERTA PÚBLICA ...           0.00
6  INGRESOS POR ESTRUCTURACIÓN DE NEGOCIOS FIDUCI...           0.00
7                                              OTROS    140899487.4
8                          CONTRATOS DE CONSTRUCCION           0.00

In [12]:
daf2.rename(inplace=True, columns={"ESTADO DE RESULTADO INTEGRAL":"CUENTA",
                                "Unnamed: 1":"CODS", "Unnamed: 2":"VALOR EN USD"})

daf2.drop(["CODS"], axis=1, inplace=True)
daf2.drop([0], inplace=True)
daf2.head(8)

                                              CUENTA   VALOR EN USD
1                                     GANANCIA BRUTA           0.00
2                                     OTROS INGRESOS           0.00
3    GANANCIA EN VENTA DE PROPIEDAD, PLANTA Y EQUIPO           0.00
4            GANANCIA EN VENTA DE ACTIVOS BIOLÓGICOS           0.00
5                                              OTROS           0.00
6                       COSTO DE VENTAS Y PRODUCCIÓN  2557102527.87
7         MATERIALES UTILIZADOS O PRODUCTOS VENDIDOS  2520857356.11
8  (+) INVENTARIO INICIAL DE BIENES NO PRODUCIDOS...           0.00

In [13]:
daf3.rename(inplace=True, columns={"ESTADO DE RESULTADO INTEGRAL":"CUENTA",
                                "Unnamed: 1":"CODS", "Unnamed: 2":"VALOR EN USD"})

daf3.drop(["CODS"], axis=1, inplace=True)
daf3.drop([0], inplace=True)
daf3.head(8)

                                              CUENTA VALOR EN USD
1           AGUA, ENERGÍA, LUZ, Y TELECOMUNICACIONES         0.00
2  NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MER...         0.00
3                                    DEPRECIACIONES:   7593811.76
4                       PROPIEDADES, PLANTA Y EQUIPO         0.00
5                           PROPIEDADES DE INVERSIÓN         0.00
6                         ACTIVOS POR DERECHO DE USO   7593811.76
7                                     AMORTIZACIONES  88302260.85
8                                        INTANGIBLES  88302260.85

In [14]:
daf4.rename(inplace=True, columns={"ESTADO DE RESULTADO INTEGRAL":"CUENTA",
                                "Unnamed: 1":"CODS", "Unnamed: 2":"VALOR EN USD"})

daf4.drop(["CODS"], axis=1, inplace=True)
daf4.drop([0], inplace=True)
daf4.head(8)

                                              CUENTA VALOR EN USD
1                       PROPIEDADES, PLANTA Y EQUIPO         0.00
2                                        INVENTARIOS         0.00
3                           INSTRUMENTOS FINANCIEROS         0.00
4                                        INTANGIBLES         0.00
5                                 CUENTAS POR COBRAR         0.00
6                                      OTROS ACTIVOS         0.00
7             DERECHOS DE USO POR ACTIVOS ARRENDADOS         0.00
8  GASTOS POR CANTIDADES ANORMALES DE UTILIZACION...         0.00

In [15]:
dafHeader.rename(inplace=True, columns={"Unnamed: 0":"RAZÓN SOCIAL",
                                    "RAZÓN SOCIAL":"CORPORACION FAVORITA C.A.",
                                    "CORPORACION FAVORITA C.A.":"NULLISHCOMLUN"})
dafHeader.drop(["NULLISHCOMLUN"], axis=1, inplace=True)
dafHeader

  RAZÓN SOCIAL                      CORPORACION FAVORITA C.A.
0    DIRECCIÓN  AV.ELOY ALFARO Y AVIGIRAS No. N52-468 BARRIO:
1   EXPEDIENTE                                            384
2          RUC                                  1790016919001
3          AÑO                                           2022
4   FORMULARIO                            SCV.NIIF.384.2022.1

In [16]:
daf5.drop(["Unnamed: 0"], axis=1, inplace=True)
daf5.iloc[ daf5.index[-1] ] = {"ESTADO DE RESULTADO INTEGRAL":"PARTICIPACION NO CONTROLADORA (INFORMATIVO)", "Unnamed: 2":"80102", "Unnamed: 3": "0.00"}

In [18]:
daf5.rename(inplace=True, columns={"CUENTA":"CUENTA",
                                "VALOR EN USD":"CODS", "Unnamed: 3":"VALOR EN USD"})
daf5.drop(["CODS"], axis=1, inplace=True)
daf5.drop([0], inplace=True)
daf5

                         ESTADO DE RESULTADO INTEGRAL Unnamed: 2
1                                        OTROS GASTOS      50204
2   PERDIDA EN INVERSIONES EN ASOCIADAS / SUBSIDIA...    5020401
3                                               OTROS    5020402
4   GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES...        600
5                      15% PARTICIPACIÓN TRABAJADORES        601
6               GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS        602
7                         IMPUESTO A LA RENTA CAUSADO        603
8   GANANCIA (PÉRDIDA) DE OPERACIONES CONTINUADAS ...        604
9                     (-) GASTO POR IMPUESTO DIFERIDO        605
10                  (+) INGRESO POR IMPUESTO DIFERIDO        606
11      GANANCIA (PERDIDA) DE OPERACIONES CONTINUADAS        607
12            INGRESOS POR OPERACIONES DISCONTINUADAS        700
13              GASTOS POR OPERACIONES DISCONTINUADAS        701
14  GANANCIA (PÉRDIDA) ANTES DE 15% A TRABAJADORES...        702
15                     15% PARTICIPACIÓN TRABAJADORES        703
16  GANANCIA (PÉRDIDA) ANTES DE IMPUESTOS DE OPERA...        704
17                        IMPUESTO A LA RENTA CAUSADO        705
18   GANANCIA (PÉRDIDA) DE OPERACIONES DISCONTINUADAS        706
19                GANANCIA (PÉRDIDA) NETA DEL PERIODO        707
20                            OTRO RESULTADO INTEGRAL        800
21            COMPONENTES DEL OTRO RESULTADO INTEGRAL      80001
22                DIFERENCIA DE CAMBIO POR CONVERSIÓN      80002
23  VALUACIÓN DE ACTIVOS FINANCIEROS A VALOR RAZON...      80003
24  GANANCIAS POR REVALUACIÓN DE PROPIEDADES, PLAN...      80004
25  GANANCIAS (PÉRDIDAS) ACTUARIALES POR PLANES DE...      80005
26  REVERSION DEL DETERIORO (PÉRDIDA POR DETERIORO...      80006
27  PARTICIPACION DE OTRO RESULTADO INTEGRAL DE AS...      80007
28  IMPUESTO SOBRE LAS GANANCIAS RELATIVO A OTRO R...      80008
29                          OTROS (DETALLAR EN NOTAS)      80009
30                   RESULTADO INTEGRAL TOTAL DEL AÑO        801
31                    PROPIETARIOS DE LA CONTROLADORA      80101
32        PARTICIPACION NO CONTROLADORA (INFORMATIVO)      80102

In [19]:
dafData = pd.concat([daf1,daf2, daf3, daf4, daf5])

In [20]:
texto = dafData["CUENTA"].to_list()
valores_list = dafData["VALOR EN USD"].to_list()

In [21]:
valores = np.array(valores_list).reshape(1,-1)
datos = pd.DataFrame(valores, columns=texto)

In [22]:
datos

,INGRESOS DE ACTIVIDADES ORDINARIAS,VENTA DE BIENES,PRESTACION DE SERVICIOS,INGRESOS POR ASESORÍA,INGRESOS POR ESTRUCTURACIÓN DE OFERTA PÚBLICA DE VALORES,INGRESOS POR ESTRUCTURACIÓN DE NEGOCIOS FIDUCIARIOS,OTROS,CONTRATOS DE CONSTRUCCION,SUBVENCIONES DEL GOBIERNO,REGALÍAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,3603082756.94,3590384805.81,140899487.4,0.00,0.00,0.00,140899487.4,0.00,0.00,0.00,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [23]:
columns_names = ["REPRESENTATE LEGAL", "CONTADOR"]
pandas_options = {"names":columns_names}

contador = tabula.read_pdf(pdf, pages=5, area=(503,19,568,425), lattice=False, output_format="dataframe", encoding="latin-1", multiple_tables=True,  pandas_options=pandas_options)
dafContador = contador[0]

In [24]:
dafContador

           REPRESENTATE LEGAL                   CONTADOR
0  REPRESENTANTE(S) LEGAL(ES)                   CONTADOR
1    SAENZ MIÑO FERNANDO JOSE  BRAVO ARELLANO JORGE LUIS
2                  1704239654              1708033251001
3                         NaN                     038674

In [25]:
print(dafContador.shape[0])
print(len(dafContador))

4
4

In [26]:
with pd.ExcelWriter("../Outputs/Docs2LaFavorita/Resultado_integral/infoResultadoIntegral.xlsx", engine="xlsxwriter") as writer:
    dafHeader.to_excel(writer, sheet_name="Encabezado", index=False)
    dafContador.to_excel(writer, sheet_name="Encabezado", index=False, startrow=len(dafHeader)+2)
    datos.to_excel(writer, sheet_name="Datos", index=False)