In [1]:
import pandas as pd
import numpy as np
import tabula

C:\Users\Usuario\AppData\Local\Temp\ipykernel_2464\3008533230.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
pdfOriginal = "../Inputs/DocEconomica_6712_3_1_1_2021_12_31_00_00_00_000.pdf"
excel_output = "../Outputs/esf_alt1.xlsx"

In [3]:
#with pd.ExcelFile(excel_output) as xls:
#    dfAcumulado_encabezado = pd.read_excel(xls, 'Encabezado', dtype=object)
#    dfAcumulado_datos = pd.read_excel(xls, 'Datos', dtype=object)
#dfAcumulado_datos

In [4]:
coords = {
    "1":(110.55,6.12,916.86,605.88),
    "2":(21.05,6.12,916.86,605.88),
    "3":(21.05,6.12,916.86,605.88),
    "4":(21.05,6.12,916.86,605.88),
    "5":(21.05,6.12,916.86,605.88),
    "6":(21.05,6.12,916.86,605.88),
    "7":(21.05,6.12,916.86,605.88),
    "8":(21.05,6.12,916.86,605.88),
    "9":(21.05,6.12,916.86,605.88),
    "10":(21.05,6.12,916.86,605.88),
    "11":(21.05,6.12,916.86,605.88),
    "12":(21.05,6.12,381.41,605.88)


}

In [5]:

first = tabula.read_pdf(pdfOriginal, pages=1, area=(110.55,6.12,916.86,605.88), lattice=False, output_format="dataframe", encoding="latin-1")
df1 = first[0]
df1

Error importing jpype dependencies. Fallback to subprocess.
No module named 'jpype'

,OPERACIONES CON PARTES RELACIONADAS LOCALES Y/O DEL EXTERIOR,Unnamed: 1,Unnamed: 2
0,CON PARTES RELACIONADAS LOCALES,NaN,NaN
1,Operaciones de activo,3.0,0.00
2,Operaciones de pasivo,4.0,0.00
3,Operaciones de ingreso,5.0,16999072.30
4,Operaciones de egreso,6.0,141014.32
...,...,...,...
61,Crédito tributario a favor del sujeto pasivo (...,336.0,0.00
62,Crédito tributario a favor del sujeto pasivo (...,337.0,304182.83
63,Otros,338.0,0.00
64,INVENTARIOS,NaN,NaN
65,Mercaderías en tránsito,339.0,250211.10

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 3 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   OPERACIONES CON PARTES RELACIONADAS LOCALES Y/O DEL EXTERIOR  66 non-null     object
 1   Unnamed: 1                                                    46 non-null     float64
 2   Unnamed: 2                                                    46 non-null     object
dtypes: float64(1), object(2)
memory usage: 1.7+ KB

In [7]:
df1[df1["Unnamed: 2"].isna()]

,OPERACIONES CON PARTES RELACIONADAS LOCALES Y/O DEL EXTERIOR,Unnamed: 1,Unnamed: 2
0,CON PARTES RELACIONADAS LOCALES,NaN,NaN
6,"CON PARTES RELACIONADAS EN PARAÍSOS FISCALES, ...",NaN,NaN
12,CON PARTES RELACIONADAS EN OTRAS JURISDICCIONE...,NaN,NaN
20,ESTADO DE SITUACIÓN FINANCIERA,NaN,NaN
21,ACTIVO,NaN,NaN
22,ACTIVOS CORRIENTES,NaN,NaN
24,CUENTAS Y DOCUMENTOS POR COBRAR CORRIENTES,NaN,NaN
25,CUENTAS Y DOCUMENTOS POR COBRAR COMERCIALES CO...,NaN,NaN
26,RELACIONADAS,NaN,NaN
30,NO RELACIONADAS,NaN,NaN
34,OTRAS CUENTAS Y DOCUMENTOS POR COBRAR CORRIENTES,NaN,NaN
35,"A ACCIONISTAS, SOCIOS, PARTICIPES, BENEFICIARI...",NaN,NaN
38,DIVIDENDOS POR COBRAR,NaN,NaN
41,OTRAS RELACIONADAS,NaN,NaN
45,OTRAS NO RELACIONADAS,NaN,NaN
49,OTROS ACTIVOS FINANCIEROS CORRIENTES,NaN,NaN
53,PORCIÓN CORRIENTE DE ARRENDAMIENTOS FINANCIERO...,NaN,NaN
56,IMPORTE BRUTO ADEUDADO POR LOS CLIENTES POR EL...,NaN,NaN
59,ACTIVOS POR IMPUESTOS CORRIENTES,NaN,NaN
64,INVENTARIOS,NaN,NaN

In [8]:
"""(df1["Unnamed: 2"].isna()) & (df1["Unnamed: 1"].isna())"""
indexNulls = df1[ (df1["Unnamed: 2"].isna())  ].index
df1.drop(indexNulls, inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46 entries, 1 to 65
Data columns (total 3 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   OPERACIONES CON PARTES RELACIONADAS LOCALES Y/O DEL EXTERIOR  46 non-null     object
 1   Unnamed: 1                                                    46 non-null     float64
 2   Unnamed: 2                                                    46 non-null     object
dtypes: float64(1), object(2)
memory usage: 1.4+ KB

AQUII

In [9]:
df1.iloc[:]

,OPERACIONES CON PARTES RELACIONADAS LOCALES Y/O DEL EXTERIOR,Unnamed: 1,Unnamed: 2
1,Operaciones de activo,3.0,0.00
2,Operaciones de pasivo,4.0,0.00
3,Operaciones de ingreso,5.0,16999072.30
4,Operaciones de egreso,6.0,141014.32
5,"Operaciones de regalías, servicios técnicos, a...",7.0,0.00
7,Operaciones de activo,8.0,0.00
8,Operaciones de pasivo,9.0,0.00
9,Operaciones de ingreso,10.0,0.00
10,Operaciones de egreso,11.0,0.00
11,"Operaciones de regalías, servicios técnicos, a...",12.0,0.00
13,Operaciones de activo,13.0,0.00
14,Operaciones de pasivo,14.0,0.00
15,Operaciones de ingreso,15.0,0.00
16,Operaciones de egreso,16.0,0.00
17,"Operaciones de regalías, servicios técnicos, a...",17.0,0.00
18,TOTAL OPERACIONES CON PARTES RELACIONADAS,29.0,17140086.60
19,¿Sujeto pasivo exento de aplicación del régime...,30.0,NO
23,Efectivo y equivalentes al efectivo,311.0,1349952.02
27,Locales,312.0,4260917.80
28,Del exterior,313.0,0.00
29,(-) Deterioro acumulado del valor de cuentas y...,314.0,0.00
31,Locales,315.0,338867.98
32,Del exterior,316.0,0.00
33,(-) Deterioro acumulado del valor de cuentas y...,317.0,34326.37
36,Locales,318.0,0.00
37,Del exterior,319.0,0.00
39,En efectivo,320.0,0.00
40,En activos diferentes del efectivo,321.0,0.00
42,Locales,322.0,1852191.80
43,Del exterior,323.0,0.00
44,(-) Deterioro acumulado del valor de otras cue...,324.0,0.00
46,Locales,325.0,351441.66
47,Del exterior,326.0,205734.31
48,(-) Deterioro acumulado del valor de otras cue...,327.0,0.00
50,A costo amortizado,328.0,0.00
51,(-) Deterioro acumulado del valor de otros ac...,329.0,0.00
52,A valor razonable,330.0,0.00
54,Relacionadas,331.0,0.00
55,No relacionadas,332.0,0.00
57,Relacionadas,333.0,0.00
58,No relacionadas,334.0,0.00
60,Crédito tributario a favor del sujeto pasivo (...,335.0,0.00
61,Crédito tributario a favor del sujeto pasivo (...,336.0,0.00
62,Crédito tributario a favor del sujeto pasivo (...,337.0,304182.83
63,Otros,338.0,0.00
65,Mercaderías en tránsito,339.0,250211.10

In [10]:
result = df1[ df1["Unnamed: 2"] == "NO"] 
print(result.index[0])
if result.index[0] != None:
    df1.drop( [result.index[0]], inplace=True )

df1

19

,OPERACIONES CON PARTES RELACIONADAS LOCALES Y/O DEL EXTERIOR,Unnamed: 1,Unnamed: 2
1,Operaciones de activo,3.0,0.00
2,Operaciones de pasivo,4.0,0.00
3,Operaciones de ingreso,5.0,16999072.30
4,Operaciones de egreso,6.0,141014.32
5,"Operaciones de regalías, servicios técnicos, a...",7.0,0.00
7,Operaciones de activo,8.0,0.00
8,Operaciones de pasivo,9.0,0.00
9,Operaciones de ingreso,10.0,0.00
10,Operaciones de egreso,11.0,0.00
11,"Operaciones de regalías, servicios técnicos, a...",12.0,0.00
13,Operaciones de activo,13.0,0.00
14,Operaciones de pasivo,14.0,0.00
15,Operaciones de ingreso,15.0,0.00
16,Operaciones de egreso,16.0,0.00
17,"Operaciones de regalías, servicios técnicos, a...",17.0,0.00
18,TOTAL OPERACIONES CON PARTES RELACIONADAS,29.0,17140086.60
23,Efectivo y equivalentes al efectivo,311.0,1349952.02
27,Locales,312.0,4260917.80
28,Del exterior,313.0,0.00
29,(-) Deterioro acumulado del valor de cuentas y...,314.0,0.00
31,Locales,315.0,338867.98
32,Del exterior,316.0,0.00
33,(-) Deterioro acumulado del valor de cuentas y...,317.0,34326.37
36,Locales,318.0,0.00
37,Del exterior,319.0,0.00
39,En efectivo,320.0,0.00
40,En activos diferentes del efectivo,321.0,0.00
42,Locales,322.0,1852191.80
43,Del exterior,323.0,0.00
44,(-) Deterioro acumulado del valor de otras cue...,324.0,0.00
46,Locales,325.0,351441.66
47,Del exterior,326.0,205734.31
48,(-) Deterioro acumulado del valor de otras cue...,327.0,0.00
50,A costo amortizado,328.0,0.00
51,(-) Deterioro acumulado del valor de otros ac...,329.0,0.00
52,A valor razonable,330.0,0.00
54,Relacionadas,331.0,0.00
55,No relacionadas,332.0,0.00
57,Relacionadas,333.0,0.00
58,No relacionadas,334.0,0.00
60,Crédito tributario a favor del sujeto pasivo (...,335.0,0.00
61,Crédito tributario a favor del sujeto pasivo (...,336.0,0.00
62,Crédito tributario a favor del sujeto pasivo (...,337.0,304182.83
63,Otros,338.0,0.00
65,Mercaderías en tránsito,339.0,250211.10

In [11]:
texto = df1["OPERACIONES CON PARTES RELACIONADAS LOCALES Y/O DEL EXTERIOR"].to_list()
valores = np.array( df1["Unnamed: 2"].to_list() ).reshape(1,-1)
datosF1 = pd.DataFrame(valores, columns=texto)
datosF1

,Operaciones de activo,Operaciones de pasivo,Operaciones de ingreso,Operaciones de egreso,"Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares",Operaciones de activo,Operaciones de pasivo,Operaciones de ingreso,Operaciones de egreso,"Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares",...,A valor razonable,Relacionadas,No relacionadas,Relacionadas,No relacionadas,Crédito tributario a favor del sujeto pasivo (ISD),Crédito tributario a favor del sujeto pasivo (IVA),Crédito tributario a favor del sujeto pasivo (Impuesto a la Renta),Otros,Mercaderías en tránsito
0,0.00,0.00,16999072.30,141014.32,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,304182.83,0.00,250211.10

### Segunda Hoja del pdf

In [12]:
second = tabula.read_pdf(pdfOriginal, pages=2, area=(21.05,6.12,916.86,605.88), lattice=False, output_format="dataframe", encoding="latin-1")
df2 = second[0]
df2

   Inventario de materia prima (no para la construcción)    340  1594231.60
0   Inventario de productos en proceso (excluyendo...     341.0   471091.05
1   Inventario de prod. term. y mercad. en almacén...     342.0  1778265.94
2   Inventario de suministros, herramientas, repue...     343.0  1122335.99
3   Inventario de materia prima, suministros y mat...     344.0        0.00
4   Inventario de obras/inmuebles en construcción ...     345.0        0.00
..                                                ...       ...         ...
69  (-) Amortización acumulada de derechos de uso ...     491.0        0.00
70                           PROPIEDADES DE INVERSIÓN       NaN         NaN
71                                           TERRENOS       NaN         NaN
72                                            A costo     394.0  1648557.11
73                                  A valor razonable     395.0        0.00

[74 rows x 3 columns]

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 3 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Inventario de materia prima (no para la construcción)  74 non-null     object
 1   340                                                    57 non-null     float64
 2   1594231.60                                             57 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.9+ KB

In [14]:
indexNulls = df2[ (df2["340"].isna()) & (df2["1594231.60"].isna()) ].index
df2.drop(indexNulls, inplace=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57 entries, 0 to 73
Data columns (total 3 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Inventario de materia prima (no para la construcción)  57 non-null     object
 1   340                                                    57 non-null     float64
 2   1594231.60                                             57 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.8+ KB

In [15]:
df2

   Inventario de materia prima (no para la construcción)    340   1594231.60
0   Inventario de productos en proceso (excluyendo...     341.0    471091.05
1   Inventario de prod. term. y mercad. en almacén...     342.0   1778265.94
2   Inventario de suministros, herramientas, repue...     343.0   1122335.99
3   Inventario de materia prima, suministros y mat...     344.0         0.00
4   Inventario de obras/inmuebles en construcción ...     345.0         0.00
5   Inventario de obras/inmuebles terminados para ...     346.0         0.00
6   (-) Deterioro acumulado del valor de inventari...     347.0         0.00
8                                               Costo     348.0    347158.76
9   (-) Deterioro acumulado del valor de activos n...     349.0         0.00
12                                            A costo     350.0         0.00
13  (-) Deterioro acumulado del valor de activos b...     351.0         0.00
14        A valor razonable menos los costos de venta     352.0         0.00
16                                            A costo     353.0         0.00
17  (-) Deterioro acumulado del valor de activos b...     354.0         0.00
18        A valor razonable menos los costos de venta     355.0         0.00
20                  Propaganda y publicidad prepagada     356.0         0.00
21   Arrendamientos operativos pagados por anticipado     357.0         0.00
22            Primas de seguro pagadas por anticipado     358.0      1497.62
23                                              Otros     359.0    369338.03
24                           Otros Activos Corrientes     360.0         0.00
25                           TOTAL ACTIVOS CORRIENTES     361.0  14563092.10
29  Costo histórico antes de reexpresiones o reval...     362.0   1152785.88
30  Ajuste acumulado por reexpresiones o revaluaci...     363.0    697772.71
32  Costo histórico antes de reexpresiones o reval...     364.0   1879596.32
33  Ajuste acumulado por reexpresiones o revaluaci...     365.0    676269.68
35  Costo histórico antes de reexpresiones o reval...     366.0         0.00
36  Ajuste acumulado por reexpresiones o revaluaci...     367.0         0.00
38  Costo histórico antes de reexpresiones o reval...     368.0   2784451.44
39  Ajuste acumulado por reexpresiones o revaluaci...     369.0    291936.62
41  Costo histórico antes de reexpresiones o reval...     370.0         0.00
42  Ajuste acumulado por reexpresiones o revaluaci...     371.0         0.00
43  Construcciones en Curso y Otros Activos en Trá...     372.0         0.00
44                                  Muebles y enseres     373.0   2367554.08
45                              Equipo de Computación     374.0   1062025.93
46   Vehículos, Equipo de Transporte y Caminero Móvil     375.0   3908607.58
48                                           Terrenos     376.0         0.00
49     Edificios y otros inmuebles (excepto terrenos)     377.0         0.00
50             Naves, aeronaves, barcazas y similares     378.0         0.00
51   Maquinaria, equipo, instalaciones y adecuaciones     379.0         0.00
52                              Equipo de computación     380.0         0.00
53   Vehículos, equipo de transporte y caminero móvil     381.0         0.00
54                                              Otros     382.0         0.00
55                 Otras Propiedades, Planta y Equipo     383.0      6762.52
57  Del costo histórico antes de reexpresiones o r...     384.0   5308405.62
58  Del ajuste acumulado por reexpresiones o reval...     385.0     63639.48
59  (-) Deterioro acumulado del valor de propiedad...     386.0         0.00
61            Plusvalía o goodwill (derecho de llave)     387.0         0.00
62      Marcas, patentes, licencias y otros similares     388.0   2330782.20
63  Adecuaciones y mejoras en bienes arrendados me...     389.0         0.00
64                  Derechos en acuerdos de concesión     390.0         0.00
65                                              Otros     391.0         0.00
66  (-) Amortización acumulada de activos intangibles     392.0   1935262.98
67     (-) Deterioro acumulado de activos intangibles     393.0         0.00
68             Derechos de uso por activos arrendados     490.0         0.00
69  (-) Amortización acumulada de derechos de uso ...     491.0         0.00
72                                            A costo     394.0   1648557.11
73                                  A valor razonable     395.0         0.00

In [16]:
df2.columns

Index(['Inventario de materia prima (no para la construcción)', '340',
       '1594231.60'],
      dtype='object')

In [17]:
newFirstRow = pd.DataFrame([df2.columns.to_list()], columns=df2.columns)
newFirstRow

  Inventario de materia prima (no para la construcción)  340  1594231.60
0  Inventario de materia prima (no para la constr...     340  1594231.60

In [18]:
dataFrame2 = pd.concat([newFirstRow, df2])
dataFrame2

   Inventario de materia prima (no para la construcción)    340  1594231.60
0   Inventario de materia prima (no para la constr...       340  1594231.60
0   Inventario de productos en proceso (excluyendo...     341.0   471091.05
1   Inventario de prod. term. y mercad. en almacén...     342.0  1778265.94
2   Inventario de suministros, herramientas, repue...     343.0  1122335.99
3   Inventario de materia prima, suministros y mat...     344.0         0.0
4   Inventario de obras/inmuebles en construcción ...     345.0         0.0
5   Inventario de obras/inmuebles terminados para ...     346.0         0.0
6   (-) Deterioro acumulado del valor de inventari...     347.0         0.0
8                                               Costo     348.0   347158.76
9   (-) Deterioro acumulado del valor de activos n...     349.0         0.0
12                                            A costo     350.0         0.0
13  (-) Deterioro acumulado del valor de activos b...     351.0         0.0
14        A valor razonable menos los costos de venta     352.0         0.0
16                                            A costo     353.0         0.0
17  (-) Deterioro acumulado del valor de activos b...     354.0         0.0
18        A valor razonable menos los costos de venta     355.0         0.0
20                  Propaganda y publicidad prepagada     356.0         0.0
21   Arrendamientos operativos pagados por anticipado     357.0         0.0
22            Primas de seguro pagadas por anticipado     358.0     1497.62
23                                              Otros     359.0   369338.03
24                           Otros Activos Corrientes     360.0         0.0
25                           TOTAL ACTIVOS CORRIENTES     361.0  14563092.1
29  Costo histórico antes de reexpresiones o reval...     362.0  1152785.88
30  Ajuste acumulado por reexpresiones o revaluaci...     363.0   697772.71
32  Costo histórico antes de reexpresiones o reval...     364.0  1879596.32
33  Ajuste acumulado por reexpresiones o revaluaci...     365.0   676269.68
35  Costo histórico antes de reexpresiones o reval...     366.0         0.0
36  Ajuste acumulado por reexpresiones o revaluaci...     367.0         0.0
38  Costo histórico antes de reexpresiones o reval...     368.0  2784451.44
39  Ajuste acumulado por reexpresiones o revaluaci...     369.0   291936.62
41  Costo histórico antes de reexpresiones o reval...     370.0         0.0
42  Ajuste acumulado por reexpresiones o revaluaci...     371.0         0.0
43  Construcciones en Curso y Otros Activos en Trá...     372.0         0.0
44                                  Muebles y enseres     373.0  2367554.08
45                              Equipo de Computación     374.0  1062025.93
46   Vehículos, Equipo de Transporte y Caminero Móvil     375.0  3908607.58
48                                           Terrenos     376.0         0.0
49     Edificios y otros inmuebles (excepto terrenos)     377.0         0.0
50             Naves, aeronaves, barcazas y similares     378.0         0.0
51   Maquinaria, equipo, instalaciones y adecuaciones     379.0         0.0
52                              Equipo de computación     380.0         0.0
53   Vehículos, equipo de transporte y caminero móvil     381.0         0.0
54                                              Otros     382.0         0.0
55                 Otras Propiedades, Planta y Equipo     383.0     6762.52
57  Del costo histórico antes de reexpresiones o r...     384.0  5308405.62
58  Del ajuste acumulado por reexpresiones o reval...     385.0    63639.48
59  (-) Deterioro acumulado del valor de propiedad...     386.0         0.0
61            Plusvalía o goodwill (derecho de llave)     387.0         0.0
62      Marcas, patentes, licencias y otros similares     388.0   2330782.2
63  Adecuaciones y mejoras en bienes arrendados me...     389.0         0.0
64                  Derechos en acuerdos de concesión     390.0         0.0
65                                              Otros     391.0         0.0
66  (-) Amortización acumulada de activos intangibles     392.0  1935262.98
67     (-) Deterioro acumulado de activos intangibles     393.0         0.0
68             Derechos de uso por activos arrendados     490.0         0.0
69  (-) Amortización acumulada de derechos de uso ...     491.0         0.0
72                                            A costo     394.0  1648557.11
73                                  A valor razonable     395.0         0.0

In [19]:
columnasNumericas= ["340","1594231.60"]
dataFrame2[columnasNumericas] = dataFrame2[columnasNumericas].astype(object)
dataFrame2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 73
Data columns (total 3 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Inventario de materia prima (no para la construcción)  58 non-null     object
 1   340                                                    58 non-null     object
 2   1594231.60                                             58 non-null     object
dtypes: object(3)
memory usage: 1.8+ KB

In [20]:
dataFrame2

   Inventario de materia prima (no para la construcción)    340  1594231.60
0   Inventario de materia prima (no para la constr...       340  1594231.60
0   Inventario de productos en proceso (excluyendo...     341.0   471091.05
1   Inventario de prod. term. y mercad. en almacén...     342.0  1778265.94
2   Inventario de suministros, herramientas, repue...     343.0  1122335.99
3   Inventario de materia prima, suministros y mat...     344.0         0.0
4   Inventario de obras/inmuebles en construcción ...     345.0         0.0
5   Inventario de obras/inmuebles terminados para ...     346.0         0.0
6   (-) Deterioro acumulado del valor de inventari...     347.0         0.0
8                                               Costo     348.0   347158.76
9   (-) Deterioro acumulado del valor de activos n...     349.0         0.0
12                                            A costo     350.0         0.0
13  (-) Deterioro acumulado del valor de activos b...     351.0         0.0
14        A valor razonable menos los costos de venta     352.0         0.0
16                                            A costo     353.0         0.0
17  (-) Deterioro acumulado del valor de activos b...     354.0         0.0
18        A valor razonable menos los costos de venta     355.0         0.0
20                  Propaganda y publicidad prepagada     356.0         0.0
21   Arrendamientos operativos pagados por anticipado     357.0         0.0
22            Primas de seguro pagadas por anticipado     358.0     1497.62
23                                              Otros     359.0   369338.03
24                           Otros Activos Corrientes     360.0         0.0
25                           TOTAL ACTIVOS CORRIENTES     361.0  14563092.1
29  Costo histórico antes de reexpresiones o reval...     362.0  1152785.88
30  Ajuste acumulado por reexpresiones o revaluaci...     363.0   697772.71
32  Costo histórico antes de reexpresiones o reval...     364.0  1879596.32
33  Ajuste acumulado por reexpresiones o revaluaci...     365.0   676269.68
35  Costo histórico antes de reexpresiones o reval...     366.0         0.0
36  Ajuste acumulado por reexpresiones o revaluaci...     367.0         0.0
38  Costo histórico antes de reexpresiones o reval...     368.0  2784451.44
39  Ajuste acumulado por reexpresiones o revaluaci...     369.0   291936.62
41  Costo histórico antes de reexpresiones o reval...     370.0         0.0
42  Ajuste acumulado por reexpresiones o revaluaci...     371.0         0.0
43  Construcciones en Curso y Otros Activos en Trá...     372.0         0.0
44                                  Muebles y enseres     373.0  2367554.08
45                              Equipo de Computación     374.0  1062025.93
46   Vehículos, Equipo de Transporte y Caminero Móvil     375.0  3908607.58
48                                           Terrenos     376.0         0.0
49     Edificios y otros inmuebles (excepto terrenos)     377.0         0.0
50             Naves, aeronaves, barcazas y similares     378.0         0.0
51   Maquinaria, equipo, instalaciones y adecuaciones     379.0         0.0
52                              Equipo de computación     380.0         0.0
53   Vehículos, equipo de transporte y caminero móvil     381.0         0.0
54                                              Otros     382.0         0.0
55                 Otras Propiedades, Planta y Equipo     383.0     6762.52
57  Del costo histórico antes de reexpresiones o r...     384.0  5308405.62
58  Del ajuste acumulado por reexpresiones o reval...     385.0    63639.48
59  (-) Deterioro acumulado del valor de propiedad...     386.0         0.0
61            Plusvalía o goodwill (derecho de llave)     387.0         0.0
62      Marcas, patentes, licencias y otros similares     388.0   2330782.2
63  Adecuaciones y mejoras en bienes arrendados me...     389.0         0.0
64                  Derechos en acuerdos de concesión     390.0         0.0
65                                              Otros     391.0         0.0
66  (-) Amortización acumulada de activos intangibles     392.0  1935262.98
67     (-) Deterioro acumulado de activos intangibles     393.0         0.0
68             Derechos de uso por activos arrendados     490.0         0.0
69  (-) Amortización acumulada de derechos de uso ...     491.0         0.0
72                                            A costo     394.0  1648557.11
73                                  A valor razonable     395.0         0.0

renombrar las columnas del dataframe 2 si esque aplica

In [21]:
texto.clear()
texto = dataFrame2["Inventario de materia prima (no para la construcción)"].to_list()
valores = np.array( dataFrame2["1594231.60"].to_list() ).reshape(1,-1)
datosF2 = pd.DataFrame(valores, columns=texto)
datosF2

,Inventario de materia prima (no para la construcción),Inventario de productos en proceso (excluyendo obras/inmuebles en construcción para la venta),Inventario de prod. term. y mercad. en almacén (excluyendo obras/inmuebles terminados para la venta),"Inventario de suministros, herramientas, repuestos y materiales (no para la construcción)","Inventario de materia prima, suministros y materiales para la construcción",Inventario de obras/inmuebles en construcción para la venta,Inventario de obras/inmuebles terminados para la venta,(-) Deterioro acumulado del valor de inventarios por ajuste al valor neto realizable,Costo,(-) Deterioro acumulado del valor de activos no corrientes mantenidos para la venta,...,"Marcas, patentes, licencias y otros similares",Adecuaciones y mejoras en bienes arrendados mediante arrendamiento operativo,Derechos en acuerdos de concesión,Otros,(-) Amortización acumulada de activos intangibles,(-) Deterioro acumulado de activos intangibles,Derechos de uso por activos arrendados,(-) Amortización acumulada de derechos de uso por activos arrendados,A costo,A valor razonable
0,1594231.60,471091.05,1778265.94,1122335.99,0.0,0.0,0.0,0.0,347158.76,0.0,...,2330782.2,0.0,0.0,0.0,1935262.98,0.0,0.0,0.0,1648557.11,0.0

### Tercera hoja del pdf

In [22]:
third = tabula.read_pdf(pdfOriginal, pages=3, area=(21.05,6.12,916.86,605.88), lattice=False, output_format="dataframe", encoding="latin-1")
df3 = third[0]
df3

,Unnamed: 0,EDIFICIOS,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,A costo,NaN,396.0,0.0
1,NaN,A valor razonable,NaN,397.0,0.0
2,NaN,(-) Depreciación Acumulada de Propiedades de I...,NaN,398.0,0.0
3,NaN,(-) Deterioro Acumulado del Valor de Propiedad...,NaN,399.0,0.0
4,ACTIVOS BIOLÓGICOS,NaN,NaN,NaN,NaN
...,...,...,...,...,...
68,NaN,Otros,NaN,444.0,0.0
69,Otros Activos No Corrientes,NaN,NaN,445.0,0.0
70,TOTAL ACTIVOS NO CORRIENTES,NaN,NaN,449.0,28885366.2
71,REVALUACIONES Y REEXPRESIONES DE ACTIVOS (INFO...,NaN,NaN,NaN,NaN
72,Ajustes acumulados por reexpresiones o revalua...,NaN,NaN,460.0,0.0

In [23]:
#df3.iloc[:30]

In [24]:
#df3.iloc[30:62]

In [25]:
#df3.iloc[62:]

In [26]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  11 non-null     object
 1   EDIFICIOS   47 non-null     object
 2   Unnamed: 2  15 non-null     object
 3   Unnamed: 3  52 non-null     float64
 4   Unnamed: 4  52 non-null     float64
dtypes: float64(2), object(3)
memory usage: 3.0+ KB

In [27]:
#print(df3["Unnamed: 0"].to_list() )
#print(len(df3["Unnamed: 0"].to_list()))
#print(df3["Unnamed: 0"])
#print(len(df3["Unnamed: 0"]))
#indexNulls = df3[ (df3["Unnamed: 0"].isna()) & (df3["EDIFICIOS"].isna())
#                    & (df3["Unnamed: 2"].isna()) & (df3["Unnamed: 3"].isna()) & (df3["Unnamed: 4"].isna())].index

#df3.drop(indexNulls, inplace=True)
#df3.info()

In [28]:
df3['EDIFICIOS'] = df3[['Unnamed: 0', 'EDIFICIOS', 'Unnamed: 2']].apply(lambda x: ' '.join(map(str, x)), axis=1)

In [29]:
df3.iloc[30:62]

,Unnamed: 0,EDIFICIOS,Unnamed: 2,Unnamed: 3,Unnamed: 4
30,NaN,nan Otros Derechos Representativos de Capital ...,NaN,418.0,3508300.61
31,NaN,nan (-) Deterioro Acumulado del Valor de Inver...,NaN,419.0,0.00
32,CUENTAS Y DOCUMENTOS POR COBRAR NO CORRIENTES,CUENTAS Y DOCUMENTOS POR COBRAR NO CORRIENTES ...,NaN,NaN,NaN
33,NaN,nan CUENTAS Y DOCUMENTOS POR COBRAR COMERCIALE...,NaN,NaN,NaN
34,NaN,nan RELACIONADAS nan,NaN,NaN,NaN
35,NaN,nan nan Locales,Locales,420.0,3483182.44
36,NaN,nan nan Del exterior,Del exterior,421.0,0.00
37,NaN,nan nan (-) Deterioro acumulado del valor de c...,(-) Deterioro acumulado del valor de cuentas y...,422.0,0.00
38,NaN,nan NO RELACIONADAS nan,NaN,NaN,NaN
39,NaN,nan nan Locales,Locales,423.0,0.00
40,NaN,nan nan Del exterior,Del exterior,424.0,0.00
41,NaN,nan nan (-) Deterioro acumulado del valor de c...,(-) Deterioro acumulado del valor de cuentas y...,425.0,0.00
42,NaN,nan OTRAS CUENTAS Y DOCUMENTOS POR COBRAR NO C...,NaN,NaN,NaN
43,NaN,"nan A ACCIONISTAS. SOCIOS, PARTICIPES. BENEFIC...",NaN,NaN,NaN
44,NaN,nan nan Locales,Locales,426.0,0.00
45,NaN,nan nan Del exterior,Del exterior,427.0,0.00
46,NaN,nan nan (-) Deterioro acumulado del valor de c...,(-) Deterioro acumulado del valor de cuentas y...,428.0,0.00
47,NaN,nan OTRAS RELACIONADAS nan,NaN,NaN,NaN
48,NaN,nan nan Locales,Locales,429.0,0.00
49,NaN,nan nan Del exterior,Del exterior,430.0,0.00
50,NaN,nan nan (-) Deterioro acumulado del valor de c...,(-) Deterioro acumulado del valor de cuentas y...,431.0,0.00
51,NaN,nan OTRAS NO RELACIONADAS nan,NaN,NaN,NaN
52,NaN,nan nan Locales,Locales,432.0,0.00
53,NaN,nan nan Del exterior,Del exterior,433.0,1329072.92
54,NaN,nan nan (-) Deterioro acumulado del valor de o...,(-) Deterioro acumulado del valor de otras cue...,434.0,1329072.92
55,OTROS ACTIVOS FINANCIEROS NO CORRIENTES,OTROS ACTIVOS FINANCIEROS NO CORRIENTES nan nan,NaN,NaN,NaN
56,NaN,nan A costo amortizado nan,NaN,435.0,0.00
57,NaN,nan (-) Deterioro acumulado del valor de otro...,NaN,436.0,0.00
58,NaN,nan A valor razonable nan,NaN,437.0,0.00
59,PORCIÓN NO CORRIENTE DE ARRENDAMIENTOS FINANCI...,PORCIÓN NO CORRIENTE DE ARRENDAMIENTOS FINANCI...,NaN,NaN,NaN
60,NaN,nan Relacionadas nan,NaN,438.0,0.00
61,NaN,nan No Relacionadas nan,NaN,439.0,0.00

In [30]:
print(df3["EDIFICIOS"].to_list())

['nan A costo nan', 'nan A valor razonable nan', 'nan (-) Depreciación Acumulada de Propiedades de Inversión nan', 'nan (-) Deterioro Acumulado del Valor de Propiedades de Inversión nan', 'ACTIVOS BIOLÓGICOS nan nan', 'nan PLANTAS VIVAS Y FRUTOS EN CRECIMIENTO nan', 'nan A costo nan', 'nan (-) Depreciación acumulada de activos biológicos medidos a costo nan', 'nan (-) Deterioro acumulado del valor de activos biológicos medidos a costo nan', 'nan A valor razonable menos los costos de venta nan', 'nan ANIMALES VIVOS nan', 'nan A costo nan', 'nan (-) Depreciación acumulada de activos biológicos medidos a costo nan', 'nan (-) Deterioro acumulado del valor de activos biológicos medidos a costo nan', 'nan A valor razonable menos los costos de venta nan', 'ACTIVOS PARA EXPLORACIÓN, EVALUACIÓN Y EXPLOTACIÓN DE RECURSOS MINERALES nan nan', 'nan Tangibles nan', 'nan Intangibles nan', 'nan (-) Depreciación / amortización acumulada de activos para exploración, evaluación y explotación nan', 'nan (-) Deterioro acumulado del valor de activos para exploración, evaluación y explotación nan', 'INVERSIONES NO CORRIENTES nan nan', 'nan EN SUBSIDIARIAS nan', 'nan Costo nan', 'nan Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional) nan', 'nan EN ASOCIADAS nan', 'nan Costo nan', 'nan Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional) nan', 'nan EN NEGOCIOS CONJUNTOS nan', 'nan Costo nan', 'nan Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional) nan', 'nan Otros Derechos Representativos de Capital en Sociedades que no son Subsidiarias, ni Asociadas, ni Negocios Conjuntos nan', 'nan (-) Deterioro Acumulado del Valor de Inversiones no Corrientes nan', 'CUENTAS Y DOCUMENTOS POR COBRAR NO CORRIENTES nan nan', 'nan CUENTAS Y DOCUMENTOS POR COBRAR COMERCIALES NO CORRIENTES nan', 'nan RELACIONADAS nan', 'nan nan Locales', 'nan nan Del exterior', 'nan nan (-) Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)', 'nan NO RELACIONADAS nan', 'nan nan Locales', 'nan nan Del exterior', 'nan nan (-) Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)', 'nan OTRAS CUENTAS Y DOCUMENTOS POR COBRAR NO CORRIENTES nan', 'nan A ACCIONISTAS. SOCIOS, PARTICIPES. BENEFICIARIOS U OTROS TITULARES DE DERECHOS REPRESENTATIVOS DE CAPITAL nan', 'nan nan Locales', 'nan nan Del exterior', 'nan nan (-) Deterioro acumulado del valor de cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', 'nan OTRAS RELACIONADAS nan', 'nan nan Locales', 'nan nan Del exterior', 'nan nan (-) Deterioro acumulado del valor de cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', 'nan OTRAS NO RELACIONADAS nan', 'nan nan Locales', 'nan nan Del exterior', 'nan nan (-) Deterioro acumulado del valor de otras cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', 'OTROS ACTIVOS FINANCIEROS NO CORRIENTES nan nan', 'nan A costo amortizado nan', 'nan (-) Deterioro acumulado del valor  de otros activos financieros no corrientes medidos a costo amortizado (provisiones para créditos incobrables) nan', 'nan A valor razonable nan', 'PORCIÓN NO CORRIENTE DE ARRENDAMIENTOS FINANCIEROS POR COBRAR nan nan', 'nan Relacionadas nan', 'nan No Relacionadas nan', 'ACTIVOS POR IMPUESTOS DIFERIDOS nan nan', 'nan Por diferencias temporarias nan', 'nan Por pérdidas tributarias sujetas a amortización en periodos siguientes nan', 'nan POR CRÉDITOS FISCALES NO UTILIZADOS nan', 'nan Crédito tributario a favor del sujeto pasivo (ISD) nan', 'nan Crédito tributario a favor del sujeto pasivo (Impuesto a la Renta) nan', 'nan Otros nan', 'Otros Activos No Corrientes nan nan', 'TOTAL ACTIVOS NO CORRIENTES nan nan', 'REVALUACIONES Y REEXPRESIONES DE ACTIVOS (INFORMATIVO) nan nan', 'Ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo) nan nan']

In [31]:
columnaTextosEdificios = df3["EDIFICIOS"].to_list()
for k in range(len(columnaTextosEdificios)):
    columnaTextosEdificios[k] = columnaTextosEdificios[k].replace("nan","").rstrip()

In [32]:
print(columnaTextosEdificios)

[' A costo', ' A valor razonable', ' (-) Depreciación Acumulada de Propiedades de Inversión', ' (-) Deterioro Acumulado del Valor de Propiedades de Inversión', 'ACTIVOS BIOLÓGICOS', ' PLANTAS VIVAS Y FRUTOS EN CRECIMIENTO', ' A costo', ' (-) Depreciación acumulada de activos biológicos medidos a costo', ' (-) Deterioro acumulado del valor de activos biológicos medidos a costo', ' A valor razonable menos los costos de venta', ' ANIMALES VIVOS', ' A costo', ' (-) Depreciación acumulada de activos biológicos medidos a costo', ' (-) Deterioro acumulado del valor de activos biológicos medidos a costo', ' A valor razonable menos los costos de venta', 'ACTIVOS PARA EXPLORACIÓN, EVALUACIÓN Y EXPLOTACIÓN DE RECURSOS MINERALES', ' Tangibles', ' Intangibles', ' (-) Depreciación / amortización acumulada de activos para exploración, evaluación y explotación', ' (-) Deterioro acumulado del valor de activos para exploración, evaluación y explotación', 'INVERSIONES NO CORRIENTES', ' EN SUBSIDIARIAS', ' Costo', ' Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional)', ' EN ASOCIADAS', ' Costo', ' Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional)', ' EN NEGOCIOS CONJUNTOS', ' Costo', ' Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional)', ' Otros Derechos Representativos de Capital en Sociedades que no son Subsidiarias, ni Asociadas, ni Negocios Conjuntos', ' (-) Deterioro Acumulado del Valor de Inversiones no Corrientes', 'CUENTAS Y DOCUMENTOS POR COBRAR NO CORRIENTES', ' CUENTAS Y DOCUMENTOS POR COBRAR COMERCIALES NO CORRIENTES', ' RELACIONADAS', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)', ' NO RELACIONADAS', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)', ' OTRAS CUENTAS Y DOCUMENTOS POR COBRAR NO CORRIENTES', ' A ACCIONISTAS. SOCIOS, PARTICIPES. BENEFICIARIOS U OTROS TITULARES DE DERECHOS REPRESENTATIVOS DE CAPITAL', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', ' OTRAS RELACIONADAS', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', ' OTRAS NO RELACIONADAS', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de otras cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', 'OTROS ACTIVOS FINANCIEROS NO CORRIENTES', ' A costo amortizado', ' (-) Deterioro acumulado del valor  de otros activos ficieros no corrientes medidos a costo amortizado (provisiones para créditos incobrables)', ' A valor razonable', 'PORCIÓN NO CORRIENTE DE ARRENDAMIENTOS FINANCIEROS POR COBRAR', ' Relacionadas', ' No Relacionadas', 'ACTIVOS POR IMPUESTOS DIFERIDOS', ' Por diferencias temporarias', ' Por pérdidas tributarias sujetas a amortización en periodos siguientes', ' POR CRÉDITOS FISCALES NO UTILIZADOS', ' Crédito tributario a favor del sujeto pasivo (ISD)', ' Crédito tributario a favor del sujeto pasivo (Impuesto a la Renta)', ' Otros', 'Otros Activos No Corrientes', 'TOTAL ACTIVOS NO CORRIENTES', 'REVALUACIONES Y REEXPRESIONES DE ACTIVOS (INFORMATIVO)', 'Ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)']

In [33]:
df3["EDIFICIOS"].iloc[0]
print(len(df3["EDIFICIOS"]))

73

In [34]:
for k in range(len(df3["EDIFICIOS"])):
    df3["EDIFICIOS"].replace(df3["EDIFICIOS"].iloc[k],columnaTextosEdificios[k], inplace=True  )

C:\Users\Usuario\AppData\Local\Temp\ipykernel_2464\2446168622.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3["EDIFICIOS"].replace(df3["EDIFICIOS"].iloc[k],columnaTextosEdificios[k], inplace=True  )

In [35]:
#df3.iloc[30:62]

In [36]:
indexColumnasNulls = df3[ (df3["Unnamed: 2"].isna()) & (df3["Unnamed: 3"].isna()) & (df3["Unnamed: 4"].isna())].index
df3.drop(indexColumnasNulls, inplace=True)
print(df3.info())
print(df3)

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, 0 to 72
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  3 non-null      object
 1   EDIFICIOS   52 non-null     object
 2   Unnamed: 2  15 non-null     object
 3   Unnamed: 3  52 non-null     float64
 4   Unnamed: 4  52 non-null     float64
dtypes: float64(2), object(3)
memory usage: 2.4+ KB
None
                                           Unnamed: 0  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
22                                                NaN
23                                                NaN
25                                                NaN
26                                                NaN
28                                                NaN
29                                                NaN
30                                                NaN
31                                                NaN
35                                                NaN
36                                                NaN
37                                                NaN
39                                                NaN
40                                                NaN
41                                                NaN
44                                                NaN
45                                                NaN
46                                                NaN
48                                                NaN
49                                                NaN
50                                                NaN
52                                                NaN
53                                                NaN
54                                                NaN
56                                                NaN
57                                                NaN
58                                                NaN
60                                                NaN
61                                                NaN
63                                                NaN
64                                                NaN
66                                                NaN
67                                                NaN
68                                                NaN
69                        Otros Activos No Corrientes
70                        TOTAL ACTIVOS NO CORRIENTES
72  Ajustes acumulados por reexpresiones o revalua...

                                            EDIFICIOS  \
0                                             A costo
1                                   A valor razonable
2    (-) Depreciación Acumulada de Propiedades de ...
3    (-) Deterioro Acumulado del Valor de Propieda...
6                                             A costo
7    (-) Depreciación acumulada de activos biológi...
8    (-) Deterioro acumulado del valor de activos ...
9         A valor razonable menos los costos de venta
11                                            A costo
12   (-) Depreciación acumulada de activos biológi...
13   (-) Deterioro acumulado del valor de activos ...
14        A valor razonable menos los costos de venta
16                                          Tangibles
17                                        Intangibles
18   (-) Depreciación / amortización acumulada de ...
19   (-) Deterioro acumulado del valor de activos ...
22                                              Costo
23   Ajuste acumulado por aplicación del método de...
25                                              Costo
26   Ajuste acumulado por aplicación del método de...
28                                              Costo
29   Ajuste acumulado por aplicación del método de...
30   Otros Derechos Representativos de Capital en ...
31   (-) Deterioro Acumulado del Valor de Inversio...
35                                            Locales
36                                       Del exterior
37    (-) Deterioro acumulado del valor de cuentas...
39                                            Locales
40                                       Del exterior
41    (-) Deterioro acumulado del valor de cuentas...
44                                            Locales
45                                       Del exterior
46    (-) Deterioro acumulado del valor de cuentas...
48                                            Locales
49                                       Del exterior
50    (-) Deterioro acumulado del valor de cuentas...
52                                            Locales
53                                       Del exterior
54    (-) Deterioro acumulado del valor de otras c...
56                                 A costo amortizado
57   (-) Deterioro acumulado del valor  de otros a...
58                                  A valor razonable
60                                       Relacionadas
61                                    No Relacionadas
63                        Por diferencias temporarias
64   Por pérdidas tributarias sujetas a amortizaci...
66   Crédito tributario a favor del sujeto pasivo ...
67   Crédito tributario a favor del sujeto pasivo ...
68                                              Otros
69                        Otros Activos No Corrientes
70                        TOTAL ACTIVOS NO CORRIENTES
72  Ajustes acumulados por reexpresiones o revalua...

                                           Unnamed: 2  Unnamed: 3   Unnamed: 4
0                                                 NaN       396.0         0.00
1                                                 NaN       397.0         0.00
2                                                 NaN       398.0         0.00
3                                                 NaN       399.0         0.00
6                                                 NaN       400.0         0.00
7                                                 NaN       401.0         0.00
8                                                 NaN       402.0         0.00
9                                                 NaN       403.0         0.00
11                                                NaN       404.0         0.00
12                                                NaN       405.0         0.00
13                                                NaN       406.0         0.00
14                                                NaN       407.0         0.00
16                                                NaN       408.0         0.00
17                                                NaN       409.0         0.00
18                                                NaN       410.0         0.00
19                                                NaN       411.0         0.00
22                                                NaN       412.0  10300514.00
23                                                NaN       413.0         0.00
25                                                NaN       414.0        95.00
26                                                NaN       415.0         0.00
28                                                NaN       416.0         0.00
29                                                NaN       417.0         0.00
30                                                NaN       418.0   3508300.61
31                                                NaN       419.0         0.00
35                                            Locales       420.0   3483182.44
36                                       Del exterior       421.0         0.00
37  (-) Deterioro acumulado del valor de cuentas y...       422.0         0.00
39                                            Locales       423.0         0.00
40                                       Del exterior       424.0         0.00
41  (-) Deterioro acumulado del valor de cuentas y...       425.0         0.00
44                                            Locales       426.0         0.00
45                                       Del exterior       427.0         0.00
46  (-) Deterioro acumulado del valor de cuentas y...       428.0         0.00
48                                            Locales       429.0         0.00
49                                       Del exterior       430.0         0.00
50  (-) Deterioro acumulado del valor de cuentas y...       431.0         0.00
52                                            Locales       432.0         0.00
53                                       Del exterior       433.0   1329072.92
54  (-) Deterioro acumulado del valor de otras cue...       434.0   1329072.92
56                                                NaN       435.0         0.00
57                                                NaN       436.0         0.00
58                                                NaN       437.0         0.00
60                                                NaN       438.0         0.00
61                                                NaN       439.0         0.00
63                                                NaN       440.0     93480.14
64                                                NaN       441.0         0.00
66                                                NaN       442.0         0.00
67                                                NaN       443.0         0.00
68                                                NaN       444.0         0.00
69                                                NaN       445.0         0.00
70                                                NaN       449.0  28885366.20
72                                                NaN       460.0         0.00

In [37]:
df3

,Unnamed: 0,EDIFICIOS,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,A costo,NaN,396.0,0.00
1,NaN,A valor razonable,NaN,397.0,0.00
2,NaN,(-) Depreciación Acumulada de Propiedades de ...,NaN,398.0,0.00
3,NaN,(-) Deterioro Acumulado del Valor de Propieda...,NaN,399.0,0.00
6,NaN,A costo,NaN,400.0,0.00
7,NaN,(-) Depreciación acumulada de activos biológi...,NaN,401.0,0.00
8,NaN,(-) Deterioro acumulado del valor de activos ...,NaN,402.0,0.00
9,NaN,A valor razonable menos los costos de venta,NaN,403.0,0.00
11,NaN,A costo,NaN,404.0,0.00
12,NaN,(-) Depreciación acumulada de activos biológi...,NaN,405.0,0.00
13,NaN,(-) Deterioro acumulado del valor de activos ...,NaN,406.0,0.00
14,NaN,A valor razonable menos los costos de venta,NaN,407.0,0.00
16,NaN,Tangibles,NaN,408.0,0.00
17,NaN,Intangibles,NaN,409.0,0.00
18,NaN,(-) Depreciación / amortización acumulada de ...,NaN,410.0,0.00
19,NaN,(-) Deterioro acumulado del valor de activos ...,NaN,411.0,0.00
22,NaN,Costo,NaN,412.0,10300514.00
23,NaN,Ajuste acumulado por aplicación del método de...,NaN,413.0,0.00
25,NaN,Costo,NaN,414.0,95.00
26,NaN,Ajuste acumulado por aplicación del método de...,NaN,415.0,0.00
28,NaN,Costo,NaN,416.0,0.00
29,NaN,Ajuste acumulado por aplicación del método de...,NaN,417.0,0.00
30,NaN,Otros Derechos Representativos de Capital en ...,NaN,418.0,3508300.61
31,NaN,(-) Deterioro Acumulado del Valor de Inversio...,NaN,419.0,0.00
35,NaN,Locales,Locales,420.0,3483182.44
36,NaN,Del exterior,Del exterior,421.0,0.00
37,NaN,(-) Deterioro acumulado del valor de cuentas...,(-) Deterioro acumulado del valor de cuentas y...,422.0,0.00
39,NaN,Locales,Locales,423.0,0.00
40,NaN,Del exterior,Del exterior,424.0,0.00
41,NaN,(-) Deterioro acumulado del valor de cuentas...,(-) Deterioro acumulado del valor de cuentas y...,425.0,0.00
44,NaN,Locales,Locales,426.0,0.00
45,NaN,Del exterior,Del exterior,427.0,0.00
46,NaN,(-) Deterioro acumulado del valor de cuentas...,(-) Deterioro acumulado del valor de cuentas y...,428.0,0.00
48,NaN,Locales,Locales,429.0,0.00
49,NaN,Del exterior,Del exterior,430.0,0.00
50,NaN,(-) Deterioro acumulado del valor de cuentas...,(-) Deterioro acumulado del valor de cuentas y...,431.0,0.00
52,NaN,Locales,Locales,432.0,0.00
53,NaN,Del exterior,Del exterior,433.0,1329072.92
54,NaN,(-) Deterioro acumulado del valor de otras c...,(-) Deterioro acumulado del valor de otras cue...,434.0,1329072.92
56,NaN,A costo amortizado,NaN,435.0,0.00
57,NaN,(-) Deterioro acumulado del valor de otros a...,NaN,436.0,0.00
58,NaN,A valor razonable,NaN,437.0,0.00
60,NaN,Relacionadas,NaN,438.0,0.00
61,NaN,No Relacionadas,NaN,439.0,0.00
63,NaN,Por diferencias temporarias,NaN,440.0,93480.14
64,NaN,Por pérdidas tributarias sujetas a amortizaci...,NaN,441.0,0.00
66,NaN,Crédito tributario a favor del sujeto pasivo ...,NaN,442.0,0.00
67,NaN,Crédito tributario a favor del sujeto pasivo ...,NaN,443.0,0.00
68,NaN,Otros,NaN,444.0,0.00
69,Otros Activos No Corrientes,Otros Activos No Corrientes,NaN,445.0,0.00
70,TOTAL ACTIVOS NO CORRIENTES,TOTAL ACTIVOS NO CORRIENTES,NaN,449.0,28885366.20
72,Ajustes acumulados por reexpresiones o revalua...,Ajustes acumulados por reexpresiones o revalua...,NaN,460.0,0.00

In [38]:
df3.drop(["Unnamed: 0","Unnamed: 2"], axis=1, inplace=True)
df3

                                            EDIFICIOS  Unnamed: 3   Unnamed: 4
0                                             A costo       396.0         0.00
1                                   A valor razonable       397.0         0.00
2    (-) Depreciación Acumulada de Propiedades de ...       398.0         0.00
3    (-) Deterioro Acumulado del Valor de Propieda...       399.0         0.00
6                                             A costo       400.0         0.00
7    (-) Depreciación acumulada de activos biológi...       401.0         0.00
8    (-) Deterioro acumulado del valor de activos ...       402.0         0.00
9         A valor razonable menos los costos de venta       403.0         0.00
11                                            A costo       404.0         0.00
12   (-) Depreciación acumulada de activos biológi...       405.0         0.00
13   (-) Deterioro acumulado del valor de activos ...       406.0         0.00
14        A valor razonable menos los costos de venta       407.0         0.00
16                                          Tangibles       408.0         0.00
17                                        Intangibles       409.0         0.00
18   (-) Depreciación / amortización acumulada de ...       410.0         0.00
19   (-) Deterioro acumulado del valor de activos ...       411.0         0.00
22                                              Costo       412.0  10300514.00
23   Ajuste acumulado por aplicación del método de...       413.0         0.00
25                                              Costo       414.0        95.00
26   Ajuste acumulado por aplicación del método de...       415.0         0.00
28                                              Costo       416.0         0.00
29   Ajuste acumulado por aplicación del método de...       417.0         0.00
30   Otros Derechos Representativos de Capital en ...       418.0   3508300.61
31   (-) Deterioro Acumulado del Valor de Inversio...       419.0         0.00
35                                            Locales       420.0   3483182.44
36                                       Del exterior       421.0         0.00
37    (-) Deterioro acumulado del valor de cuentas...       422.0         0.00
39                                            Locales       423.0         0.00
40                                       Del exterior       424.0         0.00
41    (-) Deterioro acumulado del valor de cuentas...       425.0         0.00
44                                            Locales       426.0         0.00
45                                       Del exterior       427.0         0.00
46    (-) Deterioro acumulado del valor de cuentas...       428.0         0.00
48                                            Locales       429.0         0.00
49                                       Del exterior       430.0         0.00
50    (-) Deterioro acumulado del valor de cuentas...       431.0         0.00
52                                            Locales       432.0         0.00
53                                       Del exterior       433.0   1329072.92
54    (-) Deterioro acumulado del valor de otras c...       434.0   1329072.92
56                                 A costo amortizado       435.0         0.00
57   (-) Deterioro acumulado del valor  de otros a...       436.0         0.00
58                                  A valor razonable       437.0         0.00
60                                       Relacionadas       438.0         0.00
61                                    No Relacionadas       439.0         0.00
63                        Por diferencias temporarias       440.0     93480.14
64   Por pérdidas tributarias sujetas a amortizaci...       441.0         0.00
66   Crédito tributario a favor del sujeto pasivo ...       442.0         0.00
67   Crédito tributario a favor del sujeto pasivo ...       443.0         0.00
68                                              Otros       444.0         0.00
69                        Otros Activos No Corrientes       445.0         0.00
70                        TOTAL ACTIVOS NO CORRIENTES       449.0  28885366.20
72  Ajustes acumulados por reexpresiones o revalua...       460.0         0.00

In [39]:
texto.clear()
texto = df3["EDIFICIOS"].to_list()
valores = np.array( df3["Unnamed: 4"].to_list() ).reshape(1,-1)
datosF3 = pd.DataFrame(valores, columns=texto) 
datosF3

,A costo,A valor razonable,(-) Depreciación Acumulada de Propiedades de Inversión,(-) Deterioro Acumulado del Valor de Propiedades de Inversión,A costo,(-) Depreciación acumulada de activos biológicos medidos a costo,(-) Deterioro acumulado del valor de activos biológicos medidos a costo,A valor razonable menos los costos de venta,A costo,(-) Depreciación acumulada de activos biológicos medidos a costo,...,Relacionadas,No Relacionadas,Por diferencias temporarias,Por pérdidas tributarias sujetas a amortización en periodos siguientes,Crédito tributario a favor del sujeto pasivo (ISD),Crédito tributario a favor del sujeto pasivo (Impuesto a la Renta),Otros,Otros Activos No Corrientes,TOTAL ACTIVOS NO CORRIENTES,"Ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)"
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,93480.14,0.0,0.0,0.0,0.0,0.0,28885366.2,0.0

### Cuarta hoja del pdf

In [40]:
fourth = tabula.read_pdf(pdfOriginal, pages=4, area=coords["4"], lattice=False, output_format="dataframe", encoding="latin-1")
df4 = fourth[0]
df4

,"(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)",461,0.00
0,Ajustes acumulados por reexpresiones o revalua...,462.0,0.00
1,(-) Amortización acumulada de los ajustes acum...,463.0,0.00
2,Ajustes acumulados por reexpresiones o revalua...,464.0,0.00
3,(-) Depreciación acumulada de los ajustes acum...,465.0,0.00
4,Ajustes acumulados por reexpresiones o revalua...,466.0,0.00
...,...,...,...
68,Otras,544.0,0.00
69,PASIVOS POR INGRESOS DIFERIDOS,NaN,NaN
70,Anticipos de clientes,545.0,1365270.83
71,Subvenciones del Gobierno,546.0,0.00
72,Otros,547.0,0.00

In [41]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 3 columns):
 #   Column                                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                                  --------------  -----
 0   (-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)  73 non-null     object
 1   461                                                                                                                                                     54 non-null     float64
 2   0.00                                                                                                                                                    54 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.8+ KB

In [42]:
indexNulls = df4[ (df4["461"].isna()) & (df4["0.00"].isna()) ].index
df4.drop(indexNulls, inplace=True)
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54 entries, 0 to 72
Data columns (total 3 columns):
 #   Column                                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                                  --------------  -----
 0   (-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)  54 non-null     object
 1   461                                                                                                                                                     54 non-null     float64
 2   0.00                                                                                                                                                    54 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.7+ KB

In [43]:
df4

,"(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)",461,0.00
0,Ajustes acumulados por reexpresiones o revalua...,462.0,0.00
1,(-) Amortización acumulada de los ajustes acum...,463.0,0.00
2,Ajustes acumulados por reexpresiones o revalua...,464.0,0.00
3,(-) Depreciación acumulada de los ajustes acum...,465.0,0.00
4,Ajustes acumulados por reexpresiones o revalua...,466.0,0.00
5,(-) Depreciación/amortización acumulada del aj...,467.0,0.00
6,Total de las revaluaciones y otros ajustes po...,468.0,0.00
7,(-) Total depreciación acumulada del ajuste ac...,469.0,0.00
9,Total costo de terrenos en los que se desarrol...,470.0,0.00
10,Total deterioro acumulado del costo de terreno...,471.0,0.00
11,Total costo de terrenos en los que se desarrol...,472.0,0.00
12,Total deterioro acumulado del costo de terreno...,473.0,0.00
13,Total de intereses implícitos no devengados (f...,474.0,0.00
14,Activos (fideicomitidos y generados) en fideic...,475.0,0.00
15,Activos adquiridos por el valor de las utilida...,476.0,0.00
16,TOTAL DEL ACTIVO,499.0,43448458.30
22,Locales,511.0,78380.54
23,Del exterior,512.0,0.00
25,Locales,513.0,5730768.00
26,Del exterior,514.0,1979614.66
29,Locales,515.0,468206.61
30,Del exterior,516.0,0.00
32,En efectivo,517.0,132921.62
33,En activos diferentes del efectivo,518.0,0.00
35,Locales,519.0,201246.49
36,Del exterior,520.0,0.00
38,Locales,521.0,2884347.41
39,Del exterior,522.0,1246618.06
42,Locales,523.0,0.00
43,Del exterior,524.0,0.00
45,Locales,525.0,3018224.61
46,Del exterior,526.0,0.00
47,Crédito A Mutuo,527.0,0.00
48,Porción Corriente de Obligaciones Emitidas,528.0,0.00
50,A costo amortizado,529.0,0.00
51,A valor razonable,530.0,0.00
52,Porción Corriente de Arrendamientos Financiero...,531.0,0.00
53,Pasivo corriente por arrendamiento,593.0,0.00
54,Impuesto A La Renta Por Pagar Del Ejercicio,532.0,554584.92
56,Participación trabajadores por pagar del ejerc...,533.0,0.00
57,Obligaciones con el IESS,534.0,27190.01
58,Jubilación Patronal,535.0,0.00
59,Otros Pasivos Corrientes Por Beneficios a Empl...,536.0,832618.85
61,Por garantías,537.0,0.00
62,Por desmantelamiento,538.0,0.00
63,Por contratos onerosos,539.0,0.00
64,Por reestructuraciones de negocios,540.0,0.00
65,Por reembolsos a clientes,541.0,0.00
66,Por litigios,542.0,0.00
67,Por pasivos contingentes asumidos en una combi...,543.0,0.00
68,Otras,544.0,0.00
70,Anticipos de clientes,545.0,1365270.83
71,Subvenciones del Gobierno,546.0,0.00
72,Otros,547.0,0.00

In [44]:
df4.columns

Index(['(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)',
       '461', '0.00'],
      dtype='object')

In [45]:
newFirstRow = pd.DataFrame([df4.columns.to_list()], columns=df4.columns)
newFirstRow

,"(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)",461,0.00
0,(-) Depreciación acumulada de los ajustes acum...,461,0.00

In [46]:
dataframe4 = pd.concat([newFirstRow, df4])
dataframe4

,"(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)",461,0.00
0,(-) Depreciación acumulada de los ajustes acum...,461,0.00
0,Ajustes acumulados por reexpresiones o revalua...,462.0,0.0
1,(-) Amortización acumulada de los ajustes acum...,463.0,0.0
2,Ajustes acumulados por reexpresiones o revalua...,464.0,0.0
3,(-) Depreciación acumulada de los ajustes acum...,465.0,0.0
4,Ajustes acumulados por reexpresiones o revalua...,466.0,0.0
5,(-) Depreciación/amortización acumulada del aj...,467.0,0.0
6,Total de las revaluaciones y otros ajustes po...,468.0,0.0
7,(-) Total depreciación acumulada del ajuste ac...,469.0,0.0
9,Total costo de terrenos en los que se desarrol...,470.0,0.0
10,Total deterioro acumulado del costo de terreno...,471.0,0.0
11,Total costo de terrenos en los que se desarrol...,472.0,0.0
12,Total deterioro acumulado del costo de terreno...,473.0,0.0
13,Total de intereses implícitos no devengados (f...,474.0,0.0
14,Activos (fideicomitidos y generados) en fideic...,475.0,0.0
15,Activos adquiridos por el valor de las utilida...,476.0,0.0
16,TOTAL DEL ACTIVO,499.0,43448458.3
22,Locales,511.0,78380.54
23,Del exterior,512.0,0.0
25,Locales,513.0,5730768.0
26,Del exterior,514.0,1979614.66
29,Locales,515.0,468206.61
30,Del exterior,516.0,0.0
32,En efectivo,517.0,132921.62
33,En activos diferentes del efectivo,518.0,0.0
35,Locales,519.0,201246.49
36,Del exterior,520.0,0.0
38,Locales,521.0,2884347.41
39,Del exterior,522.0,1246618.06
42,Locales,523.0,0.0
43,Del exterior,524.0,0.0
45,Locales,525.0,3018224.61
46,Del exterior,526.0,0.0
47,Crédito A Mutuo,527.0,0.0
48,Porción Corriente de Obligaciones Emitidas,528.0,0.0
50,A costo amortizado,529.0,0.0
51,A valor razonable,530.0,0.0
52,Porción Corriente de Arrendamientos Financiero...,531.0,0.0
53,Pasivo corriente por arrendamiento,593.0,0.0
54,Impuesto A La Renta Por Pagar Del Ejercicio,532.0,554584.92
56,Participación trabajadores por pagar del ejerc...,533.0,0.0
57,Obligaciones con el IESS,534.0,27190.01
58,Jubilación Patronal,535.0,0.0
59,Otros Pasivos Corrientes Por Beneficios a Empl...,536.0,832618.85
61,Por garantías,537.0,0.0
62,Por desmantelamiento,538.0,0.0
63,Por contratos onerosos,539.0,0.0
64,Por reestructuraciones de negocios,540.0,0.0
65,Por reembolsos a clientes,541.0,0.0
66,Por litigios,542.0,0.0
67,Por pasivos contingentes asumidos en una combi...,543.0,0.0
68,Otras,544.0,0.0
70,Anticipos de clientes,545.0,1365270.83
71,Subvenciones del Gobierno,546.0,0.0
72,Otros,547.0,0.0

In [47]:
columnasNumericas= ["461","0.00"]
dataframe4[columnasNumericas] = dataframe4[columnasNumericas].astype(float)
dataframe4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 0 to 72
Data columns (total 3 columns):
 #   Column                                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                                  --------------  -----
 0   (-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)  55 non-null     object
 1   461                                                                                                                                                     55 non-null     float64
 2   0.00                                                                                                                                                    55 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.7+ KB

In [48]:
dataframe4

,"(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)",461,0.00
0,(-) Depreciación acumulada de los ajustes acum...,461.0,0.00
0,Ajustes acumulados por reexpresiones o revalua...,462.0,0.00
1,(-) Amortización acumulada de los ajustes acum...,463.0,0.00
2,Ajustes acumulados por reexpresiones o revalua...,464.0,0.00
3,(-) Depreciación acumulada de los ajustes acum...,465.0,0.00
4,Ajustes acumulados por reexpresiones o revalua...,466.0,0.00
5,(-) Depreciación/amortización acumulada del aj...,467.0,0.00
6,Total de las revaluaciones y otros ajustes po...,468.0,0.00
7,(-) Total depreciación acumulada del ajuste ac...,469.0,0.00
9,Total costo de terrenos en los que se desarrol...,470.0,0.00
10,Total deterioro acumulado del costo de terreno...,471.0,0.00
11,Total costo de terrenos en los que se desarrol...,472.0,0.00
12,Total deterioro acumulado del costo de terreno...,473.0,0.00
13,Total de intereses implícitos no devengados (f...,474.0,0.00
14,Activos (fideicomitidos y generados) en fideic...,475.0,0.00
15,Activos adquiridos por el valor de las utilida...,476.0,0.00
16,TOTAL DEL ACTIVO,499.0,43448458.30
22,Locales,511.0,78380.54
23,Del exterior,512.0,0.00
25,Locales,513.0,5730768.00
26,Del exterior,514.0,1979614.66
29,Locales,515.0,468206.61
30,Del exterior,516.0,0.00
32,En efectivo,517.0,132921.62
33,En activos diferentes del efectivo,518.0,0.00
35,Locales,519.0,201246.49
36,Del exterior,520.0,0.00
38,Locales,521.0,2884347.41
39,Del exterior,522.0,1246618.06
42,Locales,523.0,0.00
43,Del exterior,524.0,0.00
45,Locales,525.0,3018224.61
46,Del exterior,526.0,0.00
47,Crédito A Mutuo,527.0,0.00
48,Porción Corriente de Obligaciones Emitidas,528.0,0.00
50,A costo amortizado,529.0,0.00
51,A valor razonable,530.0,0.00
52,Porción Corriente de Arrendamientos Financiero...,531.0,0.00
53,Pasivo corriente por arrendamiento,593.0,0.00
54,Impuesto A La Renta Por Pagar Del Ejercicio,532.0,554584.92
56,Participación trabajadores por pagar del ejerc...,533.0,0.00
57,Obligaciones con el IESS,534.0,27190.01
58,Jubilación Patronal,535.0,0.00
59,Otros Pasivos Corrientes Por Beneficios a Empl...,536.0,832618.85
61,Por garantías,537.0,0.00
62,Por desmantelamiento,538.0,0.00
63,Por contratos onerosos,539.0,0.00
64,Por reestructuraciones de negocios,540.0,0.00
65,Por reembolsos a clientes,541.0,0.00
66,Por litigios,542.0,0.00
67,Por pasivos contingentes asumidos en una combi...,543.0,0.00
68,Otras,544.0,0.00
70,Anticipos de clientes,545.0,1365270.83
71,Subvenciones del Gobierno,546.0,0.00
72,Otros,547.0,0.00

In [49]:
texto.clear()
texto = dataframe4["(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)"].to_list()
valores = np.array( dataframe4["0.00"].to_list() ).reshape(1,-1)
datosF4 = pd.DataFrame(valores, columns=texto)
datosF4

,"(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)",Ajustes acumulados por reexpresiones o revaluaciones de activos intangibles (Informativo),(-) Amortización acumulada de los ajustes acumulados por reexpresiones o revaluaciones de activos intangibles (Informativo),Ajustes acumulados por reexpresiones o revaluaciones de propiedades de inversión (Informativo),(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de propiedades de inversión (Informativo),"Ajustes acumulados por reexpresiones o revaluaciones de activos para exploración, evaluación y explotación de recursos minerales (Informativo)","(-) Depreciación/amortización acumulada del ajustes acumulado por reexpresiones o revaluaciones de activos para exploración, evaluación y explotación de recursos minerales (Informativo)","Total de las revaluaciones y otros ajustes positivos producto de valoraciones financieras excluidos del cálculo del anticipo, para todos los activos (Informativo)","(-) Total depreciación acumulada del ajuste acumulado por revaluaciones y otros ajustes negativos producto de valoraciones financieras excluidos del cálculo del anticipo, para todos los activos (Informativo)",Total costo de terrenos en los que se desarrollan actividades agropecuarias (excluyendo sus revaluaciones o reexpresiones) (Informativo),...,Por desmantelamiento,Por contratos onerosos,Por reestructuraciones de negocios,Por reembolsos a clientes,Por litigios,Por pasivos contingentes asumidos en una combinación de negocios,Otras,Anticipos de clientes,Subvenciones del Gobierno,Otros
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1365270.83,0.0,0.0

### Quinta hoja del PDF

In [50]:
fifth = tabula.read_pdf(pdfOriginal, pages=5, area=(21.05,6.12,916.86,605.88), lattice=False, output_format="dataframe", encoding="latin-1")
df5 = fifth[0]
df5

                             OTROS PASIVOS CORRIENTES  Unnamed: 1  Unnamed: 2
0   Transferencias casa matriz y sucursales (del e...       548.0         0.0
1                                               Otros       549.0         0.0
2                            TOTAL PASIVOS CORRIENTES       550.0  18519992.6
3                               PASIVOS NO CORRIENTES         NaN         NaN
4        CUENTAS Y DOCUMENTOS POR PAGAR NO CORRIENTES         NaN         NaN
..                                                ...         ...         ...
68                                              Otras       606.0    441163.1
69                              RESULTADOS ACUMULADOS         NaN         NaN
70                                 Reserva de capital       607.0       500.0
71                             Reserva por donaciones       608.0         0.0
72  Reserva por valuación (procedente de la aplica...       609.0         0.0

[73 rows x 3 columns]

In [51]:
indexNulls = df5[ (df5["Unnamed: 1"].isna()) & (df5["Unnamed: 2"].isna()) ].index
df5.drop(indexNulls, inplace=True)
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 72
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   OTROS PASIVOS CORRIENTES  53 non-null     object
 1   Unnamed: 1                53 non-null     float64
 2   Unnamed: 2                53 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.7+ KB

In [52]:
df5

                             OTROS PASIVOS CORRIENTES  Unnamed: 1   Unnamed: 2
0   Transferencias casa matriz y sucursales (del e...       548.0         0.00
1                                               Otros       549.0         0.00
2                            TOTAL PASIVOS CORRIENTES       550.0  18519992.60
7                                             Locales       553.0         0.00
8                                        Del exterior       554.0         0.00
10                                            Locales       555.0         0.00
11                                       Del exterior       556.0         0.00
14                                            Locales       557.0         0.00
15                                       Del exterior       558.0         0.00
17                                            Locales       559.0         0.00
18                                       Del exterior       560.0         0.00
20                                            Locales       561.0         0.00
21                                       Del exterior       562.0    500000.00
24                                            Locales       563.0         0.00
25                                       Del exterior       564.0         0.00
27                                            Locales       565.0  10253715.70
28                                       Del exterior       566.0         0.00
29                                    Crédito a mutuo       567.0         0.00
30      Porción no corriente de obligaciones emitidas       568.0         0.00
32                                 A costo amortizado       569.0         0.00
33                                  A valor razonable       570.0         0.00
34  Porción no corriente de arrendamientos financi...       571.0         0.00
35              Pasivo no corriente por arrendamiento       594.0         0.00
36            Pasivo por Impuesto a la Renta diferido       572.0    224815.91
38                                Jubilación Patronal       573.0    972019.71
39                                          Desahucio       574.0    220359.02
40  Otros Pasivos No Corrientes Por Beneficios A E...       575.0         0.00
42                                      Por garantías       576.0         0.00
43                               Por desmantelamiento       577.0         0.00
44                             Por contratos onerosos       578.0         0.00
45                 Por reestructuraciones de negocios       579.0         0.00
46                          Por reembolsos a clientes       580.0         0.00
47                                       Por litigios       581.0         0.00
48  Por pasivos contingentes asumidos en una combi...       582.0         0.00
49                                              Otras       583.0         0.00
51                              Anticipos de clientes       584.0         0.00
52                          Subvenciones del gobierno       585.0         0.00
53                                              Otros       586.0         0.00
55  Transferencias casa matriz y sucursales (del e...       587.0         0.00
56                                              Otros       588.0         0.00
57                        TOTAL PASIVOS NO CORRIENTES       589.0  12170910.40
58  Total de Intereses Implícitos No Debvengados (...       591.0         0.00
59  Pasivos incurridos en fideicomisos mercantiles...       592.0         0.00
60                                   TOTAL DEL PASIVO       599.0  30690903.00
62                      Capital Suscrito y/o Asignado       601.0  15582462.00
63  (-) Capital Suscrito No Pagado, Acciones en Te...       602.0         0.00
64  Aportes de Socios, Accionistas, Partícipes, Fu...       603.0         0.00
66                                      Reserva legal       604.0    911550.71
67                                Reserva facultativa       605.0         0.00
68                                              Otras       606.0    441163.10
70                                 Reserva de capital       607.0       500.00
71                             Reserva por donaciones       608.0         0.00
72  Reserva por valuación (procedente de la aplica...       609.0         0.00

In [53]:
texto.clear()
texto = df5["OTROS PASIVOS CORRIENTES"].to_list()
valores = np.array( df5["Unnamed: 2"].to_list() ).reshape(1,-1)
datosF5 = pd.DataFrame(valores, columns=texto)
datosF5

,Transferencias casa matriz y sucursales (del exterior),Otros,TOTAL PASIVOS CORRIENTES,Locales,Del exterior,Locales,Del exterior,Locales,Del exterior,Locales,...,TOTAL DEL PASIVO,Capital Suscrito y/o Asignado,"(-) Capital Suscrito No Pagado, Acciones en Tesorería","Aportes de Socios, Accionistas, Partícipes, Fundadores, Constituyentes, Beneficiarios U Otros Titulares De Derechos Representativos De Capital Para Futura Capitalización",Reserva legal,Reserva facultativa,Otras,Reserva de capital,Reserva por donaciones,Reserva por valuación (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC)
0,0.0,0.0,18519992.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,30690903.0,15582462.0,0.0,0.0,911550.71,0.0,441163.1,500.0,0.0,0.0

### Sexta hoja del pdf

In [54]:
sixth = tabula.read_pdf(pdfOriginal, pages=6, area=(21.05,6.12,916.86,605.88), lattice=False, output_format="dataframe", encoding="latin-1")
df6 = sixth[0]
df6

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),Unnamed: 1,Unnamed: 2,610,0.00
0,Utilidades acumuladas de ejercicios anteriores,NaN,NaN,611,6577.58
1,(-) Pérdidas acumuladas de ejercicios anteriores,NaN,NaN,612,135228.44
2,Excedente / pérdida del ejercicio anterior (co...,NaN,NaN,613,0.00
3,Resultados acumulados por adopción por primera...,NaN,NaN,614,-1129460.10
4,Utilidad del ejercicio,NaN,NaN,615,717804.24
...,...,...,...,...,...
68,Por litigios,6071,0.00,6072,0.00
69,Por pasivos contingentes asumidos en una combi...,6073,0.00,6074,0.00
70,Otras,6075,0.00,6076,0.00
71,GANANCIAS NETAS POR REVERSIONES DE PASIVOS POR...,Total ingresos,NaN,Valor exento / no objeto,NaN
72,Jubilación patronal y desahucio,6077,68394.75,6078,26040.53

In [55]:
df6.iloc[:50]

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),Unnamed: 1,Unnamed: 2,610,0.00
0,Utilidades acumuladas de ejercicios anteriores,NaN,NaN,611,6577.58
1,(-) Pérdidas acumuladas de ejercicios anteriores,NaN,NaN,612,135228.44
2,Excedente / pérdida del ejercicio anterior (co...,NaN,NaN,613,0.00
3,Resultados acumulados por adopción por primera...,NaN,NaN,614,-1129460.10
4,Utilidad del ejercicio,NaN,NaN,615,717804.24
5,Pérdida del ejercicio,NaN,NaN,616,0.00
6,Excedente / pérdida del ejercicio económico (c...,NaN,NaN,617,0.00
7,OTROS RESULTADOS INTEGRALES ACUMULADOS,NaN,NaN,NaN,NaN
8,SUPERÁVIT DE REVALUACIÓN ACUMULADO,NaN,NaN,NaN,NaN
9,"Propiedades, Planta y Equipo",NaN,NaN,618,276732.55
10,Activos intangibles,NaN,NaN,619,0.00
11,Otros,NaN,NaN,620,0.00
12,Ganancias y pérdidas acumuladas por inversione...,NaN,NaN,621,0.00
13,Ganancias y pérdidas acumuladas por la convers...,NaN,NaN,622,0.00
14,Ganancias y pérdidas actuariales acumuladas,NaN,NaN,623,103209.01
15,La parte efectiva de las ganancias y pérdidas ...,NaN,NaN,624,0.00
16,Otros,NaN,NaN,625,-4017755.30
17,Dividendos declarados (distribuidos) a favor d...,NaN,NaN,626,0.00
18,Dividendos pagados (liquidados) a titulares d...,NaN,NaN,627,0.00
19,TOTAL DEL PATRIMONIO,NaN,NaN,698,12757555.30
20,TOTAL PASIVO Y PATRIMONIO,NaN,NaN,699,43448458.30
21,ESTADO DEL RESULTADO INTEGRAL,NaN,NaN,NaN,NaN
22,INGRESOS,NaN,NaN,NaN,NaN
23,INGRESOS DE ACTIVIDADES ORDINARIAS,NaN,NaN,NaN,NaN
24,VENTAS LOCALES DE BIENES,Total ingresos,NaN,Valor exento / no objeto,NaN
25,Gravadas con tarifa diferente de 0% de IVA,6001,16866390.70,6002,0.00
26,Gravadas con tarifa 0% de iva o exentas de IVA,6003,0.00,6004,0.00
27,PRESTACIONES LOCALES DE SERVICIOS,Total ingresos,NaN,Valor exento / no objeto,NaN
28,Gravadas con tarifa diferente de 0% de IVA,6005,0.00,6006,0.00
29,Gravadas con tarifa 0% de iva o exentas de IVA,6007,0.00,6008,0.00
30,EXPORTACIONES NETAS (6009 - 6012),Total ingresos,NaN,Valor exento / no objeto,NaN
31,De bienes,6009,717418.93,6010,0.00
32,De servicios,6011,0.00,6012,0.00
33,Por prestación de servicios de construcción,6013,0.00,6014,0.00
34,Obtenidos bajo la modalidad de comisiones o si...,6015,0.00,6016,0.00
35,Obtenidos por arrendamientos operativos,6017,0.00,6018,0.00
36,TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS,1005,17583809.70,NaN,NaN
37,OTROS INGRESOS,NaN,NaN,NaN,NaN
38,POR REGALÍAS Y OTRAS CESIONES DE DERECHOS,Total ingresos,NaN,Valor exento / no objeto,NaN
39,Relacionadas,6019,0.00,6020,0.00
40,No Relacionadas,6021,0.00,6022,0.00
41,POR DIVIDENDOS,Total ingresos,NaN,Valor exento / no objeto,NaN
42,Procedentes de sociedades residentes o estable...,6023,0.00,6024,0.00
43,Procedentes de sociedades no residentes ni est...,6025,0.00,6026,0.00
44,Ganancias netas por mediciones de activos biol...,6027,0.00,6028,0.00
45,Ganancias netas por medición de propiedades de...,6029,0.00,6030,0.00
46,Ganancias netas por medición de instrumentos f...,6031,0.00,6032,0.00
47,Ganancias netas por diferencias de cambios,6033,0.00,6034,0.00
48,"Utilidad en venta de propiedades, planta y equipo",6035,53053.46,6036,0.00
49,Utilidad en la enajenación de derechos represe...,6037,0.00,6038,0.00

In [56]:
f6ESF = df6.iloc[:22].copy()

In [57]:
f6ESF

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),Unnamed: 1,Unnamed: 2,610,0.00
0,Utilidades acumuladas de ejercicios anteriores,NaN,NaN,611,6577.58
1,(-) Pérdidas acumuladas de ejercicios anteriores,NaN,NaN,612,135228.44
2,Excedente / pérdida del ejercicio anterior (co...,NaN,NaN,613,0.00
3,Resultados acumulados por adopción por primera...,NaN,NaN,614,-1129460.10
4,Utilidad del ejercicio,NaN,NaN,615,717804.24
5,Pérdida del ejercicio,NaN,NaN,616,0.00
6,Excedente / pérdida del ejercicio económico (c...,NaN,NaN,617,0.00
7,OTROS RESULTADOS INTEGRALES ACUMULADOS,NaN,NaN,NaN,NaN
8,SUPERÁVIT DE REVALUACIÓN ACUMULADO,NaN,NaN,NaN,NaN
9,"Propiedades, Planta y Equipo",NaN,NaN,618,276732.55
10,Activos intangibles,NaN,NaN,619,0.00
11,Otros,NaN,NaN,620,0.00
12,Ganancias y pérdidas acumuladas por inversione...,NaN,NaN,621,0.00
13,Ganancias y pérdidas acumuladas por la convers...,NaN,NaN,622,0.00
14,Ganancias y pérdidas actuariales acumuladas,NaN,NaN,623,103209.01
15,La parte efectiva de las ganancias y pérdidas ...,NaN,NaN,624,0.00
16,Otros,NaN,NaN,625,-4017755.30
17,Dividendos declarados (distribuidos) a favor d...,NaN,NaN,626,0.00
18,Dividendos pagados (liquidados) a titulares d...,NaN,NaN,627,0.00
19,TOTAL DEL PATRIMONIO,NaN,NaN,698,12757555.30
20,TOTAL PASIVO Y PATRIMONIO,NaN,NaN,699,43448458.30
21,ESTADO DEL RESULTADO INTEGRAL,NaN,NaN,NaN,NaN

In [58]:
f6ESF.drop([21], axis=0,inplace=True)
f6ESF

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),Unnamed: 1,Unnamed: 2,610,0.00
0,Utilidades acumuladas de ejercicios anteriores,NaN,NaN,611,6577.58
1,(-) Pérdidas acumuladas de ejercicios anteriores,NaN,NaN,612,135228.44
2,Excedente / pérdida del ejercicio anterior (co...,NaN,NaN,613,0.00
3,Resultados acumulados por adopción por primera...,NaN,NaN,614,-1129460.10
4,Utilidad del ejercicio,NaN,NaN,615,717804.24
5,Pérdida del ejercicio,NaN,NaN,616,0.00
6,Excedente / pérdida del ejercicio económico (c...,NaN,NaN,617,0.00
7,OTROS RESULTADOS INTEGRALES ACUMULADOS,NaN,NaN,NaN,NaN
8,SUPERÁVIT DE REVALUACIÓN ACUMULADO,NaN,NaN,NaN,NaN
9,"Propiedades, Planta y Equipo",NaN,NaN,618,276732.55
10,Activos intangibles,NaN,NaN,619,0.00
11,Otros,NaN,NaN,620,0.00
12,Ganancias y pérdidas acumuladas por inversione...,NaN,NaN,621,0.00
13,Ganancias y pérdidas acumuladas por la convers...,NaN,NaN,622,0.00
14,Ganancias y pérdidas actuariales acumuladas,NaN,NaN,623,103209.01
15,La parte efectiva de las ganancias y pérdidas ...,NaN,NaN,624,0.00
16,Otros,NaN,NaN,625,-4017755.30
17,Dividendos declarados (distribuidos) a favor d...,NaN,NaN,626,0.00
18,Dividendos pagados (liquidados) a titulares d...,NaN,NaN,627,0.00
19,TOTAL DEL PATRIMONIO,NaN,NaN,698,12757555.30
20,TOTAL PASIVO Y PATRIMONIO,NaN,NaN,699,43448458.30

In [59]:
f6ESF.drop(["Unnamed: 1","Unnamed: 2"], axis=1, inplace=True)
f6ESF

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),610,0.00
0,Utilidades acumuladas de ejercicios anteriores,611,6577.58
1,(-) Pérdidas acumuladas de ejercicios anteriores,612,135228.44
2,Excedente / pérdida del ejercicio anterior (co...,613,0.00
3,Resultados acumulados por adopción por primera...,614,-1129460.10
4,Utilidad del ejercicio,615,717804.24
5,Pérdida del ejercicio,616,0.00
6,Excedente / pérdida del ejercicio económico (c...,617,0.00
7,OTROS RESULTADOS INTEGRALES ACUMULADOS,NaN,NaN
8,SUPERÁVIT DE REVALUACIÓN ACUMULADO,NaN,NaN
9,"Propiedades, Planta y Equipo",618,276732.55
10,Activos intangibles,619,0.00
11,Otros,620,0.00
12,Ganancias y pérdidas acumuladas por inversione...,621,0.00
13,Ganancias y pérdidas acumuladas por la convers...,622,0.00
14,Ganancias y pérdidas actuariales acumuladas,623,103209.01
15,La parte efectiva de las ganancias y pérdidas ...,624,0.00
16,Otros,625,-4017755.30
17,Dividendos declarados (distribuidos) a favor d...,626,0.00
18,Dividendos pagados (liquidados) a titulares d...,627,0.00
19,TOTAL DEL PATRIMONIO,698,12757555.30
20,TOTAL PASIVO Y PATRIMONIO,699,43448458.30

In [60]:
newFirstRow = pd.DataFrame([f6ESF.columns.to_list()], columns=f6ESF.columns)
newFirstRow

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),610,0.00
0,Superávit por revaluación de inversiones (proc...,610,0.00

In [61]:
dataframe6 = pd.concat([newFirstRow, f6ESF])
dataframe6

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),610,0.00
0,Superávit por revaluación de inversiones (proc...,610,0.00
0,Utilidades acumuladas de ejercicios anteriores,611,6577.58
1,(-) Pérdidas acumuladas de ejercicios anteriores,612,135228.44
2,Excedente / pérdida del ejercicio anterior (co...,613,0.0
3,Resultados acumulados por adopción por primera...,614,-1129460.1
4,Utilidad del ejercicio,615,717804.24
5,Pérdida del ejercicio,616,0.0
6,Excedente / pérdida del ejercicio económico (c...,617,0.0
7,OTROS RESULTADOS INTEGRALES ACUMULADOS,NaN,NaN
8,SUPERÁVIT DE REVALUACIÓN ACUMULADO,NaN,NaN
9,"Propiedades, Planta y Equipo",618,276732.55
10,Activos intangibles,619,0.0
11,Otros,620,0.0
12,Ganancias y pérdidas acumuladas por inversione...,621,0.0
13,Ganancias y pérdidas acumuladas por la convers...,622,0.0
14,Ganancias y pérdidas actuariales acumuladas,623,103209.01
15,La parte efectiva de las ganancias y pérdidas ...,624,0.0
16,Otros,625,-4017755.3
17,Dividendos declarados (distribuidos) a favor d...,626,0.0
18,Dividendos pagados (liquidados) a titulares d...,627,0.0
19,TOTAL DEL PATRIMONIO,698,12757555.3
20,TOTAL PASIVO Y PATRIMONIO,699,43448458.3

In [62]:
dataframe6

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),610,0.00
0,Superávit por revaluación de inversiones (proc...,610,0.00
0,Utilidades acumuladas de ejercicios anteriores,611,6577.58
1,(-) Pérdidas acumuladas de ejercicios anteriores,612,135228.44
2,Excedente / pérdida del ejercicio anterior (co...,613,0.0
3,Resultados acumulados por adopción por primera...,614,-1129460.1
4,Utilidad del ejercicio,615,717804.24
5,Pérdida del ejercicio,616,0.0
6,Excedente / pérdida del ejercicio económico (c...,617,0.0
7,OTROS RESULTADOS INTEGRALES ACUMULADOS,NaN,NaN
8,SUPERÁVIT DE REVALUACIÓN ACUMULADO,NaN,NaN
9,"Propiedades, Planta y Equipo",618,276732.55
10,Activos intangibles,619,0.0
11,Otros,620,0.0
12,Ganancias y pérdidas acumuladas por inversione...,621,0.0
13,Ganancias y pérdidas acumuladas por la convers...,622,0.0
14,Ganancias y pérdidas actuariales acumuladas,623,103209.01
15,La parte efectiva de las ganancias y pérdidas ...,624,0.0
16,Otros,625,-4017755.3
17,Dividendos declarados (distribuidos) a favor d...,626,0.0
18,Dividendos pagados (liquidados) a titulares d...,627,0.0
19,TOTAL DEL PATRIMONIO,698,12757555.3
20,TOTAL PASIVO Y PATRIMONIO,699,43448458.3

In [63]:
texto.clear()
texto = dataframe6["Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC)"].to_list()
valores = np.array( dataframe6["0.00"].to_list() ).reshape(1,-1)
datosF6_1 = pd.DataFrame(valores, columns=texto)
datosF6_1

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),Utilidades acumuladas de ejercicios anteriores,(-) Pérdidas acumuladas de ejercicios anteriores,Excedente / pérdida del ejercicio anterior (con socios),Resultados acumulados por adopción por primera vez de las NIIF,Utilidad del ejercicio,Pérdida del ejercicio,Excedente / pérdida del ejercicio económico (con socios),OTROS RESULTADOS INTEGRALES ACUMULADOS,SUPERÁVIT DE REVALUACIÓN ACUMULADO,...,Otros,Ganancias y pérdidas acumuladas por inversiones en instrumentos de patrimonio medidos a valor razonable con cambios en otro resultado integral,Ganancias y pérdidas acumuladas por la conversión de estados financieros de un negocio en el extranjero,Ganancias y pérdidas actuariales acumuladas,La parte efectiva de las ganancias y pérdidas de los instrumentos de cobertura en una cobertura de flujos de efectivo,Otros,Dividendos declarados (distribuidos) a favor de titulares de derechos representativos de capital en el ejercicio fiscal (Informativo),Dividendos pagados (liquidados) a titulares de derechos representativos de capital en el ejercicio fiscal (Informativo),TOTAL DEL PATRIMONIO,TOTAL PASIVO Y PATRIMONIO
0,0.00,6577.58,135228.44,0.0,-1129460.1,717804.24,0.0,0.0,nan,nan,...,0.0,0.0,0.0,103209.01,0.0,-4017755.3,0.0,0.0,12757555.3,43448458.3

In [64]:
#AHORA HOJA 6 PERO CON EL ESTADO DE RESULTADO INTEGRAL
df6ERI = df6.drop( df6.index[0:21])
df6ERI

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),Unnamed: 1,Unnamed: 2,610,0.00
21,ESTADO DEL RESULTADO INTEGRAL,NaN,NaN,NaN,NaN
22,INGRESOS,NaN,NaN,NaN,NaN
23,INGRESOS DE ACTIVIDADES ORDINARIAS,NaN,NaN,NaN,NaN
24,VENTAS LOCALES DE BIENES,Total ingresos,NaN,Valor exento / no objeto,NaN
25,Gravadas con tarifa diferente de 0% de IVA,6001,16866390.70,6002,0.00
26,Gravadas con tarifa 0% de iva o exentas de IVA,6003,0.00,6004,0.00
27,PRESTACIONES LOCALES DE SERVICIOS,Total ingresos,NaN,Valor exento / no objeto,NaN
28,Gravadas con tarifa diferente de 0% de IVA,6005,0.00,6006,0.00
29,Gravadas con tarifa 0% de iva o exentas de IVA,6007,0.00,6008,0.00
30,EXPORTACIONES NETAS (6009 - 6012),Total ingresos,NaN,Valor exento / no objeto,NaN
31,De bienes,6009,717418.93,6010,0.00
32,De servicios,6011,0.00,6012,0.00
33,Por prestación de servicios de construcción,6013,0.00,6014,0.00
34,Obtenidos bajo la modalidad de comisiones o si...,6015,0.00,6016,0.00
35,Obtenidos por arrendamientos operativos,6017,0.00,6018,0.00
36,TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS,1005,17583809.70,NaN,NaN
37,OTROS INGRESOS,NaN,NaN,NaN,NaN
38,POR REGALÍAS Y OTRAS CESIONES DE DERECHOS,Total ingresos,NaN,Valor exento / no objeto,NaN
39,Relacionadas,6019,0.00,6020,0.00
40,No Relacionadas,6021,0.00,6022,0.00
41,POR DIVIDENDOS,Total ingresos,NaN,Valor exento / no objeto,NaN
42,Procedentes de sociedades residentes o estable...,6023,0.00,6024,0.00
43,Procedentes de sociedades no residentes ni est...,6025,0.00,6026,0.00
44,Ganancias netas por mediciones de activos biol...,6027,0.00,6028,0.00
45,Ganancias netas por medición de propiedades de...,6029,0.00,6030,0.00
46,Ganancias netas por medición de instrumentos f...,6031,0.00,6032,0.00
47,Ganancias netas por diferencias de cambios,6033,0.00,6034,0.00
48,"Utilidad en venta de propiedades, planta y equipo",6035,53053.46,6036,0.00
49,Utilidad en la enajenación de derechos represe...,6037,0.00,6038,0.00
50,Ingresos devengados por subvenciones del gobie...,6039,0.00,6040,0.00
51,GANANCIAS NETAS POR REVERSIONES DE DETERIORO E...,Total ingresos,NaN,Valor exento / no objeto,NaN
52,De activos financieros (reversión de provision...,6041,0.00,6042,0.00
53,De inventarios,6043,0.00,6044,0.00
54,De activos no corrientes mantenidos para la venta,6045,0.00,6046,0.00
55,De activos biológicos,6047,0.00,6048,0.00
56,"De propiedades, planta y equipo",6049,0.00,6050,0.00
57,De activos intangibles,6051,0.00,6052,0.00
58,De propiedades de inversión,6053,0.00,6054,0.00
59,"De activos de exploración, evaluación y explot...",6055,0.00,6056,0.00
60,De inversiones no corrientes,6057,0.00,6058,0.00
61,Otras,6059,0.00,6060,0.00
62,GANANCIAS NETAS POR REVERSIONES DE PROVISIONES,Total ingresos,NaN,Valor exento / no objeto,NaN
63,Por garantías,6061,0.00,6062,0.00
64,Por desmantelamientos,6063,0.00,6064,0.00
65,Por contratos onerosos,6065,0.00,6066,0.00
66,Por reestructuraciones de negocios,6067,0.00,6068,0.00
67,Por reembolsos a clientes,6069,0.00,6070,0.00
68,Por litigios,6071,0.00,6072,0.00
69,Por pasivos contingentes asumidos en una combi...,6073,0.00,6074,0.00
70,Otras,6075,0.00,6076,0.00
71,GANANCIAS NETAS POR REVERSIONES DE PASIVOS POR...,Total ingresos,NaN,Valor exento / no objeto,NaN
72,Jubilación patronal y desahucio,6077,68394.75,6078,26040.53

In [65]:
df6ERI.reset_index(drop=True, inplace=True)
df6ERI

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),Unnamed: 1,Unnamed: 2,610,0.00
0,ESTADO DEL RESULTADO INTEGRAL,NaN,NaN,NaN,NaN
1,INGRESOS,NaN,NaN,NaN,NaN
2,INGRESOS DE ACTIVIDADES ORDINARIAS,NaN,NaN,NaN,NaN
3,VENTAS LOCALES DE BIENES,Total ingresos,NaN,Valor exento / no objeto,NaN
4,Gravadas con tarifa diferente de 0% de IVA,6001,16866390.70,6002,0.00
5,Gravadas con tarifa 0% de iva o exentas de IVA,6003,0.00,6004,0.00
6,PRESTACIONES LOCALES DE SERVICIOS,Total ingresos,NaN,Valor exento / no objeto,NaN
7,Gravadas con tarifa diferente de 0% de IVA,6005,0.00,6006,0.00
8,Gravadas con tarifa 0% de iva o exentas de IVA,6007,0.00,6008,0.00
9,EXPORTACIONES NETAS (6009 - 6012),Total ingresos,NaN,Valor exento / no objeto,NaN
10,De bienes,6009,717418.93,6010,0.00
11,De servicios,6011,0.00,6012,0.00
12,Por prestación de servicios de construcción,6013,0.00,6014,0.00
13,Obtenidos bajo la modalidad de comisiones o si...,6015,0.00,6016,0.00
14,Obtenidos por arrendamientos operativos,6017,0.00,6018,0.00
15,TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS,1005,17583809.70,NaN,NaN
16,OTROS INGRESOS,NaN,NaN,NaN,NaN
17,POR REGALÍAS Y OTRAS CESIONES DE DERECHOS,Total ingresos,NaN,Valor exento / no objeto,NaN
18,Relacionadas,6019,0.00,6020,0.00
19,No Relacionadas,6021,0.00,6022,0.00
20,POR DIVIDENDOS,Total ingresos,NaN,Valor exento / no objeto,NaN
21,Procedentes de sociedades residentes o estable...,6023,0.00,6024,0.00
22,Procedentes de sociedades no residentes ni est...,6025,0.00,6026,0.00
23,Ganancias netas por mediciones de activos biol...,6027,0.00,6028,0.00
24,Ganancias netas por medición de propiedades de...,6029,0.00,6030,0.00
25,Ganancias netas por medición de instrumentos f...,6031,0.00,6032,0.00
26,Ganancias netas por diferencias de cambios,6033,0.00,6034,0.00
27,"Utilidad en venta de propiedades, planta y equipo",6035,53053.46,6036,0.00
28,Utilidad en la enajenación de derechos represe...,6037,0.00,6038,0.00
29,Ingresos devengados por subvenciones del gobie...,6039,0.00,6040,0.00
30,GANANCIAS NETAS POR REVERSIONES DE DETERIORO E...,Total ingresos,NaN,Valor exento / no objeto,NaN
31,De activos financieros (reversión de provision...,6041,0.00,6042,0.00
32,De inventarios,6043,0.00,6044,0.00
33,De activos no corrientes mantenidos para la venta,6045,0.00,6046,0.00
34,De activos biológicos,6047,0.00,6048,0.00
35,"De propiedades, planta y equipo",6049,0.00,6050,0.00
36,De activos intangibles,6051,0.00,6052,0.00
37,De propiedades de inversión,6053,0.00,6054,0.00
38,"De activos de exploración, evaluación y explot...",6055,0.00,6056,0.00
39,De inversiones no corrientes,6057,0.00,6058,0.00
40,Otras,6059,0.00,6060,0.00
41,GANANCIAS NETAS POR REVERSIONES DE PROVISIONES,Total ingresos,NaN,Valor exento / no objeto,NaN
42,Por garantías,6061,0.00,6062,0.00
43,Por desmantelamientos,6063,0.00,6064,0.00
44,Por contratos onerosos,6065,0.00,6066,0.00
45,Por reestructuraciones de negocios,6067,0.00,6068,0.00
46,Por reembolsos a clientes,6069,0.00,6070,0.00
47,Por litigios,6071,0.00,6072,0.00
48,Por pasivos contingentes asumidos en una combi...,6073,0.00,6074,0.00
49,Otras,6075,0.00,6076,0.00
50,GANANCIAS NETAS POR REVERSIONES DE PASIVOS POR...,Total ingresos,NaN,Valor exento / no objeto,NaN
51,Jubilación patronal y desahucio,6077,68394.75,6078,26040.53

In [66]:
df6ERI.drop( df6ERI.index[0:3], inplace=True)
df6ERI

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),Unnamed: 1,Unnamed: 2,610,0.00
3,VENTAS LOCALES DE BIENES,Total ingresos,NaN,Valor exento / no objeto,NaN
4,Gravadas con tarifa diferente de 0% de IVA,6001,16866390.70,6002,0.00
5,Gravadas con tarifa 0% de iva o exentas de IVA,6003,0.00,6004,0.00
6,PRESTACIONES LOCALES DE SERVICIOS,Total ingresos,NaN,Valor exento / no objeto,NaN
7,Gravadas con tarifa diferente de 0% de IVA,6005,0.00,6006,0.00
8,Gravadas con tarifa 0% de iva o exentas de IVA,6007,0.00,6008,0.00
9,EXPORTACIONES NETAS (6009 - 6012),Total ingresos,NaN,Valor exento / no objeto,NaN
10,De bienes,6009,717418.93,6010,0.00
11,De servicios,6011,0.00,6012,0.00
12,Por prestación de servicios de construcción,6013,0.00,6014,0.00
13,Obtenidos bajo la modalidad de comisiones o si...,6015,0.00,6016,0.00
14,Obtenidos por arrendamientos operativos,6017,0.00,6018,0.00
15,TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS,1005,17583809.70,NaN,NaN
16,OTROS INGRESOS,NaN,NaN,NaN,NaN
17,POR REGALÍAS Y OTRAS CESIONES DE DERECHOS,Total ingresos,NaN,Valor exento / no objeto,NaN
18,Relacionadas,6019,0.00,6020,0.00
19,No Relacionadas,6021,0.00,6022,0.00
20,POR DIVIDENDOS,Total ingresos,NaN,Valor exento / no objeto,NaN
21,Procedentes de sociedades residentes o estable...,6023,0.00,6024,0.00
22,Procedentes de sociedades no residentes ni est...,6025,0.00,6026,0.00
23,Ganancias netas por mediciones de activos biol...,6027,0.00,6028,0.00
24,Ganancias netas por medición de propiedades de...,6029,0.00,6030,0.00
25,Ganancias netas por medición de instrumentos f...,6031,0.00,6032,0.00
26,Ganancias netas por diferencias de cambios,6033,0.00,6034,0.00
27,"Utilidad en venta de propiedades, planta y equipo",6035,53053.46,6036,0.00
28,Utilidad en la enajenación de derechos represe...,6037,0.00,6038,0.00
29,Ingresos devengados por subvenciones del gobie...,6039,0.00,6040,0.00
30,GANANCIAS NETAS POR REVERSIONES DE DETERIORO E...,Total ingresos,NaN,Valor exento / no objeto,NaN
31,De activos financieros (reversión de provision...,6041,0.00,6042,0.00
32,De inventarios,6043,0.00,6044,0.00
33,De activos no corrientes mantenidos para la venta,6045,0.00,6046,0.00
34,De activos biológicos,6047,0.00,6048,0.00
35,"De propiedades, planta y equipo",6049,0.00,6050,0.00
36,De activos intangibles,6051,0.00,6052,0.00
37,De propiedades de inversión,6053,0.00,6054,0.00
38,"De activos de exploración, evaluación y explot...",6055,0.00,6056,0.00
39,De inversiones no corrientes,6057,0.00,6058,0.00
40,Otras,6059,0.00,6060,0.00
41,GANANCIAS NETAS POR REVERSIONES DE PROVISIONES,Total ingresos,NaN,Valor exento / no objeto,NaN
42,Por garantías,6061,0.00,6062,0.00
43,Por desmantelamientos,6063,0.00,6064,0.00
44,Por contratos onerosos,6065,0.00,6066,0.00
45,Por reestructuraciones de negocios,6067,0.00,6068,0.00
46,Por reembolsos a clientes,6069,0.00,6070,0.00
47,Por litigios,6071,0.00,6072,0.00
48,Por pasivos contingentes asumidos en una combi...,6073,0.00,6074,0.00
49,Otras,6075,0.00,6076,0.00
50,GANANCIAS NETAS POR REVERSIONES DE PASIVOS POR...,Total ingresos,NaN,Valor exento / no objeto,NaN
51,Jubilación patronal y desahucio,6077,68394.75,6078,26040.53

In [67]:
indexCurrencyNull = df6ERI[ (df6ERI["Unnamed: 2"].isna()) & (df6ERI["0.00"].isna()) ].index
df6ERI.drop(indexCurrencyNull, inplace=True)
df6ERI

,Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC),Unnamed: 1,Unnamed: 2,610,0.00
4,Gravadas con tarifa diferente de 0% de IVA,6001,16866390.70,6002,0.00
5,Gravadas con tarifa 0% de iva o exentas de IVA,6003,0.00,6004,0.00
7,Gravadas con tarifa diferente de 0% de IVA,6005,0.00,6006,0.00
8,Gravadas con tarifa 0% de iva o exentas de IVA,6007,0.00,6008,0.00
10,De bienes,6009,717418.93,6010,0.00
11,De servicios,6011,0.00,6012,0.00
12,Por prestación de servicios de construcción,6013,0.00,6014,0.00
13,Obtenidos bajo la modalidad de comisiones o si...,6015,0.00,6016,0.00
14,Obtenidos por arrendamientos operativos,6017,0.00,6018,0.00
15,TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS,1005,17583809.70,NaN,NaN
18,Relacionadas,6019,0.00,6020,0.00
19,No Relacionadas,6021,0.00,6022,0.00
21,Procedentes de sociedades residentes o estable...,6023,0.00,6024,0.00
22,Procedentes de sociedades no residentes ni est...,6025,0.00,6026,0.00
23,Ganancias netas por mediciones de activos biol...,6027,0.00,6028,0.00
24,Ganancias netas por medición de propiedades de...,6029,0.00,6030,0.00
25,Ganancias netas por medición de instrumentos f...,6031,0.00,6032,0.00
26,Ganancias netas por diferencias de cambios,6033,0.00,6034,0.00
27,"Utilidad en venta de propiedades, planta y equipo",6035,53053.46,6036,0.00
28,Utilidad en la enajenación de derechos represe...,6037,0.00,6038,0.00
29,Ingresos devengados por subvenciones del gobie...,6039,0.00,6040,0.00
31,De activos financieros (reversión de provision...,6041,0.00,6042,0.00
32,De inventarios,6043,0.00,6044,0.00
33,De activos no corrientes mantenidos para la venta,6045,0.00,6046,0.00
34,De activos biológicos,6047,0.00,6048,0.00
35,"De propiedades, planta y equipo",6049,0.00,6050,0.00
36,De activos intangibles,6051,0.00,6052,0.00
37,De propiedades de inversión,6053,0.00,6054,0.00
38,"De activos de exploración, evaluación y explot...",6055,0.00,6056,0.00
39,De inversiones no corrientes,6057,0.00,6058,0.00
40,Otras,6059,0.00,6060,0.00
42,Por garantías,6061,0.00,6062,0.00
43,Por desmantelamientos,6063,0.00,6064,0.00
44,Por contratos onerosos,6065,0.00,6066,0.00
45,Por reestructuraciones de negocios,6067,0.00,6068,0.00
46,Por reembolsos a clientes,6069,0.00,6070,0.00
47,Por litigios,6071,0.00,6072,0.00
48,Por pasivos contingentes asumidos en una combi...,6073,0.00,6074,0.00
49,Otras,6075,0.00,6076,0.00
51,Jubilación patronal y desahucio,6077,68394.75,6078,26040.53

In [68]:
df6ERI.rename(inplace=True, columns={"Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC)":"CUENTA",
                                "Unnamed: 1":"Total ingresos", "Unnamed: 2":"USD 1" ,"610":"Valor exento / no objeto", "0.00":"USD2"})
df6ERI

,CUENTA,Total ingresos,USD 1,Valor exento / no objeto,USD2
4,Gravadas con tarifa diferente de 0% de IVA,6001,16866390.70,6002,0.00
5,Gravadas con tarifa 0% de iva o exentas de IVA,6003,0.00,6004,0.00
7,Gravadas con tarifa diferente de 0% de IVA,6005,0.00,6006,0.00
8,Gravadas con tarifa 0% de iva o exentas de IVA,6007,0.00,6008,0.00
10,De bienes,6009,717418.93,6010,0.00
11,De servicios,6011,0.00,6012,0.00
12,Por prestación de servicios de construcción,6013,0.00,6014,0.00
13,Obtenidos bajo la modalidad de comisiones o si...,6015,0.00,6016,0.00
14,Obtenidos por arrendamientos operativos,6017,0.00,6018,0.00
15,TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS,1005,17583809.70,NaN,NaN
18,Relacionadas,6019,0.00,6020,0.00
19,No Relacionadas,6021,0.00,6022,0.00
21,Procedentes de sociedades residentes o estable...,6023,0.00,6024,0.00
22,Procedentes de sociedades no residentes ni est...,6025,0.00,6026,0.00
23,Ganancias netas por mediciones de activos biol...,6027,0.00,6028,0.00
24,Ganancias netas por medición de propiedades de...,6029,0.00,6030,0.00
25,Ganancias netas por medición de instrumentos f...,6031,0.00,6032,0.00
26,Ganancias netas por diferencias de cambios,6033,0.00,6034,0.00
27,"Utilidad en venta de propiedades, planta y equipo",6035,53053.46,6036,0.00
28,Utilidad en la enajenación de derechos represe...,6037,0.00,6038,0.00
29,Ingresos devengados por subvenciones del gobie...,6039,0.00,6040,0.00
31,De activos financieros (reversión de provision...,6041,0.00,6042,0.00
32,De inventarios,6043,0.00,6044,0.00
33,De activos no corrientes mantenidos para la venta,6045,0.00,6046,0.00
34,De activos biológicos,6047,0.00,6048,0.00
35,"De propiedades, planta y equipo",6049,0.00,6050,0.00
36,De activos intangibles,6051,0.00,6052,0.00
37,De propiedades de inversión,6053,0.00,6054,0.00
38,"De activos de exploración, evaluación y explot...",6055,0.00,6056,0.00
39,De inversiones no corrientes,6057,0.00,6058,0.00
40,Otras,6059,0.00,6060,0.00
42,Por garantías,6061,0.00,6062,0.00
43,Por desmantelamientos,6063,0.00,6064,0.00
44,Por contratos onerosos,6065,0.00,6066,0.00
45,Por reestructuraciones de negocios,6067,0.00,6068,0.00
46,Por reembolsos a clientes,6069,0.00,6070,0.00
47,Por litigios,6071,0.00,6072,0.00
48,Por pasivos contingentes asumidos en una combi...,6073,0.00,6074,0.00
49,Otras,6075,0.00,6076,0.00
51,Jubilación patronal y desahucio,6077,68394.75,6078,26040.53

In [69]:
columnsToAppend = df6ERI.columns.to_list()
print(columnsToAppend)

['CUENTA', 'Total ingresos', 'USD 1', 'Valor exento / no objeto', 'USD2']

In [70]:
columnsToAppend.remove("CUENTA");  columnsToAppend.remove("USD 1");  columnsToAppend.remove("USD2"); 
print(columnsToAppend)

['Total ingresos', 'Valor exento / no objeto']

In [71]:
extendedCuentaValues = df6ERI["CUENTA"].to_list()
print(extendedCuentaValues)

['Gravadas con tarifa diferente de 0% de IVA', 'Gravadas con tarifa 0% de iva o exentas de IVA', 'Gravadas con tarifa diferente de 0% de IVA', 'Gravadas con tarifa 0% de iva o exentas de IVA', 'De bienes', 'De servicios', 'Por prestación de servicios de construcción', 'Obtenidos bajo la modalidad de comisiones o similares (relaciones de agencia)', 'Obtenidos por arrendamientos operativos', 'TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS', 'Relacionadas', 'No Relacionadas', 'Procedentes de sociedades residentes o establecidas en Ecuador', 'Procedentes de sociedades no residentes ni establecidas en Ecuador', 'Ganancias netas por mediciones de activos biológicos a valor razonable menos costos de venta', 'Ganancias netas por medición de propiedades de inversión a valor razonable', 'Ganancias netas por medición de instrumentos financieros a valor razonable', 'Ganancias netas por diferencias de cambios', 'Utilidad en venta de propiedades, planta y equipo', 'Utilidad en la enajenación de derechos representativos de capital', 'Ingresos devengados por subvenciones del gobierno y otras ayudas gubernamentales', 'De activos financieros (reversión de provisiones para créditos incobrables)', 'De inventarios', 'De activos no corrientes mantenidos para la venta', 'De activos biológicos', 'De propiedades, planta y equipo', 'De activos intangibles', 'De propiedades de inversión', 'De activos de exploración, evaluación y explotación de recursos minerales', 'De inversiones no corrientes', 'Otras', 'Por garantías', 'Por desmantelamientos', 'Por contratos onerosos', 'Por reestructuraciones de negocios', 'Por reembolsos a clientes', 'Por litigios', 'Por pasivos contingentes asumidos en una combinación de negocios', 'Otras', 'Jubilación patronal y desahucio']

In [72]:
extendedCuentaValuesLENGHT = len(extendedCuentaValues)
#for i in range(len(columnsToAppend)):
#    for k in range(extendedCuentaValues):
#        extendedCuentaValues.insert(k+1, extendedCuentaValues[k] +" "+columnsToAppend[i] )
extended_values = []

for cuenta_value in extendedCuentaValues:
    for column_to_append in columnsToAppend:
        extended_values.append(cuenta_value + " " + column_to_append)

print(extended_values)
"""
#AÑADIMOS EL ELEMENTO REPETIDO
for k in range(extendedCuentaValuesLENGHT) :
    extendedCuentaValues.insert(k+1, extendedCuentaValues[k])

#AÑADIMOS EL TOTAL INGRESOS O VALOR EXENTO SEGÚN CORRESPONDA
for extended, cuenta in zip(range(extendedCuentaValuesLENGHT), range(len(columnsToAppend)) ):
    extendedCuentaValues[extended] = extendedCuentaValues[extended] + " " + columnsToAppend[cuenta]
"""

['Gravadas con tarifa diferente de 0% de IVA Total ingresos', 'Gravadas con tarifa diferente de 0% de IVA Valor exento / no objeto', 'Gravadas con tarifa 0% de iva o exentas de IVA Total ingresos', 'Gravadas con tarifa 0% de iva o exentas de IVA Valor exento / no objeto', 'Gravadas con tarifa diferente de 0% de IVA Total ingresos', 'Gravadas con tarifa diferente de 0% de IVA Valor exento / no objeto', 'Gravadas con tarifa 0% de iva o exentas de IVA Total ingresos', 'Gravadas con tarifa 0% de iva o exentas de IVA Valor exento / no objeto', 'De bienes Total ingresos', 'De bienes Valor exento / no objeto', 'De servicios Total ingresos', 'De servicios Valor exento / no objeto', 'Por prestación de servicios de construcción Total ingresos', 'Por prestación de servicios de construcción Valor exento / no objeto', 'Obtenidos bajo la modalidad de comisiones o similares (relaciones de agencia) Total ingresos', 'Obtenidos bajo la modalidad de comisiones o similares (relaciones de agencia) Valor exento / no objeto', 'Obtenidos por arrendamientos operativos Total ingresos', 'Obtenidos por arrendamientos operativos Valor exento / no objeto', 'TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS Total ingresos', 'TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS Valor exento / no objeto', 'Relacionadas Total ingresos', 'Relacionadas Valor exento / no objeto', 'No Relacionadas Total ingresos', 'No Relacionadas Valor exento / no objeto', 'Procedentes de sociedades residentes o establecidas en Ecuador Total ingresos', 'Procedentes de sociedades residentes o establecidas en Ecuador Valor exento / no objeto', 'Procedentes de sociedades no residentes ni establecidas en Ecuador Total ingresos', 'Procedentes de sociedades no residentes ni establecidas en Ecuador Valor exento / no objeto', 'Ganancias netas por mediciones de activos biológicos a valor razonable menos costos de venta Total ingresos', 'Ganancias netas por mediciones de activos biológicos a valor razonable menos costos de venta Valor exento / no objeto', 'Ganancias netas por medición de propiedades de inversión a valor razonable Total ingresos', 'Ganancias netas por medición de propiedades de inversión a valor razonable Valor exento / no objeto', 'Ganancias netas por medición de instrumentos financieros a valor razonable Total ingresos', 'Ganancias netas por medición de instrumentos financieros a valor razonable Valor exento / no objeto', 'Ganancias netas por diferencias de cambios Total ingresos', 'Ganancias netas por diferencias de cambios Valor exento / no objeto', 'Utilidad en venta de propiedades, planta y equipo Total ingresos', 'Utilidad en venta de propiedades, planta y equipo Valor exento / no objeto', 'Utilidad en la enajenación de derechos representativos de capital Total ingresos', 'Utilidad en la enajenación de derechos representativos de capital Valor exento / no objeto', 'Ingresos devengados por subvenciones del gobierno y otras ayudas gubernamentales Total ingresos', 'Ingresos devengados por subvenciones del gobierno y otras ayudas gubernamentales Valor exento / no objeto', 'De activos financieros (reversión de provisiones para créditos incobrables) Total ingresos', 'De activos financieros (reversión de provisiones para créditos incobrables) Valor exento / no objeto', 'De inventarios Total ingresos', 'De inventarios Valor exento / no objeto', 'De activos no corrientes mantenidos para la venta Total ingresos', 'De activos no corrientes mantenidos para la venta Valor exento / no objeto', 'De activos biológicos Total ingresos', 'De activos biológicos Valor exento / no objeto', 'De propiedades, planta y equipo Total ingresos', 'De propiedades, planta y equipo Valor exento / no objeto', 'De activos intangibles Total ingresos', 'De activos intangibles Valor exento / no objeto', 'De propiedades de inversión Total ingresos', 'De propiedades de inversión Valor exento / no objeto', 'De activos de exploración, evaluación y explotación de recursos minerales Total ingresos', 'De activos de exploración, evaluación y explotación de recursos minerales Valor exento / no objeto', 'De inversiones no corrientes Total ingresos', 'De inversiones no corrientes Valor exento / no objeto', 'Otras Total ingresos', 'Otras Valor exento / no objeto', 'Por garantías Total ingresos', 'Por garantías Valor exento / no objeto', 'Por desmantelamientos Total ingresos', 'Por desmantelamientos Valor exento / no objeto', 'Por contratos onerosos Total ingresos', 'Por contratos onerosos Valor exento / no objeto', 'Por reestructuraciones de negocios Total ingresos', 'Por reestructuraciones de negocios Valor exento / no objeto', 'Por reembolsos a clientes Total ingresos', 'Por reembolsos a clientes Valor exento / no objeto', 'Por litigios Total ingresos', 'Por litigios Valor exento / no objeto', 'Por pasivos contingentes asumidos en una combinación de negocios Total ingresos', 'Por pasivos contingentes asumidos en una combinación de negocios Valor exento / no objeto', 'Otras Total ingresos', 'Otras Valor exento / no objeto', 'Jubilación patronal y desahucio Total ingresos', 'Jubilación patronal y desahucio Valor exento / no objeto']

'\n#AÑADIMOS EL ELEMENTO REPETIDO\nfor k in range(extendedCuentaValuesLENGHT) :\n    extendedCuentaValues.insert(k+1, extendedCuentaValues[k])\n\n#AÑADIMOS EL TOTAL INGRESOS O VALOR EXENTO SEGÚN CORRESPONDA\nfor extended, cuenta in zip(range(extendedCuentaValuesLENGHT), range(len(columnsToAppend)) ):\n    extendedCuentaValues[extended] = extendedCuentaValues[extended] + " " + columnsToAppend[cuenta]\n'

In [73]:
df6ERI.reset_index(drop=True, inplace=True)
df6ERI

,CUENTA,Total ingresos,USD 1,Valor exento / no objeto,USD2
0,Gravadas con tarifa diferente de 0% de IVA,6001,16866390.70,6002,0.00
1,Gravadas con tarifa 0% de iva o exentas de IVA,6003,0.00,6004,0.00
2,Gravadas con tarifa diferente de 0% de IVA,6005,0.00,6006,0.00
3,Gravadas con tarifa 0% de iva o exentas de IVA,6007,0.00,6008,0.00
4,De bienes,6009,717418.93,6010,0.00
5,De servicios,6011,0.00,6012,0.00
6,Por prestación de servicios de construcción,6013,0.00,6014,0.00
7,Obtenidos bajo la modalidad de comisiones o si...,6015,0.00,6016,0.00
8,Obtenidos por arrendamientos operativos,6017,0.00,6018,0.00
9,TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS,1005,17583809.70,NaN,NaN
10,Relacionadas,6019,0.00,6020,0.00
11,No Relacionadas,6021,0.00,6022,0.00
12,Procedentes de sociedades residentes o estable...,6023,0.00,6024,0.00
13,Procedentes de sociedades no residentes ni est...,6025,0.00,6026,0.00
14,Ganancias netas por mediciones de activos biol...,6027,0.00,6028,0.00
15,Ganancias netas por medición de propiedades de...,6029,0.00,6030,0.00
16,Ganancias netas por medición de instrumentos f...,6031,0.00,6032,0.00
17,Ganancias netas por diferencias de cambios,6033,0.00,6034,0.00
18,"Utilidad en venta de propiedades, planta y equipo",6035,53053.46,6036,0.00
19,Utilidad en la enajenación de derechos represe...,6037,0.00,6038,0.00
20,Ingresos devengados por subvenciones del gobie...,6039,0.00,6040,0.00
21,De activos financieros (reversión de provision...,6041,0.00,6042,0.00
22,De inventarios,6043,0.00,6044,0.00
23,De activos no corrientes mantenidos para la venta,6045,0.00,6046,0.00
24,De activos biológicos,6047,0.00,6048,0.00
25,"De propiedades, planta y equipo",6049,0.00,6050,0.00
26,De activos intangibles,6051,0.00,6052,0.00
27,De propiedades de inversión,6053,0.00,6054,0.00
28,"De activos de exploración, evaluación y explot...",6055,0.00,6056,0.00
29,De inversiones no corrientes,6057,0.00,6058,0.00
30,Otras,6059,0.00,6060,0.00
31,Por garantías,6061,0.00,6062,0.00
32,Por desmantelamientos,6063,0.00,6064,0.00
33,Por contratos onerosos,6065,0.00,6066,0.00
34,Por reestructuraciones de negocios,6067,0.00,6068,0.00
35,Por reembolsos a clientes,6069,0.00,6070,0.00
36,Por litigios,6071,0.00,6072,0.00
37,Por pasivos contingentes asumidos en una combi...,6073,0.00,6074,0.00
38,Otras,6075,0.00,6076,0.00
39,Jubilación patronal y desahucio,6077,68394.75,6078,26040.53

In [74]:
valoresUsd = []
for i in range(len(df6ERI)):
    valoresUsd.append( [df6ERI.loc[i,"USD 1"], df6ERI.loc[i,"USD2"]] )

In [75]:
#for listaUSD in valoresUsd:
#    for usd in listaUSD:
#       if pd.isna(usd):
#            usd = 11
#            print(valoresUsd.index(listaUSD))
#            print(listaUSD.index(usd))

print(valoresUsd)

[[16866390.7, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [717418.93, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [17583809.7, nan], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [53053.46, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [68394.75, 26040.53]]

In [76]:
arrUsd = np.array(valoresUsd)

In [77]:
arrUsd = np.reshape(arrUsd,(1,-1))

In [78]:
columnaUSD =  arrUsd.flatten().tolist()

In [79]:
print(len(columnaUSD))
print(len(extended_values))

80
80

In [80]:
datosF6_2 = pd.DataFrame([columnaUSD], columns=extended_values)
datosF6_2

,Gravadas con tarifa diferente de 0% de IVA Total ingresos,Gravadas con tarifa diferente de 0% de IVA Valor exento / no objeto,Gravadas con tarifa 0% de iva o exentas de IVA Total ingresos,Gravadas con tarifa 0% de iva o exentas de IVA Valor exento / no objeto,Gravadas con tarifa diferente de 0% de IVA Total ingresos,Gravadas con tarifa diferente de 0% de IVA Valor exento / no objeto,Gravadas con tarifa 0% de iva o exentas de IVA Total ingresos,Gravadas con tarifa 0% de iva o exentas de IVA Valor exento / no objeto,De bienes Total ingresos,De bienes Valor exento / no objeto,...,Por reembolsos a clientes Total ingresos,Por reembolsos a clientes Valor exento / no objeto,Por litigios Total ingresos,Por litigios Valor exento / no objeto,Por pasivos contingentes asumidos en una combinación de negocios Total ingresos,Por pasivos contingentes asumidos en una combinación de negocios Valor exento / no objeto,Otras Total ingresos,Otras Valor exento / no objeto,Jubilación patronal y desahucio Total ingresos,Jubilación patronal y desahucio Valor exento / no objeto
0,16866390.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,717418.93,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68394.75,26040.53

### Séptima hoja del pdf

In [81]:
seventh = tabula.read_pdf(pdfOriginal, pages=7, area=(21.05,6.12,916.86,605.88), lattice=False, output_format="dataframe", encoding="latin-1")
df7 = seventh[0]
df7

,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
0,RENTAS NETAS PROVENIENTES DE DONACIONES Y APOR...,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
1,De recursos públicos,NaN,6081,0.0,6082,0.0
2,De otras locales,NaN,6083,0.0,6084,0.0
3,Del exterior,NaN,6085,0.0,6086,0.0
4,POR REEMBOLSOS DE SEGUROS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
...,...,...,...,...,...,...
68,Inventario inicial de bienes no producidos por...,770349.29,.,NaN,.,NaN
69,Compras netas locales de bienes no producidos ...,0.00,.,NaN,7006,0.0
70,Importaciones de bienes no producidos por el s...,107583.53,NaN,NaN,7009,0.0
71,(-) Inventario final de bienes no producidos p...,519020.26,.,NaN,.,NaN
72,Inventario inicial de materia prima 7013,2561776.54,.,NaN,.,NaN

In [82]:
newFirstRow = pd.DataFrame([df7.columns.to_list()], columns=df7.columns)
dataFrame7 = pd.concat([newFirstRow, df7])
dataFrame7

,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
0,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
0,RENTAS NETAS PROVENIENTES DE DONACIONES Y APOR...,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
1,De recursos públicos,NaN,6081,0.0,6082,0.0
2,De otras locales,NaN,6083,0.0,6084,0.0
3,Del exterior,NaN,6085,0.0,6086,0.0
...,...,...,...,...,...,...
68,Inventario inicial de bienes no producidos por...,770349.29,.,NaN,.,NaN
69,Compras netas locales de bienes no producidos ...,0.0,.,NaN,7006,0.0
70,Importaciones de bienes no producidos por el s...,107583.53,NaN,NaN,7009,0.0
71,(-) Inventario final de bienes no producidos p...,519020.26,.,NaN,.,NaN
72,Inventario inicial de materia prima 7013,2561776.54,.,NaN,.,NaN

In [83]:
dataFrame7.reset_index(drop=True, inplace=True)
dataFrame7

,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
0,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
1,RENTAS NETAS PROVENIENTES DE DONACIONES Y APOR...,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
2,De recursos públicos,NaN,6081,0.0,6082,0.0
3,De otras locales,NaN,6083,0.0,6084,0.0
4,Del exterior,NaN,6085,0.0,6086,0.0
...,...,...,...,...,...,...
69,Inventario inicial de bienes no producidos por...,770349.29,.,NaN,.,NaN
70,Compras netas locales de bienes no producidos ...,0.0,.,NaN,7006,0.0
71,Importaciones de bienes no producidos por el s...,107583.53,NaN,NaN,7009,0.0
72,(-) Inventario final de bienes no producidos p...,519020.26,.,NaN,.,NaN
73,Inventario inicial de materia prima 7013,2561776.54,.,NaN,.,NaN

In [84]:
dataFrame7.iloc[:60]

,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
0,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
1,RENTAS NETAS PROVENIENTES DE DONACIONES Y APOR...,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
2,De recursos públicos,NaN,6081,0.0,6082,0.0
3,De otras locales,NaN,6083,0.0,6084,0.0
4,Del exterior,NaN,6085,0.0,6086,0.0
5,POR REEMBOLSOS DE SEGUROS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
6,Por lucro cesante,NaN,6087,0.0,6088,0.0
7,Otros,NaN,6089,33532.46,6090,33532.46
8,Provenientes del exterior,NaN,6091,0.0,6092,0.0
9,Otros,NaN,6093,0.0,6094,0.0
10,INGRESOS FINANCIEROS Y OTROS NO OPERACIONALES,NaN,NaN,NaN,NaN,NaN
11,INGRESOS FINANCIEROS,NaN,NaN,NaN,NaN,NaN
12,ARRENDAMIENTO MERCANTIL,NaN,NaN,NaN,NaN,NaN
13,RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
14,Local,NaN,6095,0.0,6096,0.0
15,Del exterior,NaN,6097,0.0,6098,0.0
16,NO RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
17,Local,NaN,6099,0.0,6100,0.0
18,Del exterior,NaN,6101,0.0,6102,0.0
19,"COSTOS DE TRANSACCIÓN (COMISIONES BANCRIAS, HO...",NaN,NaN,NaN,NaN,NaN
20,RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
21,Local,NaN,6103,0.0,6104,0.0
22,Del exterior,NaN,6105,0.0,6106,0.0
23,NO RELACIONADAS,NaN,Total ingresos,NaN,NaN,NaN
24,Local,NaN,6107,0.0,6108,0.0
25,Del exterior,NaN,6109,0.0,6110,0.0
26,INTERESES CON INSTITUCIONES FINANCIERAS,NaN,NaN,NaN,NaN,NaN
27,RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
28,Local,NaN,6111,0.0,6112,0.0
29,Del exterior,NaN,6113,0.0,6114,0.0
30,NO RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
31,Local,NaN,6115,2420.0,6116,0.0
32,Del exterior,NaN,6117,0.0,6118,0.0
33,INTERESES DEVENGADOS CON TERCEROS,NaN,NaN,NaN,NaN,NaN
34,RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
35,Local,NaN,6119,234717.7,6120,0.0
36,Del exterior,NaN,6121,0.0,6122,0.0
37,NO RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
38,Local,NaN,6123,0.0,6124,0.0
39,Del exterior,NaN,6125,0.0,6126,0.0
40,Prestación de servicios de custodia de activos...,NaN,6241,0.0,6242,0.0
41,Prestación de servicios de operaciones de inve...,NaN,6251,0.0,6252,0.0
42,"Por actividades de inversión, reinversión o de...",NaN,6261,0.0,6262,0.0
43,.,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
44,Intereses implícitos devengados por acuerdos q...,NaN,6127,0.0,6128,0.0
45,Otros,NaN,6129,0.0,6130,0.0
46,Ganancias por medición de inversiones en asoci...,NaN,6131,0.0,6132,0.0
47,Otros,NaN,6133,54712.91,6134,0.0
48,NaN,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
49,Ganancias netas procedentes de actividades dis...,NaN,6135,0.0,6136,0.0
50,TOTAL INGRESOS NO OPERACIONALES,NaN,1045,446831.28,NaN,NaN
51,TOTAL INGRESOS,NaN,NaN,NaN,6999,18030640.9
52,"Ventas netas de propiedades, planta y equipo (...",NaN,NaN,NaN,6140,114862.74
53,Ingresos por reembolso como intermediario / mo...,NaN,NaN,NaN,6141,0.0
54,Dividendos declarados (distribuidos) a favor d...,NaN,NaN,NaN,6142,0.0
55,Dividendos cobrados (recaudados) por el contr...,NaN,NaN,NaN,6143,0.0
56,Ingresos obtenidos por las organizaciones pre...,NaN,NaN,NaN,NaN,NaN
57,Utilidades (Informativo),NaN,NaN,NaN,6144,0.0
58,Excedentes (Informativo),NaN,NaN,NaN,6145,0.0
59,Monto total facturado por comisionistas y simi...,NaN,NaN,NaN,NaN,NaN

In [85]:
df7Part1 = dataFrame7.iloc[:52].copy()
df7Part1

,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
0,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
1,RENTAS NETAS PROVENIENTES DE DONACIONES Y APOR...,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
2,De recursos públicos,NaN,6081,0.0,6082,0.0
3,De otras locales,NaN,6083,0.0,6084,0.0
4,Del exterior,NaN,6085,0.0,6086,0.0
5,POR REEMBOLSOS DE SEGUROS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
6,Por lucro cesante,NaN,6087,0.0,6088,0.0
7,Otros,NaN,6089,33532.46,6090,33532.46
8,Provenientes del exterior,NaN,6091,0.0,6092,0.0
9,Otros,NaN,6093,0.0,6094,0.0
10,INGRESOS FINANCIEROS Y OTROS NO OPERACIONALES,NaN,NaN,NaN,NaN,NaN
11,INGRESOS FINANCIEROS,NaN,NaN,NaN,NaN,NaN
12,ARRENDAMIENTO MERCANTIL,NaN,NaN,NaN,NaN,NaN
13,RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
14,Local,NaN,6095,0.0,6096,0.0
15,Del exterior,NaN,6097,0.0,6098,0.0
16,NO RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
17,Local,NaN,6099,0.0,6100,0.0
18,Del exterior,NaN,6101,0.0,6102,0.0
19,"COSTOS DE TRANSACCIÓN (COMISIONES BANCRIAS, HO...",NaN,NaN,NaN,NaN,NaN
20,RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
21,Local,NaN,6103,0.0,6104,0.0
22,Del exterior,NaN,6105,0.0,6106,0.0
23,NO RELACIONADAS,NaN,Total ingresos,NaN,NaN,NaN
24,Local,NaN,6107,0.0,6108,0.0
25,Del exterior,NaN,6109,0.0,6110,0.0
26,INTERESES CON INSTITUCIONES FINANCIERAS,NaN,NaN,NaN,NaN,NaN
27,RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
28,Local,NaN,6111,0.0,6112,0.0
29,Del exterior,NaN,6113,0.0,6114,0.0
30,NO RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
31,Local,NaN,6115,2420.0,6116,0.0
32,Del exterior,NaN,6117,0.0,6118,0.0
33,INTERESES DEVENGADOS CON TERCEROS,NaN,NaN,NaN,NaN,NaN
34,RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
35,Local,NaN,6119,234717.7,6120,0.0
36,Del exterior,NaN,6121,0.0,6122,0.0
37,NO RELACIONADAS,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
38,Local,NaN,6123,0.0,6124,0.0
39,Del exterior,NaN,6125,0.0,6126,0.0
40,Prestación de servicios de custodia de activos...,NaN,6241,0.0,6242,0.0
41,Prestación de servicios de operaciones de inve...,NaN,6251,0.0,6252,0.0
42,"Por actividades de inversión, reinversión o de...",NaN,6261,0.0,6262,0.0
43,.,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
44,Intereses implícitos devengados por acuerdos q...,NaN,6127,0.0,6128,0.0
45,Otros,NaN,6129,0.0,6130,0.0
46,Ganancias por medición de inversiones en asoci...,NaN,6131,0.0,6132,0.0
47,Otros,NaN,6133,54712.91,6134,0.0
48,NaN,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
49,Ganancias netas procedentes de actividades dis...,NaN,6135,0.0,6136,0.0
50,TOTAL INGRESOS NO OPERACIONALES,NaN,1045,446831.28,NaN,NaN
51,TOTAL INGRESOS,NaN,NaN,NaN,6999,18030640.9

In [86]:
df7Part1.drop(["Unnamed: 1"], axis=1, inplace=True)
df7Part1

,Otros,6079,0.00,6080,0.00.1
0,Otros,6079,0.00,6080,0.00.1
1,RENTAS NETAS PROVENIENTES DE DONACIONES Y APOR...,Total ingresos,NaN,Valor exento / no objeto,NaN
2,De recursos públicos,6081,0.0,6082,0.0
3,De otras locales,6083,0.0,6084,0.0
4,Del exterior,6085,0.0,6086,0.0
5,POR REEMBOLSOS DE SEGUROS,Total ingresos,NaN,Valor exento / no objeto,NaN
6,Por lucro cesante,6087,0.0,6088,0.0
7,Otros,6089,33532.46,6090,33532.46
8,Provenientes del exterior,6091,0.0,6092,0.0
9,Otros,6093,0.0,6094,0.0
10,INGRESOS FINANCIEROS Y OTROS NO OPERACIONALES,NaN,NaN,NaN,NaN
11,INGRESOS FINANCIEROS,NaN,NaN,NaN,NaN
12,ARRENDAMIENTO MERCANTIL,NaN,NaN,NaN,NaN
13,RELACIONADAS,Total ingresos,NaN,Valor exento / no objeto,NaN
14,Local,6095,0.0,6096,0.0
15,Del exterior,6097,0.0,6098,0.0
16,NO RELACIONADAS,Total ingresos,NaN,Valor exento / no objeto,NaN
17,Local,6099,0.0,6100,0.0
18,Del exterior,6101,0.0,6102,0.0
19,"COSTOS DE TRANSACCIÓN (COMISIONES BANCRIAS, HO...",NaN,NaN,NaN,NaN
20,RELACIONADAS,Total ingresos,NaN,Valor exento / no objeto,NaN
21,Local,6103,0.0,6104,0.0
22,Del exterior,6105,0.0,6106,0.0
23,NO RELACIONADAS,Total ingresos,NaN,NaN,NaN
24,Local,6107,0.0,6108,0.0
25,Del exterior,6109,0.0,6110,0.0
26,INTERESES CON INSTITUCIONES FINANCIERAS,NaN,NaN,NaN,NaN
27,RELACIONADAS,Total ingresos,NaN,Valor exento / no objeto,NaN
28,Local,6111,0.0,6112,0.0
29,Del exterior,6113,0.0,6114,0.0
30,NO RELACIONADAS,Total ingresos,NaN,Valor exento / no objeto,NaN
31,Local,6115,2420.0,6116,0.0
32,Del exterior,6117,0.0,6118,0.0
33,INTERESES DEVENGADOS CON TERCEROS,NaN,NaN,NaN,NaN
34,RELACIONADAS,Total ingresos,NaN,Valor exento / no objeto,NaN
35,Local,6119,234717.7,6120,0.0
36,Del exterior,6121,0.0,6122,0.0
37,NO RELACIONADAS,Total ingresos,NaN,Valor exento / no objeto,NaN
38,Local,6123,0.0,6124,0.0
39,Del exterior,6125,0.0,6126,0.0
40,Prestación de servicios de custodia de activos...,6241,0.0,6242,0.0
41,Prestación de servicios de operaciones de inve...,6251,0.0,6252,0.0
42,"Por actividades de inversión, reinversión o de...",6261,0.0,6262,0.0
43,.,Total ingresos,NaN,Valor exento / no objeto,NaN
44,Intereses implícitos devengados por acuerdos q...,6127,0.0,6128,0.0
45,Otros,6129,0.0,6130,0.0
46,Ganancias por medición de inversiones en asoci...,6131,0.0,6132,0.0
47,Otros,6133,54712.91,6134,0.0
48,NaN,Total ingresos,NaN,Valor exento / no objeto,NaN
49,Ganancias netas procedentes de actividades dis...,6135,0.0,6136,0.0
50,TOTAL INGRESOS NO OPERACIONALES,1045,446831.28,NaN,NaN
51,TOTAL INGRESOS,NaN,NaN,6999,18030640.9

In [87]:
indexCurrencyNull = df7Part1[ (df7Part1["0.00"].isna()) & (df7Part1["0.00.1"].isna()) ].index

df7Part1.drop(indexCurrencyNull, inplace=True)
df7Part1

,Otros,6079,0.00,6080,0.00.1
0,Otros,6079,0.00,6080,0.00.1
2,De recursos públicos,6081,0.0,6082,0.0
3,De otras locales,6083,0.0,6084,0.0
4,Del exterior,6085,0.0,6086,0.0
6,Por lucro cesante,6087,0.0,6088,0.0
7,Otros,6089,33532.46,6090,33532.46
8,Provenientes del exterior,6091,0.0,6092,0.0
9,Otros,6093,0.0,6094,0.0
14,Local,6095,0.0,6096,0.0
15,Del exterior,6097,0.0,6098,0.0
17,Local,6099,0.0,6100,0.0
18,Del exterior,6101,0.0,6102,0.0
21,Local,6103,0.0,6104,0.0
22,Del exterior,6105,0.0,6106,0.0
24,Local,6107,0.0,6108,0.0
25,Del exterior,6109,0.0,6110,0.0
28,Local,6111,0.0,6112,0.0
29,Del exterior,6113,0.0,6114,0.0
31,Local,6115,2420.0,6116,0.0
32,Del exterior,6117,0.0,6118,0.0
35,Local,6119,234717.7,6120,0.0
36,Del exterior,6121,0.0,6122,0.0
38,Local,6123,0.0,6124,0.0
39,Del exterior,6125,0.0,6126,0.0
40,Prestación de servicios de custodia de activos...,6241,0.0,6242,0.0
41,Prestación de servicios de operaciones de inve...,6251,0.0,6252,0.0
42,"Por actividades de inversión, reinversión o de...",6261,0.0,6262,0.0
44,Intereses implícitos devengados por acuerdos q...,6127,0.0,6128,0.0
45,Otros,6129,0.0,6130,0.0
46,Ganancias por medición de inversiones en asoci...,6131,0.0,6132,0.0
47,Otros,6133,54712.91,6134,0.0
49,Ganancias netas procedentes de actividades dis...,6135,0.0,6136,0.0
50,TOTAL INGRESOS NO OPERACIONALES,1045,446831.28,NaN,NaN
51,TOTAL INGRESOS,NaN,NaN,6999,18030640.9

In [88]:
df7Part1.rename(inplace=True, columns={"Otros":"CUENTA", "6079":"Total ingresos",
                        "0.00":"USD 1" ,"6080":"Valor exento / no objeto", "0.00.1":"USD2"})
df7Part1

,CUENTA,Total ingresos,USD 1,Valor exento / no objeto,USD2
0,Otros,6079,0.00,6080,0.00.1
2,De recursos públicos,6081,0.0,6082,0.0
3,De otras locales,6083,0.0,6084,0.0
4,Del exterior,6085,0.0,6086,0.0
6,Por lucro cesante,6087,0.0,6088,0.0
7,Otros,6089,33532.46,6090,33532.46
8,Provenientes del exterior,6091,0.0,6092,0.0
9,Otros,6093,0.0,6094,0.0
14,Local,6095,0.0,6096,0.0
15,Del exterior,6097,0.0,6098,0.0
17,Local,6099,0.0,6100,0.0
18,Del exterior,6101,0.0,6102,0.0
21,Local,6103,0.0,6104,0.0
22,Del exterior,6105,0.0,6106,0.0
24,Local,6107,0.0,6108,0.0
25,Del exterior,6109,0.0,6110,0.0
28,Local,6111,0.0,6112,0.0
29,Del exterior,6113,0.0,6114,0.0
31,Local,6115,2420.0,6116,0.0
32,Del exterior,6117,0.0,6118,0.0
35,Local,6119,234717.7,6120,0.0
36,Del exterior,6121,0.0,6122,0.0
38,Local,6123,0.0,6124,0.0
39,Del exterior,6125,0.0,6126,0.0
40,Prestación de servicios de custodia de activos...,6241,0.0,6242,0.0
41,Prestación de servicios de operaciones de inve...,6251,0.0,6252,0.0
42,"Por actividades de inversión, reinversión o de...",6261,0.0,6262,0.0
44,Intereses implícitos devengados por acuerdos q...,6127,0.0,6128,0.0
45,Otros,6129,0.0,6130,0.0
46,Ganancias por medición de inversiones en asoci...,6131,0.0,6132,0.0
47,Otros,6133,54712.91,6134,0.0
49,Ganancias netas procedentes de actividades dis...,6135,0.0,6136,0.0
50,TOTAL INGRESOS NO OPERACIONALES,1045,446831.28,NaN,NaN
51,TOTAL INGRESOS,NaN,NaN,6999,18030640.9

In [89]:
columnsToAppend =  df7Part1 .columns.to_list()
print(columnsToAppend)
columnsToAppend.remove("CUENTA");  columnsToAppend.remove("USD 1");  columnsToAppend.remove("USD2"); 
print(columnsToAppend)

['CUENTA', 'Total ingresos', 'USD 1', 'Valor exento / no objeto', 'USD2']
['Total ingresos', 'Valor exento / no objeto']

In [90]:
extendedCuentaValues = df7Part1["CUENTA"].to_list()
print(extendedCuentaValues)

['Otros', 'De recursos públicos', 'De otras locales', 'Del exterior', 'Por lucro cesante', 'Otros', 'Provenientes del exterior', 'Otros', 'Local', 'Del exterior', 'Local', 'Del exterior', 'Local', 'Del exterior', 'Local', 'Del exterior', 'Local', 'Del exterior', 'Local', 'Del exterior', 'Local', 'Del exterior', 'Local', 'Del exterior', 'Prestación de servicios de custodia de activos financieros', 'Prestación de servicios de operaciones de inversión en nombre de terceros', 'Por actividades de inversión, reinversión o de negociación de activos financieros (si la sociedad es administrada por una Institución Financiera)', 'Intereses implícitos devengados por acuerdos que constituyen efectivamente una transacción financiera o cobro diferido', 'Otros', 'Ganancias por medición de inversiones en asociadas y negocios conjuntos al método de la participación (valor patrimonial proporcional)', 'Otros', 'Ganancias netas procedentes de actividades discontinuadas', 'TOTAL INGRESOS NO OPERACIONALES', 'TOTAL INGRESOS']

In [91]:
extendedCuentaValuesLENGHT = len(extendedCuentaValues)
extended_values = []
for cuenta_value in extendedCuentaValues:
    for column_to_append in columnsToAppend:
        extended_values.append(cuenta_value + " " + column_to_append)

print(extended_values)

['Otros Total ingresos', 'Otros Valor exento / no objeto', 'De recursos públicos Total ingresos', 'De recursos públicos Valor exento / no objeto', 'De otras locales Total ingresos', 'De otras locales Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Por lucro cesante Total ingresos', 'Por lucro cesante Valor exento / no objeto', 'Otros Total ingresos', 'Otros Valor exento / no objeto', 'Provenientes del exterior Total ingresos', 'Provenientes del exterior Valor exento / no objeto', 'Otros Total ingresos', 'Otros Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Prestación de servicios de custodia de activos financieros Total ingresos', 'Prestación de servicios de custodia de activos financieros Valor exento / no objeto', 'Prestación de servicios de operaciones de inversión en nombre de terceros Total ingresos', 'Prestación de servicios de operaciones de inversión en nombre de terceros Valor exento / no objeto', 'Por actividades de inversión, reinversión o de negociación de activos financieros (si la sociedad es administrada por una Institución Financiera) Total ingresos', 'Por actividades de inversión, reinversión o de negociación de activos financieros (si la sociedad es administrada por una Institución Financiera) Valor exento / no objeto', 'Intereses implícitos devengados por acuerdos que constituyen efectivamente una transacción financiera o cobro diferido Total ingresos', 'Intereses implícitos devengados por acuerdos que constituyen efectivamente una transacción financiera o cobro diferido Valor exento / no objeto', 'Otros Total ingresos', 'Otros Valor exento / no objeto', 'Ganancias por medición de inversiones en asociadas y negocios conjuntos al método de la participación (valor patrimonial proporcional) Total ingresos', 'Ganancias por medición de inversiones en asociadas y negocios conjuntos al método de la participación (valor patrimonial proporcional) Valor exento / no objeto', 'Otros Total ingresos', 'Otros Valor exento / no objeto', 'Ganancias netas procedentes de actividades discontinuadas Total ingresos', 'Ganancias netas procedentes de actividades discontinuadas Valor exento / no objeto', 'TOTAL INGRESOS NO OPERACIONALES Total ingresos', 'TOTAL INGRESOS NO OPERACIONALES Valor exento / no objeto', 'TOTAL INGRESOS Total ingresos', 'TOTAL INGRESOS Valor exento / no objeto']

In [92]:
df7Part1.reset_index(drop=True, inplace=True)
df7Part1

,CUENTA,Total ingresos,USD 1,Valor exento / no objeto,USD2
0,Otros,6079,0.00,6080,0.00.1
1,De recursos públicos,6081,0.0,6082,0.0
2,De otras locales,6083,0.0,6084,0.0
3,Del exterior,6085,0.0,6086,0.0
4,Por lucro cesante,6087,0.0,6088,0.0
5,Otros,6089,33532.46,6090,33532.46
6,Provenientes del exterior,6091,0.0,6092,0.0
7,Otros,6093,0.0,6094,0.0
8,Local,6095,0.0,6096,0.0
9,Del exterior,6097,0.0,6098,0.0
10,Local,6099,0.0,6100,0.0
11,Del exterior,6101,0.0,6102,0.0
12,Local,6103,0.0,6104,0.0
13,Del exterior,6105,0.0,6106,0.0
14,Local,6107,0.0,6108,0.0
15,Del exterior,6109,0.0,6110,0.0
16,Local,6111,0.0,6112,0.0
17,Del exterior,6113,0.0,6114,0.0
18,Local,6115,2420.0,6116,0.0
19,Del exterior,6117,0.0,6118,0.0
20,Local,6119,234717.7,6120,0.0
21,Del exterior,6121,0.0,6122,0.0
22,Local,6123,0.0,6124,0.0
23,Del exterior,6125,0.0,6126,0.0
24,Prestación de servicios de custodia de activos...,6241,0.0,6242,0.0
25,Prestación de servicios de operaciones de inve...,6251,0.0,6252,0.0
26,"Por actividades de inversión, reinversión o de...",6261,0.0,6262,0.0
27,Intereses implícitos devengados por acuerdos q...,6127,0.0,6128,0.0
28,Otros,6129,0.0,6130,0.0
29,Ganancias por medición de inversiones en asoci...,6131,0.0,6132,0.0
30,Otros,6133,54712.91,6134,0.0
31,Ganancias netas procedentes de actividades dis...,6135,0.0,6136,0.0
32,TOTAL INGRESOS NO OPERACIONALES,1045,446831.28,NaN,NaN
33,TOTAL INGRESOS,NaN,NaN,6999,18030640.9

In [93]:
valoresUsd = []
for i in range(len(df7Part1)):
    valoresUsd.append( [df7Part1.loc[i,"USD 1"], df7Part1.loc[i,"USD2"]] )
print(valoresUsd)

[['0.00', '0.00.1'], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [33532.46, 33532.46], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [2420.0, 0.0], [0.0, 0.0], [234717.7, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [54712.91, 0.0], [0.0, 0.0], [446831.28, nan], [nan, 18030640.9]]

In [94]:
valoresUsd[0][1]="0.00"
valoresUsd[0]

['0.00', '0.00']

In [95]:
arrUsd = np.array(valoresUsd)
arrUsd = np.reshape(arrUsd, (1,-1))
columnaUSD = arrUsd.flatten().tolist()

In [96]:
print(len(columnaUSD))
print(len(extended_values))

68
68

In [97]:
datosF7 = pd.DataFrame([columnaUSD], columns=extended_values, dtype=float)
datosF7

,Otros Total ingresos,Otros Valor exento / no objeto,De recursos públicos Total ingresos,De recursos públicos Valor exento / no objeto,De otras locales Total ingresos,De otras locales Valor exento / no objeto,Del exterior Total ingresos,Del exterior Valor exento / no objeto,Por lucro cesante Total ingresos,Por lucro cesante Valor exento / no objeto,...,Ganancias por medición de inversiones en asociadas y negocios conjuntos al método de la participación (valor patrimonial proporcional) Total ingresos,Ganancias por medición de inversiones en asociadas y negocios conjuntos al método de la participación (valor patrimonial proporcional) Valor exento / no objeto,Otros Total ingresos,Otros Valor exento / no objeto,Ganancias netas procedentes de actividades discontinuadas Total ingresos,Ganancias netas procedentes de actividades discontinuadas Valor exento / no objeto,TOTAL INGRESOS NO OPERACIONALES Total ingresos,TOTAL INGRESOS NO OPERACIONALES Valor exento / no objeto,TOTAL INGRESOS Total ingresos,TOTAL INGRESOS Valor exento / no objeto
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,54712.91,0.0,0.0,0.0,446831.28,NaN,NaN,18030640.9

In [98]:
df7Part2 =  dataFrame7.iloc[52:67].copy()

In [99]:
df7Part2

,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
52,"Ventas netas de propiedades, planta y equipo (...",NaN,NaN,NaN,6140,114862.74
53,Ingresos por reembolso como intermediario / mo...,NaN,NaN,NaN,6141,0.0
54,Dividendos declarados (distribuidos) a favor d...,NaN,NaN,NaN,6142,0.0
55,Dividendos cobrados (recaudados) por el contr...,NaN,NaN,NaN,6143,0.0
56,Ingresos obtenidos por las organizaciones pre...,NaN,NaN,NaN,NaN,NaN
57,Utilidades (Informativo),NaN,NaN,NaN,6144,0.0
58,Excedentes (Informativo),NaN,NaN,NaN,6145,0.0
59,Monto total facturado por comisionistas y simi...,NaN,NaN,NaN,NaN,NaN
60,Correspondiente a los valores brutos de los bi...,NaN,NaN,NaN,6146,0.0
61,"Valor total correspondiente a las comisiones, ...",NaN,NaN,NaN,6147,0.0
62,Ingresos generados por compañías de transporte...,NaN,NaN,NaN,6148,0.0
63,Ingresos generados en fideicomisos mercantiles...,NaN,NaN,NaN,6149,0.0
64,Ingresos no objeto de impuesto a la renta,NaN,NaN,NaN,6150,0.0
65,Ingresos obtenidos en dinero electrónico (Info...,NaN,NaN,NaN,6151,0.0
66,Ingresos brutos totales según contabilidad,NaN,NaN,NaN,6152,18030640.9

In [100]:
df7Part2.drop(["Unnamed: 1","6079","0.00","6080"], axis=1, inplace=True)
indexCurrencyNull = df7Part2[ (df7Part2["0.00.1"].isna()) ].index
df7Part2.drop(indexCurrencyNull, inplace=True)
df7Part2

                                                Otros      0.00.1
52  Ventas netas de propiedades, planta y equipo (...   114862.74
53  Ingresos por reembolso como intermediario / mo...         0.0
54  Dividendos declarados (distribuidos) a favor d...         0.0
55  Dividendos cobrados (recaudados) por el  contr...         0.0
57                           Utilidades (Informativo)         0.0
58                           Excedentes (Informativo)         0.0
60  Correspondiente a los valores brutos de los bi...         0.0
61  Valor total correspondiente a las comisiones, ...         0.0
62  Ingresos generados por compañías de transporte...         0.0
63  Ingresos generados en fideicomisos mercantiles...         0.0
64          Ingresos no objeto de impuesto a la renta         0.0
65  Ingresos obtenidos en dinero electrónico (Info...         0.0
66         Ingresos brutos totales según contabilidad  18030640.9

In [101]:
texto.clear()
texto = df7Part2["Otros"].to_list()
valores = np.array( df7Part2["0.00.1"].to_list() ).reshape(1,-1)
datosF7_2 = pd.DataFrame(valores, columns=texto)
datosF7_2

,"Ventas netas de propiedades, planta y equipo (Informativo)",Ingresos por reembolso como intermediario / monto total facturado por operadoras de transporte con puntos de emisión asignados a socios (Informativo),Dividendos declarados (distribuidos) a favor del contribuyente en el ejercicio fiscal (Informativo),Dividendos cobrados (recaudados) por el contribuyente en el ejercicio fiscal (Informativo),Utilidades (Informativo),Excedentes (Informativo),Correspondiente a los valores brutos de los bienes o servicios vendidos bajo la modalidad de comisiones o similares (Informativo),"Valor total correspondiente a las comisiones, descuentos, primas y similares sobre los valores brutos de los bienes o servicios vendidos bajo la modalidad de comisiones o similares (Informativo)",Ingresos generados por compañías de transporte internacional por sus operaciones habituales de transporte (Informativo),Ingresos generados en fideicomisos mercantiles o encargos fiduciarios donde el contribuyente es constituyente o aportante (Informativo),Ingresos no objeto de impuesto a la renta,Ingresos obtenidos en dinero electrónico (Informativo),Ingresos brutos totales según contabilidad
0,114862.74,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18030640.9

In [102]:
dataFrame7.iloc[67:]

,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
67,COSTOS Y GASTOS,NaN,NaN,NaN,NaN,NaN
68,COSTO DE VENTAS Costo,NaN,Gasto,NaN,Valor no deducible,NaN
69,Inventario inicial de bienes no producidos por...,770349.29,.,NaN,.,NaN
70,Compras netas locales de bienes no producidos ...,0.0,.,NaN,7006,0.0
71,Importaciones de bienes no producidos por el s...,107583.53,NaN,NaN,7009,0.0
72,(-) Inventario final de bienes no producidos p...,519020.26,.,NaN,.,NaN
73,Inventario inicial de materia prima 7013,2561776.54,.,NaN,.,NaN

In [103]:
df7Part3 = dataFrame7.iloc[67:].copy()
df7Part3

,Otros,Unnamed: 1,6079,0.00,6080,0.00.1
67,COSTOS Y GASTOS,NaN,NaN,NaN,NaN,NaN
68,COSTO DE VENTAS Costo,NaN,Gasto,NaN,Valor no deducible,NaN
69,Inventario inicial de bienes no producidos por...,770349.29,.,NaN,.,NaN
70,Compras netas locales de bienes no producidos ...,0.0,.,NaN,7006,0.0
71,Importaciones de bienes no producidos por el s...,107583.53,NaN,NaN,7009,0.0
72,(-) Inventario final de bienes no producidos p...,519020.26,.,NaN,.,NaN
73,Inventario inicial de materia prima 7013,2561776.54,.,NaN,.,NaN

In [104]:
df7Part3.rename(inplace=True, columns={
    "Otros":"CUENTA", "Unnamed: 1":"Costo", "6079":"Gasto", "0.00":"0.00",
    "6080":"Valor No Deducible", "0.00.1":"USD2"
})
df7Part3

,CUENTA,Costo,Gasto,0.00,Valor No Deducible,USD2
67,COSTOS Y GASTOS,NaN,NaN,NaN,NaN,NaN
68,COSTO DE VENTAS Costo,NaN,Gasto,NaN,Valor no deducible,NaN
69,Inventario inicial de bienes no producidos por...,770349.29,.,NaN,.,NaN
70,Compras netas locales de bienes no producidos ...,0.0,.,NaN,7006,0.0
71,Importaciones de bienes no producidos por el s...,107583.53,NaN,NaN,7009,0.0
72,(-) Inventario final de bienes no producidos p...,519020.26,.,NaN,.,NaN
73,Inventario inicial de materia prima 7013,2561776.54,.,NaN,.,NaN

In [105]:
df7Part3.drop(["0.00"], axis=1, inplace=True)
df7Part3

,CUENTA,Costo,Gasto,Valor No Deducible,USD2
67,COSTOS Y GASTOS,NaN,NaN,NaN,NaN
68,COSTO DE VENTAS Costo,NaN,Gasto,Valor no deducible,NaN
69,Inventario inicial de bienes no producidos por...,770349.29,.,.,NaN
70,Compras netas locales de bienes no producidos ...,0.0,.,7006,0.0
71,Importaciones de bienes no producidos por el s...,107583.53,NaN,7009,0.0
72,(-) Inventario final de bienes no producidos p...,519020.26,.,.,NaN
73,Inventario inicial de materia prima 7013,2561776.54,.,.,NaN

In [106]:
df7Part3.drop([67,68], inplace=True)
df7Part3

,CUENTA,Costo,Gasto,Valor No Deducible,USD2
69,Inventario inicial de bienes no producidos por...,770349.29,.,.,NaN
70,Compras netas locales de bienes no producidos ...,0.0,.,7006,0.0
71,Importaciones de bienes no producidos por el s...,107583.53,NaN,7009,0.0
72,(-) Inventario final de bienes no producidos p...,519020.26,.,.,NaN
73,Inventario inicial de materia prima 7013,2561776.54,.,.,NaN

In [107]:
df7Part3.replace(".","", inplace=True)
df7Part3

C:\Users\Usuario\AppData\Local\Temp\ipykernel_2464\3425308677.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df7Part3.replace(".","", inplace=True)

,CUENTA,Costo,Gasto,Valor No Deducible,USD2
69,Inventario inicial de bienes no producidos por...,770349.29,,,NaN
70,Compras netas locales de bienes no producidos ...,0.00,,7006,0.0
71,Importaciones de bienes no producidos por el s...,107583.53,NaN,7009,0.0
72,(-) Inventario final de bienes no producidos p...,519020.26,,,NaN
73,Inventario inicial de materia prima 7013,2561776.54,,,NaN

In [108]:
columnasToAppend = df7Part3 .columns.to_list()
print(columnasToAppend)

['CUENTA', 'Costo', 'Gasto', 'Valor No Deducible', 'USD2']

In [109]:
columnasToAppend.remove("CUENTA")
columnasToAppend.remove("USD2")
print(columnasToAppend)

['Costo', 'Gasto', 'Valor No Deducible']

In [110]:
extendedCuentaValues = df7Part3["CUENTA"].to_list()
print(extendedCuentaValues)

['Inventario inicial de bienes no producidos por el sujeto pasivo 7001', 'Compras netas locales de bienes no producidos por el sujeto pasivo 7004', 'Importaciones de bienes no producidos por el sujeto pasivo 7007', '(-) Inventario final de bienes no producidos por el sujeto pasivo 7010', 'Inventario inicial de materia prima 7013']

In [111]:
extendedCuentaValuesLENGHT = len(extendedCuentaValues)
print(extendedCuentaValuesLENGHT)

5

In [112]:
for k in range(extendedCuentaValuesLENGHT):
    extendedCuentaValues[k] = extendedCuentaValues[k][:-5]
print(extendedCuentaValues)

['Inventario inicial de bienes no producidos por el sujeto pasivo', 'Compras netas locales de bienes no producidos por el sujeto pasivo', 'Importaciones de bienes no producidos por el sujeto pasivo', '(-) Inventario final de bienes no producidos por el sujeto pasivo', 'Inventario inicial de materia prima']

In [113]:
extendedValues = []
for cuenta_value in extendedCuentaValues:
    for column_to_append in columnasToAppend:
        extendedValues.append(cuenta_value+ " " + column_to_append)

print(extendedValues)

['Inventario inicial de bienes no producidos por el sujeto pasivo Costo', 'Inventario inicial de bienes no producidos por el sujeto pasivo Gasto', 'Inventario inicial de bienes no producidos por el sujeto pasivo Valor No Deducible', 'Compras netas locales de bienes no producidos por el sujeto pasivo Costo', 'Compras netas locales de bienes no producidos por el sujeto pasivo Gasto', 'Compras netas locales de bienes no producidos por el sujeto pasivo Valor No Deducible', 'Importaciones de bienes no producidos por el sujeto pasivo Costo', 'Importaciones de bienes no producidos por el sujeto pasivo Gasto', 'Importaciones de bienes no producidos por el sujeto pasivo Valor No Deducible', '(-) Inventario final de bienes no producidos por el sujeto pasivo Costo', '(-) Inventario final de bienes no producidos por el sujeto pasivo Gasto', '(-) Inventario final de bienes no producidos por el sujeto pasivo Valor No Deducible', 'Inventario inicial de materia prima Costo', 'Inventario inicial de materia prima Gasto', 'Inventario inicial de materia prima Valor No Deducible']

In [114]:
columnasNumericas = ["Costo","USD2"]
df7Part3[columnasNumericas] = df7Part3[columnasNumericas].astype(float)
df7Part3

,CUENTA,Costo,Gasto,Valor No Deducible,USD2
69,Inventario inicial de bienes no producidos por...,770349.29,,,NaN
70,Compras netas locales de bienes no producidos ...,0.00,,7006,0.0
71,Importaciones de bienes no producidos por el s...,107583.53,NaN,7009,0.0
72,(-) Inventario final de bienes no producidos p...,519020.26,,,NaN
73,Inventario inicial de materia prima 7013,2561776.54,,,NaN

In [115]:
df7Part3.reset_index(drop=True, inplace=True)

In [116]:
df7Part3.replace(pd.NA,0, inplace=True)
df7Part3

,CUENTA,Costo,Gasto,Valor No Deducible,USD2
0,Inventario inicial de bienes no producidos por...,770349.29,,,NaN
1,Compras netas locales de bienes no producidos ...,0.00,,7006,0.0
2,Importaciones de bienes no producidos por el s...,107583.53,0,7009,0.0
3,(-) Inventario final de bienes no producidos p...,519020.26,,,NaN
4,Inventario inicial de materia prima 7013,2561776.54,,,NaN

In [117]:
print(len(df7Part3))

5

In [118]:
valoressUsd = []
for i in range(len(df7Part3)):
    valoressUsd.append( [ df7Part3.loc[i,"Costo"], df7Part3.loc[i,"Gasto"], df7Part3.loc[i,"USD2"]] )

In [119]:
valoressUsd

[[770349.29, '', nan],
 [0.0, '', 0.0],
 [107583.53, 0, 0.0],
 [519020.26, '', nan],
 [2561776.54, '', nan]]

In [120]:
arrUsd = np.array(valoressUsd)
arrUsd = np.reshape(arrUsd,(1,-1))
columnaUSD = arrUsd.flatten().tolist()

In [121]:
print(len(columnaUSD))
print(len(extendedValues))

15
15

In [122]:
datosF7_3 = pd.DataFrame([columnaUSD], columns=extendedValues)
datosF7_3

,Inventario inicial de bienes no producidos por el sujeto pasivo Costo,Inventario inicial de bienes no producidos por el sujeto pasivo Gasto,Inventario inicial de bienes no producidos por el sujeto pasivo Valor No Deducible,Compras netas locales de bienes no producidos por el sujeto pasivo Costo,Compras netas locales de bienes no producidos por el sujeto pasivo Gasto,Compras netas locales de bienes no producidos por el sujeto pasivo Valor No Deducible,Importaciones de bienes no producidos por el sujeto pasivo Costo,Importaciones de bienes no producidos por el sujeto pasivo Gasto,Importaciones de bienes no producidos por el sujeto pasivo Valor No Deducible,(-) Inventario final de bienes no producidos por el sujeto pasivo Costo,(-) Inventario final de bienes no producidos por el sujeto pasivo Gasto,(-) Inventario final de bienes no producidos por el sujeto pasivo Valor No Deducible,Inventario inicial de materia prima Costo,Inventario inicial de materia prima Gasto,Inventario inicial de materia prima Valor No Deducible
0,770349.29,,nan,0.0,,0.0,107583.53,0,0.0,519020.26,,nan,2561776.54,,nan

In [123]:
print(datosF1.iloc[0].to_list())
listaDataframes = [datosF1, datosF2, datosF3, datosF4, datosF5, datosF6_1, datosF6_2,
                datosF7, datosF7_2, datosF7_3]

rows = []
for dataframe in listaDataframes:
    fila = dataframe.iloc[0].to_list()
    rows.extend(fila)

arrayDatos1_7 = np.array(rows)
print(arrayDatos1_7)

['0.00', '0.00', '16999072.30', '141014.32', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '17140086.60', '1349952.02', '4260917.80', '0.00', '0.00', '338867.98', '0.00', '34326.37', '0.00', '0.00', '0.00', '0.00', '1852191.80', '0.00', '0.00', '351441.66', '205734.31', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '304182.83', '0.00', '250211.10']
['0.00' '0.00' '16999072.30' '141014.32' '0.00' '0.00' '0.00' '0.00'
 '0.00' '0.00' '0.00' '0.00' '0.00' '0.00' '0.00' '17140086.60'
 '1349952.02' '4260917.80' '0.00' '0.00' '338867.98' '0.00' '34326.37'
 '0.00' '0.00' '0.00' '0.00' '1852191.80' '0.00' '0.00' '351441.66'
 '205734.31' '0.00' '0.00' '0.00' '0.00' '0.00' '0.00' '0.00' '0.00'
 '0.00' '0.00' '304182.83' '0.00' '250211.10' '1594231.60' '471091.05'
 '1778265.94' '1122335.99' '0.0' '0.0' '0.0' '0.0' '347158.76' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '1497.62' '369338.03' '0.0'
 '14563092.1' '1152785.88' '697772.71' '1879596.32' '676269.68' '0.0'
 '0.0' '2784451.44' '291936.62' '0.0' '0.0' '0.0' '2367554.08'
 '1062025.93' '3908607.58' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '6762.52' '5308405.62' '63639.48' '0.0' '0.0' '2330782.2' '0.0' '0.0'
 '0.0' '1935262.98' '0.0' '0.0' '0.0' '1648557.11' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '10300514.0' '0.0' '95.0' '0.0' '0.0' '0.0' '3508300.61' '0.0'
 '3483182.44' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '1329072.92' '1329072.92' '0.0' '0.0' '0.0' '0.0' '0.0'
 '93480.14' '0.0' '0.0' '0.0' '0.0' '0.0' '28885366.2' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '43448458.3' '78380.54' '0.0' '5730768.0' '1979614.66'
 '468206.61' '0.0' '132921.62' '0.0' '201246.49' '0.0' '2884347.41'
 '1246618.06' '0.0' '0.0' '3018224.61' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '554584.92' '0.0' '27190.01' '0.0' '832618.85' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '1365270.83' '0.0' '0.0' '0.0' '0.0'
 '18519992.6' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '500000.0' '0.0' '0.0' '10253715.7' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '224815.91' '972019.71' '220359.02' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '12170910.4' '0.0'
 '0.0' '30690903.0' '15582462.0' '0.0' '0.0' '911550.71' '0.0' '441163.1'
 '500.0' '0.0' '0.0' '0.00' '6577.58' '135228.44' '0.0' '-1129460.1'
 '717804.24' '0.0' '0.0' 'nan' 'nan' '276732.55' '0.0' '0.0' '0.0' '0.0'
 '103209.01' '0.0' '-4017755.3' '0.0' '0.0' '12757555.3' '43448458.3'
 '16866390.7' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '717418.93' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '17583809.7' 'nan' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '53053.46' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '68394.75'
 '26040.53' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '33532.46' '33532.46' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '2420.0' '0.0' '0.0' '0.0' '234717.7' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '54712.91' '0.0' '0.0' '0.0' '446831.28'
 'nan' 'nan' '18030640.9' '114862.74' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0'
 '0.0' '0.0' '0.0' '0.0' '0.0' '18030640.9' '770349.29' '' 'nan' '0.0' ''
 '0.0' '107583.53' '0' '0.0' '519020.26' '' 'nan' '2561776.54' '' 'nan']

In [124]:
textos = []
for dataframe in listaDataframes:
    fila = dataframe.columns.to_list()
    textos.extend(fila)


print(textos)

['Operaciones de activo', 'Operaciones de pasivo', 'Operaciones de ingreso', 'Operaciones de egreso', 'Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares', 'Operaciones de activo', 'Operaciones de pasivo', 'Operaciones de ingreso', 'Operaciones de egreso', 'Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares', 'Operaciones de activo', 'Operaciones de pasivo', 'Operaciones de ingreso', 'Operaciones de egreso', 'Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares', 'TOTAL OPERACIONES CON PARTES RELACIONADAS', 'Efectivo y equivalentes al efectivo', 'Locales', 'Del exterior', '(-) Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)', 'Locales', 'Del exterior', '(-) Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)', 'Locales', 'Del exterior', 'En efectivo', 'En activos diferentes del efectivo', 'Locales', 'Del exterior', '(-) Deterioro acumulado del valor de otras cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', 'Locales', 'Del exterior', '(-) Deterioro acumulado del valor de otras cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', 'A costo amortizado', '(-) Deterioro acumulado del valor  de otros activos financieros corrientes medidos a costo amortizado  (provisiones para créditos incobrables)', 'A valor razonable', 'Relacionadas', 'No relacionadas', 'Relacionadas', 'No relacionadas', 'Crédito tributario a favor del sujeto pasivo (ISD)', 'Crédito tributario a favor del sujeto pasivo (IVA)', 'Crédito tributario a favor del sujeto pasivo (Impuesto a la Renta)', 'Otros', 'Mercaderías en tránsito', 'Inventario de materia prima (no para la construcción)', 'Inventario de productos en proceso (excluyendo obras/inmuebles en construcción para la venta)', 'Inventario de prod. term. y mercad. en almacén (excluyendo obras/inmuebles  terminados para la venta)', 'Inventario de suministros, herramientas, repuestos y materiales (no para la construcción)', 'Inventario de materia prima, suministros y materiales para la construcción', 'Inventario de obras/inmuebles en construcción para la venta', 'Inventario de obras/inmuebles terminados para la venta', '(-) Deterioro acumulado del valor de inventarios por ajuste al valor neto realizable', 'Costo', '(-) Deterioro acumulado del valor de activos no corrientes mantenidos para la venta', 'A costo', '(-) Deterioro acumulado del valor de activos biológicos medidos a costo', 'A valor razonable menos los costos de venta', 'A costo', '(-) Deterioro acumulado del valor de activos biológicos medidos a costo', 'A valor razonable menos los costos de venta', 'Propaganda y publicidad prepagada', 'Arrendamientos operativos pagados por anticipado', 'Primas de seguro pagadas por anticipado', 'Otros', 'Otros Activos Corrientes', 'TOTAL ACTIVOS CORRIENTES', 'Costo histórico antes de reexpresiones o revaluaciones', 'Ajuste acumulado por reexpresiones o revaluaciones', 'Costo histórico antes de reexpresiones o revaluaciones', 'Ajuste acumulado por reexpresiones o revaluaciones', 'Costo histórico antes de reexpresiones o revaluaciones', 'Ajuste acumulado por reexpresiones o revaluaciones', 'Costo histórico antes de reexpresiones o revaluaciones', 'Ajuste acumulado por reexpresiones o revaluaciones', 'Costo histórico antes de reexpresiones o revaluaciones', 'Ajuste acumulado por reexpresiones o revaluaciones', 'Construcciones en Curso y Otros Activos en Tránsito', 'Muebles y enseres', 'Equipo de Computación', 'Vehículos, Equipo de Transporte y Caminero Móvil', 'Terrenos', 'Edificios y otros inmuebles (excepto terrenos)', 'Naves, aeronaves, barcazas y similares', 'Maquinaria, equipo, instalaciones y adecuaciones', 'Equipo de computación', 'Vehículos, equipo de transporte y caminero móvil', 'Otros', 'Otras Propiedades, Planta y Equipo', 'Del costo histórico antes de reexpresiones o revaluaciones', 'Del ajuste acumulado por reexpresiones o revaluaciones', '(-) Deterioro acumulado del valor de propiedades, planta y equipo', 'Plusvalía o goodwill (derecho de llave)', 'Marcas, patentes, licencias y otros similares', 'Adecuaciones y mejoras en bienes arrendados mediante arrendamiento operativo', 'Derechos en acuerdos de concesión', 'Otros', '(-) Amortización acumulada de activos intangibles', '(-) Deterioro acumulado de activos intangibles', 'Derechos de uso por activos arrendados', '(-) Amortización acumulada de derechos de uso por activos arrendados', 'A costo', 'A valor razonable', ' A costo', ' A valor razonable', ' (-) Depreciación Acumulada de Propiedades de Inversión', ' (-) Deterioro Acumulado del Valor de Propiedades de Inversión', ' A costo', ' (-) Depreciación acumulada de activos biológicos medidos a costo', ' (-) Deterioro acumulado del valor de activos biológicos medidos a costo', ' A valor razonable menos los costos de venta', ' A costo', ' (-) Depreciación acumulada de activos biológicos medidos a costo', ' (-) Deterioro acumulado del valor de activos biológicos medidos a costo', ' A valor razonable menos los costos de venta', ' Tangibles', ' Intangibles', ' (-) Depreciación / amortización acumulada de activos para exploración, evaluación y explotación', ' (-) Deterioro acumulado del valor de activos para exploración, evaluación y explotación', ' Costo', ' Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional)', ' Costo', ' Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional)', ' Costo', ' Ajuste acumulado por aplicación del método de la participación (valor patrimonial proporcional)', ' Otros Derechos Representativos de Capital en Sociedades que no son Subsidiarias, ni Asociadas, ni Negocios Conjuntos', ' (-) Deterioro Acumulado del Valor de Inversiones no Corrientes', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de cuentas y documentos por cobrar comerciales por incobrabilidad (provisiones para créditos incobrables)', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', '  Locales', '  Del exterior', '  (-) Deterioro acumulado del valor de otras cuentas y documentos por cobrar por incobrabilidad (provisiones para créditos incobrables)', ' A costo amortizado', ' (-) Deterioro acumulado del valor  de otros activos ficieros no corrientes medidos a costo amortizado (provisiones para créditos incobrables)', ' A valor razonable', ' Relacionadas', ' No Relacionadas', ' Por diferencias temporarias', ' Por pérdidas tributarias sujetas a amortización en periodos siguientes', ' Crédito tributario a favor del sujeto pasivo (ISD)', ' Crédito tributario a favor del sujeto pasivo (Impuesto a la Renta)', ' Otros', 'Otros Activos No Corrientes', 'TOTAL ACTIVOS NO CORRIENTES', 'Ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)', '(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de otras partidas de propiedades, planta y equipo (Informativo)', 'Ajustes acumulados por reexpresiones o revaluaciones de activos intangibles (Informativo)', '(-) Amortización acumulada de los ajustes acumulados por reexpresiones o revaluaciones de activos intangibles (Informativo)', 'Ajustes acumulados por reexpresiones o revaluaciones de propiedades de inversión (Informativo)', '(-) Depreciación acumulada de los ajustes acumulados por reexpresiones o revaluaciones de propiedades de inversión (Informativo)', 'Ajustes acumulados por reexpresiones o revaluaciones de activos para exploración, evaluación y explotación de recursos minerales (Informativo)', '(-) Depreciación/amortización acumulada del ajustes acumulado por reexpresiones o revaluaciones de activos para exploración, evaluación y explotación de recursos minerales (Informativo)', 'Total de las  revaluaciones y otros ajustes positivos producto de valoraciones financieras excluidos del cálculo del anticipo,  para todos los activos (Informativo)', '(-) Total depreciación acumulada del ajuste acumulado por  revaluaciones y otros ajustes negativos producto de valoraciones financieras excluidos del cálculo del anticipo, para todos los activos (Informativo)', 'Total costo de terrenos en los que se desarrollan actividades agropecuarias (excluyendo sus revaluaciones o reexpresiones) (Informativo)', 'Total deterioro acumulado del costo de terrenos en los que se desarrollan actividades agropecuarias (Informativo)', 'Total costo de terrenos en los que se desarrollan proyectos inmobiliarios para la vivienda de interés social (excluyendo sus revaluaciones o reexpresiones) (Informativo)', 'Total deterioro acumulado del costo de terrenos en los que se desarrollan proyectos inmobiliarios para la vivienda de interés  social (Informativo)', 'Total de intereses implícitos no devengados (futuros ingresos financieros en el estado de resultados) por acuerdos que constituyen efectivamente una transacción financiera o cobro diferido (Informativo)', 'Activos (fideicomitidos y generados) en fideicomisos mercantiles o encargos fiduciarios donde el contribuyente es constituyente  o aportante (Informativo)', 'Activos adquiridos por el valor de las utilidades reinvertidas generadas en el período anterior al declarado (Informativo)', 'TOTAL DEL ACTIVO', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'En efectivo', 'En activos diferentes del efectivo', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Crédito A Mutuo', 'Porción Corriente de Obligaciones Emitidas', 'A costo amortizado', 'A valor razonable', 'Porción Corriente de Arrendamientos Financieros Por Pagar', 'Pasivo corriente por arrendamiento', 'Impuesto A La Renta Por Pagar Del Ejercicio', 'Participación trabajadores por pagar del ejercicio', 'Obligaciones con el IESS', 'Jubilación Patronal', 'Otros Pasivos Corrientes Por Beneficios a Empleados', 'Por garantías', 'Por desmantelamiento', 'Por contratos onerosos', 'Por reestructuraciones de negocios', 'Por reembolsos a clientes', 'Por litigios', 'Por pasivos contingentes asumidos en una combinación de negocios', 'Otras', 'Anticipos de clientes', 'Subvenciones del Gobierno', 'Otros', 'Transferencias casa matriz y sucursales (del exterior)', 'Otros', 'TOTAL PASIVOS CORRIENTES', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Locales', 'Del exterior', 'Crédito a mutuo', 'Porción no corriente de obligaciones emitidas', 'A costo amortizado', 'A valor razonable', 'Porción no corriente de arrendamientos financieros por pagar', 'Pasivo no corriente por arrendamiento', 'Pasivo por Impuesto a la Renta diferido', 'Jubilación Patronal', 'Desahucio', 'Otros Pasivos No Corrientes Por Beneficios A Empleados', 'Por garantías', 'Por desmantelamiento', 'Por contratos onerosos', 'Por reestructuraciones de negocios', 'Por reembolsos a clientes', 'Por litigios', 'Por pasivos contingentes asumidos en una combinación de negocios', 'Otras', 'Anticipos de clientes', 'Subvenciones del gobierno', 'Otros', 'Transferencias casa matriz y sucursales (del exterior)', 'Otros', 'TOTAL PASIVOS NO CORRIENTES', 'Total de Intereses Implícitos No Debvengados (Futuros Gastos Financieros En El Estado De Resultados) Por Acuerdos Que Constituyen Efectivamente Una Transacción Financiera O Pago Diferido (Informativo)', 'Pasivos incurridos en fideicomisos mercantiles o encargos fiduciarios donde el contribuyente es constituyente  o aportante (Informativo)', 'TOTAL DEL PASIVO', 'Capital Suscrito y/o Asignado', '(-) Capital Suscrito No Pagado, Acciones en Tesorería', 'Aportes de Socios, Accionistas, Partícipes, Fundadores, Constituyentes, Beneficiarios U Otros Titulares De Derechos Representativos De Capital Para Futura Capitalización', 'Reserva legal', 'Reserva facultativa', 'Otras', 'Reserva de capital', 'Reserva por donaciones', 'Reserva por valuación (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC)', 'Superávit por revaluación de inversiones (procedente de la aplicación de normas ecuatorianas de contabilidad - NEC)', 'Utilidades acumuladas de ejercicios anteriores', '(-) Pérdidas acumuladas de ejercicios anteriores', 'Excedente / pérdida del ejercicio anterior (con socios)', 'Resultados acumulados por adopción por primera vez de las NIIF', 'Utilidad del ejercicio', 'Pérdida del ejercicio', 'Excedente / pérdida del ejercicio económico (con socios)', 'OTROS RESULTADOS INTEGRALES ACUMULADOS', 'SUPERÁVIT DE REVALUACIÓN ACUMULADO', 'Propiedades, Planta y Equipo', 'Activos intangibles', 'Otros', 'Ganancias y pérdidas acumuladas por inversiones en instrumentos de patrimonio medidos a valor razonable con cambios en otro resultado integral', 'Ganancias y pérdidas acumuladas por la conversión de estados financieros de un negocio en el extranjero', 'Ganancias y pérdidas actuariales acumuladas', 'La parte efectiva de las ganancias y pérdidas de los instrumentos de cobertura en una cobertura de flujos de efectivo', 'Otros', 'Dividendos declarados (distribuidos) a favor de titulares de derechos representativos de capital en el ejercicio fiscal  (Informativo)', 'Dividendos pagados (liquidados)  a titulares de derechos representativos de capital en el ejercicio fiscal  (Informativo)', 'TOTAL DEL PATRIMONIO', 'TOTAL PASIVO Y PATRIMONIO', 'Gravadas con tarifa diferente de 0% de IVA Total ingresos', 'Gravadas con tarifa diferente de 0% de IVA Valor exento / no objeto', 'Gravadas con tarifa 0% de iva o exentas de IVA Total ingresos', 'Gravadas con tarifa 0% de iva o exentas de IVA Valor exento / no objeto', 'Gravadas con tarifa diferente de 0% de IVA Total ingresos', 'Gravadas con tarifa diferente de 0% de IVA Valor exento / no objeto', 'Gravadas con tarifa 0% de iva o exentas de IVA Total ingresos', 'Gravadas con tarifa 0% de iva o exentas de IVA Valor exento / no objeto', 'De bienes Total ingresos', 'De bienes Valor exento / no objeto', 'De servicios Total ingresos', 'De servicios Valor exento / no objeto', 'Por prestación de servicios de construcción Total ingresos', 'Por prestación de servicios de construcción Valor exento / no objeto', 'Obtenidos bajo la modalidad de comisiones o similares (relaciones de agencia) Total ingresos', 'Obtenidos bajo la modalidad de comisiones o similares (relaciones de agencia) Valor exento / no objeto', 'Obtenidos por arrendamientos operativos Total ingresos', 'Obtenidos por arrendamientos operativos Valor exento / no objeto', 'TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS Total ingresos', 'TOTAL INGRESOS DE ACTIVIDADES ORDINARIAS Valor exento / no objeto', 'Relacionadas Total ingresos', 'Relacionadas Valor exento / no objeto', 'No Relacionadas Total ingresos', 'No Relacionadas Valor exento / no objeto', 'Procedentes de sociedades residentes o establecidas en Ecuador Total ingresos', 'Procedentes de sociedades residentes o establecidas en Ecuador Valor exento / no objeto', 'Procedentes de sociedades no residentes ni establecidas en Ecuador Total ingresos', 'Procedentes de sociedades no residentes ni establecidas en Ecuador Valor exento / no objeto', 'Ganancias netas por mediciones de activos biológicos a valor razonable menos costos de venta Total ingresos', 'Ganancias netas por mediciones de activos biológicos a valor razonable menos costos de venta Valor exento / no objeto', 'Ganancias netas por medición de propiedades de inversión a valor razonable Total ingresos', 'Ganancias netas por medición de propiedades de inversión a valor razonable Valor exento / no objeto', 'Ganancias netas por medición de instrumentos financieros a valor razonable Total ingresos', 'Ganancias netas por medición de instrumentos financieros a valor razonable Valor exento / no objeto', 'Ganancias netas por diferencias de cambios Total ingresos', 'Ganancias netas por diferencias de cambios Valor exento / no objeto', 'Utilidad en venta de propiedades, planta y equipo Total ingresos', 'Utilidad en venta de propiedades, planta y equipo Valor exento / no objeto', 'Utilidad en la enajenación de derechos representativos de capital Total ingresos', 'Utilidad en la enajenación de derechos representativos de capital Valor exento / no objeto', 'Ingresos devengados por subvenciones del gobierno y otras ayudas gubernamentales Total ingresos', 'Ingresos devengados por subvenciones del gobierno y otras ayudas gubernamentales Valor exento / no objeto', 'De activos financieros (reversión de provisiones para créditos incobrables) Total ingresos', 'De activos financieros (reversión de provisiones para créditos incobrables) Valor exento / no objeto', 'De inventarios Total ingresos', 'De inventarios Valor exento / no objeto', 'De activos no corrientes mantenidos para la venta Total ingresos', 'De activos no corrientes mantenidos para la venta Valor exento / no objeto', 'De activos biológicos Total ingresos', 'De activos biológicos Valor exento / no objeto', 'De propiedades, planta y equipo Total ingresos', 'De propiedades, planta y equipo Valor exento / no objeto', 'De activos intangibles Total ingresos', 'De activos intangibles Valor exento / no objeto', 'De propiedades de inversión Total ingresos', 'De propiedades de inversión Valor exento / no objeto', 'De activos de exploración, evaluación y explotación de recursos minerales Total ingresos', 'De activos de exploración, evaluación y explotación de recursos minerales Valor exento / no objeto', 'De inversiones no corrientes Total ingresos', 'De inversiones no corrientes Valor exento / no objeto', 'Otras Total ingresos', 'Otras Valor exento / no objeto', 'Por garantías Total ingresos', 'Por garantías Valor exento / no objeto', 'Por desmantelamientos Total ingresos', 'Por desmantelamientos Valor exento / no objeto', 'Por contratos onerosos Total ingresos', 'Por contratos onerosos Valor exento / no objeto', 'Por reestructuraciones de negocios Total ingresos', 'Por reestructuraciones de negocios Valor exento / no objeto', 'Por reembolsos a clientes Total ingresos', 'Por reembolsos a clientes Valor exento / no objeto', 'Por litigios Total ingresos', 'Por litigios Valor exento / no objeto', 'Por pasivos contingentes asumidos en una combinación de negocios Total ingresos', 'Por pasivos contingentes asumidos en una combinación de negocios Valor exento / no objeto', 'Otras Total ingresos', 'Otras Valor exento / no objeto', 'Jubilación patronal y desahucio Total ingresos', 'Jubilación patronal y desahucio Valor exento / no objeto', 'Otros Total ingresos', 'Otros Valor exento / no objeto', 'De recursos públicos Total ingresos', 'De recursos públicos Valor exento / no objeto', 'De otras locales Total ingresos', 'De otras locales Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Por lucro cesante Total ingresos', 'Por lucro cesante Valor exento / no objeto', 'Otros Total ingresos', 'Otros Valor exento / no objeto', 'Provenientes del exterior Total ingresos', 'Provenientes del exterior Valor exento / no objeto', 'Otros Total ingresos', 'Otros Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del exterior Total ingresos', 'Del exterior Valor exento / no objeto', 'Local Total ingresos', 'Local Valor exento / no objeto', 'Del

In [125]:
print(len(arrayDatos1_7))
print(len(textos))

461
461

In [126]:
dataFrameComplete1_7 = pd.DataFrame([arrayDatos1_7], columns=textos)
dataFrameComplete1_7

,Operaciones de activo,Operaciones de pasivo,Operaciones de ingreso,Operaciones de egreso,"Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares",Operaciones de activo,Operaciones de pasivo,Operaciones de ingreso,Operaciones de egreso,"Operaciones de regalías, servicios técnicos, administrativos, de consultoría y similares",...,Compras netas locales de bienes no producidos por el sujeto pasivo Valor No Deducible,Importaciones de bienes no producidos por el sujeto pasivo Costo,Importaciones de bienes no producidos por el sujeto pasivo Gasto,Importaciones de bienes no producidos por el sujeto pasivo Valor No Deducible,(-) Inventario final de bienes no producidos por el sujeto pasivo Costo,(-) Inventario final de bienes no producidos por el sujeto pasivo Gasto,(-) Inventario final de bienes no producidos por el sujeto pasivo Valor No Deducible,Inventario inicial de materia prima Costo,Inventario inicial de materia prima Gasto,Inventario inicial de materia prima Valor No Deducible
0,0.00,0.00,16999072.30,141014.32,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,107583.53,0,0.0,519020.26,,nan,2561776.54,,nan

In [127]:
header = tabula.read_pdf(pdfOriginal, pages=1, area=(34.82,3.83,105.97,608.88), lattice=False, output_format="dataframe", encoding="latin-1")
dfHeader = header[0]
dfHeader = dfHeader.astype(object)

In [128]:
dfHeader

,Unnamed: 0,FORMULARIO 101,Unnamed: 2,DECLARACIÓN DEL IMPUESTO A LA RENTA Y PRESENTACIÓN DE BALANCES FORMULARIO ÚNICO SOCIEDADES Y ESTABLECIMIENTOS PERMANENTES,Unnamed: 4,Unnamed: 5
0,102,Año 2021,NaN,104 No. de formulario que sustituye,No.,992353929556.0
1,201,RUC 0190167348001,202.0,Razón o denominación social CORPORACION AZENDE...,NaN,NaN

In [129]:
rowAnio = dfHeader.iloc[0].to_dict()
rowRucName = dfHeader.iloc[1].to_dict()
print(rowAnio)
print(rowRucName)

{'Unnamed: 0': 102, 'FORMULARIO 101': 'Año 2021', 'Unnamed: 2': nan, 'DECLARACIÓN DEL IMPUESTO A LA RENTA Y PRESENTACIÓN DE BALANCES FORMULARIO ÚNICO SOCIEDADES Y ESTABLECIMIENTOS PERMANENTES': '104 No. de formulario que sustituye', 'Unnamed: 4': 'No.', 'Unnamed: 5': 992353929556.0}
{'Unnamed: 0': 201, 'FORMULARIO 101': 'RUC 0190167348001', 'Unnamed: 2': 202.0, 'DECLARACIÓN DEL IMPUESTO A LA RENTA Y PRESENTACIÓN DE BALANCES FORMULARIO ÚNICO SOCIEDADES Y ESTABLECIMIENTOS PERMANENTES': 'Razón o denominación social CORPORACION AZENDE S.A.', 'Unnamed: 4': nan, 'Unnamed: 5': nan}

In [130]:
listaColumnsHeader= [
    "Razón Social",
    rowRucName["FORMULARIO 101"].split(" ")[0],
    rowAnio["FORMULARIO 101"].split(" ")[0],
    rowAnio["DECLARACIÓN DEL IMPUESTO A LA RENTA Y PRESENTACIÓN DE BALANCES FORMULARIO ÚNICO SOCIEDADES Y ESTABLECIMIENTOS PERMANENTES"]

]
print(listaColumnsHeader)

['Razón Social', 'RUC', 'Año', '104 No. de formulario que sustituye']

In [131]:
razSoc = rowRucName["DECLARACIÓN DEL IMPUESTO A LA RENTA Y PRESENTACIÓN DE BALANCES FORMULARIO ÚNICO SOCIEDADES Y ESTABLECIMIENTOS PERMANENTES"]
primEspacio  = razSoc.find("CORPORACION")
razSoc = razSoc[primEspacio:]
print(razSoc)

CORPORACION AZENDE S.A.

In [132]:
listaDatosHeader=[
    razSoc,
    rowRucName["FORMULARIO 101"].split(" ")[1],
    rowAnio["FORMULARIO 101"].split(" ")[1],
    rowAnio["Unnamed: 5"],
]
print(listaDatosHeader)

['CORPORACION AZENDE S.A.', '0190167348001', '2021', 992353929556.0]

In [133]:
dataframeHeader = pd.DataFrame([listaDatosHeader], columns=listaColumnsHeader, dtype=object)
dataframeHeader

,Razón Social,RUC,Año,104 No. de formulario que sustituye
0,CORPORACION AZENDE S.A.,0190167348001,2021,992353929556.0

In [134]:
with pd.ExcelWriter(excel_output, engine="xlsxwriter") as writer:
    dataframeHeader.to_excel(writer, sheet_name="Encabezado", index=False)
    dataFrameComplete1_7.to_excel(writer, sheet_name="Datos", index=False)

In [135]:
#with pd.ExcelWriter(excel_output, engine="openpyxl", if_sheet_exists="overlay", mode="a") as writer:
#    dataframeHeader.to_excel(writer, sheet_name="Encabezado", header=False, index=False, startrow=len(dfAcumulado_encabezado)+1)
#    dataFrameComplete1_7.to_excel(writer, sheet_name="Datos", header=False,index=False, startrow=len(dfAcumulado_datos)+1)